apache/camel-k

Gopkg.toml

Use https instead of git for github.com/nicolaferraro/operator-sdk.git source

---

pkg/install/operator.go

@nicolaferraro as you suggested, ignore service recreation

Unable to reinstall the operator fixes #43

---

runtime/jvm/src/main/java/org/apache/camel/k/jvm/RoutesLoaders.java

kamel run runtime/examples/Sample.java fails with java.lang.NoClassDefFoundError

---

runtime/jvm/src/main/java/org/apache/camel/k/jvm/Routes.java
runtime/jvm/src/main/java/org/apache/camel/k/jvm/RoutesLoaders.java
runtime/jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersTest.java
runtime/jvm/src/test/resources/routes.xml

Add support for XML routes

---

README.md
build/Makefile
build/install_minishift.sh
build/minishift_add_role.sh

Added make install-minishift command to build

---

Gopkg.lock
pkg/client/cmd/run.go
pkg/util/log/annotation_scraper.go
pkg/util/log/pod_scraper.go
test/build_manager_integration_test.go
test/local_builder_integration_test.go
test/log_scrape_integration_test.go
test/testing_env.go

Fixes #33.
It dynamically follows all pods of a integration.

Pod log implementation

---

Gopkg.lock
pkg/client/cmd/completion_bash.go
pkg/client/cmd/run.go
pkg/stub/action/integration/build.go
pkg/stub/action/integration/util.go
pkg/util/util.go

Groovy regression

---

runtime/jvm/src/main/java/org/apache/camel/k/jvm/RoutesLoaders.java

Avoid deprecated addRoutes (replaced by includeRoutes)

---

docs/developers.adoc

Dead link in Developer's guide "runtime"

---

.travis.yml

Add travis build info

---

Gopkg.lock
cmd/kamel/kamel.go
pkg/client/cmd/run.go
pkg/util/util.go
pkg/util/watch/watch.go
vendor/github.com/arsham/blush/LICENSE
vendor/github.com/arsham/blush/blush/blush.go
vendor/github.com/arsham/blush/blush/colour.go
vendor/github.com/arsham/blush/blush/doc.go
vendor/github.com/arsham/blush/blush/errors.go
vendor/github.com/arsham/blush/blush/find.go
vendor/github.com/arsham/blush/internal/reader/reader.go
vendor/github.com/arsham/blush/internal/tools/dir.go
vendor/github.com/arsham/blush/internal/tools/strings.go

- improve status tracking
- improve runtime logging set-up
- add some colours while watching integrations logs

Misc fixing

---

pkg/build/publish/kaniko_publisher.go

Use a working kaniko sha

---

pkg/client/cmd/run.go

Cannot configure traits

---

pkg/client/cmd/run.go

Add an option to the run command:
-o, --output string           Output format. One of: json|yaml

feat: #207 Provide option to get the Json/Yaml of a integration

---

docs/traits.adoc
pkg/builder/builder.go
pkg/builder/builder_types.go
pkg/builder/kaniko/kaniko.go
pkg/platform/build.go
pkg/trait/knative.go

Fix #226 
Also added some doc about the Knative trait

Fix kaniko build

---

deploy/operator-deployment-kubernetes.yaml
deploy/operator-deployment-openshift.yaml
deploy/resources.go
runtime/camel-knative/pom.xml
runtime/catalog-builder/pom.xml
runtime/dependency-lister/pom.xml
runtime/groovy/pom.xml
runtime/jvm/pom.xml
runtime/kotlin/pom.xml
runtime/pom.xml
version/version.go

Let's run some integration tests..

Bump version to 0.0.6-SNAPSHOT

---

pkg/builder/builder.go

temporary build folder not cleaned up

---

README.adoc
deploy/builder-pvc.yaml
deploy/operator-deployment-kubernetes.yaml
deploy/operator-deployment-openshift.yaml
deploy/resources.go
docs/gke-setup.adoc
pkg/apis/camel/v1alpha1/types.go
pkg/builder/builder.go
pkg/builder/kaniko/publisher.go
pkg/client/cmd/install.go
pkg/install/operator.go

Make it work on GKE

---

runtime/catalog-builder/pom.xml
runtime/groovy/pom.xml
runtime/groovy/src/test/groovy/org/apache/camel/k/groovy/dsl/IntegrationTest.groovy
runtime/jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersTest.java
runtime/jvm/src/test/resources/MyRoutesWithNestedClass.java
runtime/pom.xml

Update runtime dependencies

---

pkg/trait/knative.go
pkg/trait/knative_test.go
pkg/util/kubernetes/collection.go
pkg/util/util.go

Allow using compressed sources in Knative profile

---

pkg/apis/camel/v1alpha1/types.go
pkg/client/cmd/run.go
pkg/gzip/compress.go
pkg/metadata/http.go
pkg/metadata/metadata.go
pkg/metadata/metadata_http_test.go
pkg/metadata/types.go
pkg/trait/builder.go
pkg/trait/builder_test.go
pkg/trait/catalog.go
pkg/trait/debug.go
pkg/trait/debug_test.go
pkg/trait/dependencies.go
pkg/trait/deployment.go
pkg/trait/ingress.go
pkg/trait/istio.go
pkg/trait/knative.go
pkg/trait/knative_test.go
pkg/trait/owner.go
pkg/trait/route.go
pkg/trait/service.go
pkg/trait/springboot.go
pkg/trait/trait.go
pkg/trait/trait_test.go
pkg/trait/types.go
pkg/util/kubernetes/replace.go
pkg/util/kubernetes/util.go

Some experiment about traits life-cycle  see #268

Traits lifecycle

---

pkg/apis/camel/v1alpha1/integration_types.go
pkg/controller/integration/initialize.go

Add a state to integrations waiting for platform to be ready

---

deploy/camel-catalog.yaml
deploy/platform-cr.yaml
deploy/resources.go
pkg/apis/camel/v1alpha1/integrationcontext_types.go
pkg/apis/camel/v1alpha1/integrationplatform_types.go
pkg/builder/builder.go
pkg/builder/builder_steps.go
pkg/builder/builder_types.go
pkg/cmd/install.go
pkg/controller/integrationcontext/build.go
test/build_manager_integration_test.go

Allow to configure the base image used to run integrations

---

pkg/apis/camel/v1alpha1/integration_types_support.go
pkg/builder/builder.go
pkg/builder/builder_steps.go
pkg/builder/builder_types.go
pkg/builder/kaniko/kaniko.go
pkg/builder/s2i/s2i.go
pkg/controller/integration/build_image.go
pkg/controller/integrationcontext/build.go
pkg/trait/builder.go
pkg/trait/builder_test.go
pkg/util/kubernetes/util.go
test/build_manager_integration_test.go

With this PR I have refactored the builder so we can add event handlers and
react to build state changes. This make it possible - as example - to perform 
resources updates as latest step of the build process avoiding incnsistent
contexts when the incremental builder search for compatible images

builder: add hooks to the builder state changes to update resources when the build completes

---

docs/traits.adoc
pkg/trait/catalog.go
pkg/trait/deployment.go
pkg/trait/jolokia.go

Jolokia trait initial implementation

---

examples/RestWithRestlet.java
runtime/camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/loader/JavaSourceLoader.java
runtime/camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersTest.java
runtime/camel-k-runtime-jvm/src/test/resources/MyRoutesWithRestConfiguration.java

The example RestWithRestlet does not work calling its service via curl or webbrowser

---

runtime/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeComponent.java
runtime/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeConfiguration.java
runtime/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
runtime/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeSupport.java
runtime/camel-knative/src/main/java/org/apache/camel/component/knative/ce/CloudEventsProcessors.java
runtime/camel-knative/src/main/java/org/apache/camel/component/knative/ce/V01.java
runtime/camel-knative/src/main/java/org/apache/camel/component/knative/ce/V02.java
runtime/camel-knative/src/test/java/org/apache/camel/component/knative/CloudEventsV01Test.java
runtime/camel-knative/src/test/java/org/apache/camel/component/knative/CloudEventsV02Test.java

camel-knative: support for cloud events specs v0.2

---

runtime/camel-k-maven-plugin/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-maven-plugin/src/main/resources/META-INF/NOTICE.txt
runtime/camel-k-runtime-core/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-runtime-core/src/main/resources/META-INF/NOTICE.txt
runtime/camel-k-runtime-groovy/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-runtime-groovy/src/main/resources/META-INF/NOTICE.txt
runtime/camel-k-runtime-jvm/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-runtime-jvm/src/main/resources/META-INF/NOTICE.txt
runtime/camel-k-runtime-kotlin/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-runtime-kotlin/src/main/resources/META-INF/NOTICE.txt
runtime/camel-k-runtime-spring-boot-layout/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-runtime-spring-boot-layout/src/main/resources/META-INF/NOTICE.txt
runtime/camel-k-runtime-spring-boot/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-runtime-spring-boot/src/main/resources/META-INF/NOTICE.txt
runtime/camel-k-runtime-yaml/src/main/resources/META-INF/LICENSE.txt
runtime/camel-k-runtime-yaml/src/main/resources/META-INF/NOTICE.txt
runtime/camel-knative-http/src/main/resources/META-INF/LICENSE.txt
runtime/camel-knative-http/src/main/resources/META-INF/NOTICE.txt
runtime/camel-knative/src/main/resources/META-INF/LICENSE.txt
runtime/camel-knative/src/main/resources/META-INF/NOTICE.txt
runtime/pom.xml

- add LICENSE.txt
- add NOTICE.txt
- add release info to root pom

chore(runtime): prepare for deployment

---

pkg/trait/knative_service.go
pkg/trait/knative_test.go
runtime/camel-k-runtime-core/src/main/java/org/apache/camel/k/Source.java
runtime/camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/loader/JavaClassLoader.java
runtime/camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/loader/JavaSourceLoader.java
runtime/camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersTest.java
runtime/camel-k-runtime-jvm/src/test/resources/MyRoutes.java
runtime/camel-k-runtime-jvm/src/test/resources/MyRoutesWithNameOverride.java
runtime/camel-k-runtime-jvm/src/test/resources/MyRoutesWithNestedClass.java
runtime/camel-k-runtime-jvm/src/test/resources/MyRoutesWithRestConfiguration.java

Error while deploying integration in Knative based environment

---

runtime/camel-k-runtime-jvm/pom.xml
runtime/camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/loader/JavaSourceLoader.java
runtime/camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/MyRoutes.java
runtime/camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersCommonTest.java
runtime/camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersTest.java
runtime/camel-k-runtime-jvm/src/test/resources/MyRoutesWithPackage.java

Cannot deploy integration if not in the root package

---

Gopkg.lock
assets/json-schema/CamelCatalog.json
assets/json-schema/Integration.json
assets/json-schema/IntegrationContext.json
assets/json-schema/IntegrationPlatform.json
cmd/util/json-schema-gen/jsonschemagen.go
script/Makefile
vendor/github.com/alecthomas/jsonschema/COPYING
vendor/github.com/alecthomas/jsonschema/reflect.go

add a tool to generate json schema from custom resources 

---

assets/json-schema/Integration.json
assets/json-schema/IntegrationContext.json
assets/json-schema/IntegrationPlatform.json
cmd/util/publisher/publisher.go
pkg/apis/camel/v1alpha1/integration_types.go
pkg/apis/camel/v1alpha1/integrationcontext_types.go
pkg/apis/camel/v1alpha1/integrationplatform_types.go
pkg/builder/builder_steps.go
pkg/builder/builder_steps_test.go
pkg/builder/builder_types.go
pkg/builder/springboot/generator.go
pkg/cmd/install.go
pkg/controller/integration/build_image.go
pkg/controller/integration/util.go
pkg/controller/integrationcontext/build.go
pkg/controller/integrationplatform/initialize.go
pkg/trait/camel.go
pkg/trait/environment.go
pkg/trait/rest-dsl.go
pkg/trait/types.go
pkg/util/defaults/defaults.go
pkg/util/test/catalog_test.go
test/builder_integration_test.go
version/version.go

add an option to set which runtime version the operator should to run integrations

---

docs/cluster-setup.adoc

Resolves #509 
- Added instructions to setup minikube
- Updated instructions on installing knative

minikube doc update

---

pkg/cmd/delete.go
pkg/util/kubernetes/sanitize_test.go

fix: Allow file names as delete cmd argument

---

pkg/trait/probes.go
pkg/trait/probes_test.go

Add option to health probes

---

pkg/util/kubernetes/sanitize.go
pkg/util/kubernetes/sanitize_test.go

fix: Improve how SanitizeName handles paths and URLs

---

pkg/apis/camel/v1alpha1/integrationplatform_types.go
pkg/builder/builder_steps_test.go
pkg/builder/s2i/publisher.go
pkg/cmd/install.go
pkg/controller/integrationplatform/initialize.go
pkg/util/kubernetes/wait.go
test/builder_integration_test.go

Timeout in S2I build

---

pkg/trait/container.go
pkg/trait/trait_catalog.go

support for cpu and memory requests/limits
Fixes #570

allow to configure resources requests/limits

---

docs/traits.adoc
examples/knative/reader.groovy
examples/knative/writer.groovy
pkg/apis/camel/v1alpha1/knative/types_support.go
pkg/trait/knative.go
pkg/trait/knative_test.go
pkg/trait/trait_types.go
pkg/util/knative/knative.go
pkg/util/knative/uri.go
pkg/util/knative/uri_test.go
pkg/util/kubernetes/util.go

Fixes #553
Requires https://github.com/apache/camel-k-runtime/pull/35

knative: create full camel environment

---

pkg/trait/knative.go
pkg/util/knative/knative.go

Fix #579: fix namespace in subscription

---

pkg/metadata/metadata_dependencies_test.go
pkg/util/source/inspector.go

Fix #575: recognize hystrix automatically

---

Gopkg.lock
docs/traits.adoc
pkg/trait/istio.go
pkg/trait/istio_test.go

istio: allow to control annotation sidecar.istio.io/inject i

---

README.adoc

My repo for changes is here: https://github.com/stevef1uk/camel-k

Updated README for configmap

---

pkg/controller/integration/integration_controller.go

fix: Integration stuck waiting for platform

---

assets/json-schema/Integration.json
deploy/camel-catalog-2.24.0.yaml
deploy/resources.go
pkg/util/defaults/defaults.go
pkg/util/test/catalog_test.go
script/Makefile

Update to Camel 2.24.0

---

docs/cluster-setup.adoc

Just updated the minishift document by adding a reference of installing knative on minishift.

#701 Update the cluster-setup document for installing knative on minishift

---

examples/resources-route.groovy

kamel run --dev examples/resources-route.groovy issues Cannot find resource

---

pkg/cmd/install.go
pkg/controller/integrationplatform/create.go
pkg/platform/resources.go

Don't automatically install contexts upon platform installation

---

script/Makefile
script/cross_compile.sh

Fix #707: sign released artifacts

---

pkg/trait/knative_service.go

Fix #722
Some rules have been enforced in 0.6.0: https://github.com/knative/serving/blob/ce96dd74b1c85f024d63ce0991d4bf61aced582a/pkg/apis/serving/fieldmask.go#L311-L312

Filter allowed env variables in Knative

---

pkg/cmd/root.go

fix: Honour KUBECONFIG

---

deploy/cr-example.yaml
deploy/resources.go

 fix: CR example is using wrong schema

---

docs/traits.adoc
pkg/trait/service.go
pkg/trait/service_test.go

Service trait: confusing behavior

---

pkg/apis/camel/v1alpha1/camelcatalog_types_support.go
pkg/builder/builder_utils.go
pkg/trait/camel.go
pkg/trait/environment_test.go
pkg/trait/istio_test.go
pkg/trait/rest-dsl.go
pkg/trait/trait_types.go
pkg/util/maven/maven_project_test.go
pkg/util/maven/maven_types.go

Automatically create catalogs from maven

---

pkg/util/kubernetes/sanitize.go
pkg/util/kubernetes/sanitize_test.go

fix: Integration naming issues with numbers in them

---

script/travis_build.sh

chore: Re-enable e2e tests

---

script/travis_build.sh

Revert "chore: Re-enable e2e tests"

---

pkg/trait/dependencies.go
pkg/trait/dependencies_test.go
pkg/trait/rest-dsl.go
pkg/trait/rest-dsl_test.go
pkg/util/kubernetes/util.go

fix: Dependencies & rest-dsl traits are never enabled

---

pkg/builder/builder_steps.go
pkg/builder/builder_steps_test.go

requires https://github.com/apache/camel-k-runtime/pull/106

chore(runtime): remove hardcoded log4j dependency

---

e2e/files/yaml.yaml
e2e/run_test.go

test(yaml): Add YAML e2e test

---

e2e/test_support.go
e2e/upgrade_test.go

Concurrency issue in the end to end tests

---

pkg/trait/container.go
pkg/trait/container_test.go
pkg/trait/deployment.go
pkg/trait/jolokia.go
pkg/trait/knative_service.go
pkg/trait/knative_service_test.go
pkg/trait/prometheus.go
pkg/trait/service_test.go
pkg/util/kubernetes/collection.go

Stable container name

---

docs/modules/ROOT/pages/traits.adoc
pkg/trait/istio.go
pkg/trait/istio_test.go
pkg/trait/trait_catalog.go

Disable Istio by default

---

e2e/files/knative1.groovy
e2e/files/knative2.groovy
e2e/files/knativech1.groovy
e2e/files/knativech2.groovy
e2e/knative_test.go
e2e/test_support.go
pkg/apis/camel/v1alpha1/knative/types_support.go
pkg/cmd/install.go
pkg/trait/knative.go
script/Makefile

Fix #856: lookup destination in multiple places and add e2e tests

---

pkg/controller/integrationplatform/initialize.go
pkg/platform/platform.go
pkg/util/knative/knative.go

Fix #815: determine correct profile at runtime when empty

---

deploy/olm-catalog/camel-k/1.0.0-M1-SNAPSHOT/camel-k.v1.0.0-M1-SNAPSHOT.clusterserviceversion.yaml

Fix #789: add correct example for operator hub

---

script/Makefile

@nicolaferraro , i will wounder, if testing binary file in repo requires for some reasons

Fix make clean for tests and remove binary file from repo

---

examples/camel-caffeine.groovy
examples/dns.js
examples/greetings.groovy
examples/knative/feed.groovy
examples/knative/printer.groovy
examples/knative/reader.groovy
examples/knative/splitter.groovy
examples/knative/writer.groovy
examples/kotlin-routes.kts
examples/props.js
examples/resources-route.groovy
examples/routes-rest.js
examples/routes.groovy
examples/routes.js
examples/simple.groovy
examples/simple.js

it allows to benefit from tooling based on Camel Language Server

Include modeline in examples #895

---

pkg/cmd/run.go
pkg/util/watch/watch.go

fix: Dev mode does not show if the build failed

---

pkg/controller/integration/integration_controller.go

No `Integration` CRs own `Build` CRs anymore.

chore: Remove unecessary watch on builds while reconciling integrations

---

script/Makefile

fix(build): Remove builder bin commands

---

pkg/builder/kaniko/publisher.go

Fixes #960. Speculatively fixes #965.

fix: Kaniko publisher step fails with IncrementalPackager

---

pkg/controller/integration/monitor.go
pkg/trait/gc.go
pkg/trait/gc_test.go
pkg/util/kubernetes/util.go

chore: GC trait improvements

---

pkg/controller/integration/integration_controller.go

```release-note
perf: Enqueue ReplicaSet updates only when replicas changed
```

perf: Enqueue ReplicaSet updates only when replicas changed

---

deploy/olm-catalog/camel-k/1.0.0-M2/camel-k.v1.0.0-M2.clusterserviceversion.yaml
deploy/olm-catalog/camel-k/camel-k.package.yaml
deploy/operator-role-olm.yaml

Relates to #1004.
```release-note
NONE
```

Update OLM manifests for 1.0.0-M2 release

---

e2e/files/knativegetpost1.groovy
e2e/files/knativegetpost2.groovy
e2e/files/knativemultihop1.groovy
e2e/files/knativemultihop2.groovy
e2e/files/knativemultihop3.groovy
e2e/knative_test.go
e2e/test_support.go

chore(tests): add integration tests for common knative issues

---

.gitignore
.golangci.yml
.pre-commit-config.yaml
.travis.yml
cmd/util/license-check/main.go
deploy/builder-role-kubernetes.yaml
deploy/builder-role-openshift.yaml
deploy/builder-service-account.yaml
deploy/olm-catalog/camel-k/0.3.4/camel-k.v0.3.4.clusterserviceversion.yaml
deploy/olm-catalog/camel-k/0.3.4/crd-build.yaml
deploy/olm-catalog/camel-k/0.3.4/crd-camel-catalog.yaml
deploy/olm-catalog/camel-k/0.3.4/crd-integration-context.yaml
deploy/olm-catalog/camel-k/0.3.4/crd-integration-platform.yaml
deploy/olm-catalog/camel-k/0.3.4/crd-integration.yaml
deploy/olm-catalog/camel-k/1.0.0-M1/camel-k.v1.0.0-M1.clusterserviceversion.yaml
deploy/olm-catalog/camel-k/1.0.0-M2/camel-k.v1.0.0-M2.clusterserviceversion.yaml
deploy/olm-catalog/camel-k/1.0.0-M3-SNAPSHOT/camel-k.v1.0.0-m3-SNAPSHOT.clusterserviceversion.yaml
e2e/files/yaml.yaml
examples/routes.yaml
pkg/util/kubernetes/customclient/scheme.go
script/Makefile
script/check_licenses.sh
script/headers/default-jvm.txt
script/headers/default.txt
script/headers/js.txt
script/headers/sh.txt
script/headers/xml.txt
script/headers/yaml.txt

Fix #988
```release-note
NONE
```

fix #988: add check for missing licenses before release

---

examples/camel-caffeine.groovy
examples/knative/README.adoc
examples/routes.groovy

chore: fix eaxmples

---

docs/modules/ROOT/pages/running/running.adoc

Fix typo in doc

---

release.adoc

Fix #989
This documents the steps used to do a release (so I'm no more the only one that can do it ;)).
It's also useful to having it shared, so that we can improve it over time.
Please, have a look: @oscerd, @davsclaus, @WillemJiang
Nicola
```release-note
NONE
```

fix #989: document the release process

---

pkg/util/digest/digest.go

Fix #1038
```release-note
NONE
```

Fix #1038: redeploy integration when trait config changes

---

deploy/operator-deployment.yaml
deploy/resources.go

fix the version of the operator image

---

examples/routes.js

Fixes #1065 
fix broken routes.js example 
```release-note
NONE
```

add wrapper for processor functions

---

pkg/trait/gc.go

chore(lint): fix formatting error to make CI happy again

---

script/Makefile

chore(build): disable go modules when performing go clean

---

.github/workflows/pr-build.yml
.github/workflows/pr-validate.yml

Enable github actions to build and validate pr

---

e2e/backward_compat_test.go
e2e/build_test.go
e2e/client_test.go
e2e/docker_hub_test.go
e2e/github_packages_test.go
e2e/install_test.go
e2e/knative_test.go
e2e/platformless_run_test.go
e2e/run_test.go
e2e/tekton_test.go
e2e/test_support.go
e2e/upgrade_test.go
e2e/util/dump.go
script/Makefile

chore(ci): dump namespace when tests fail in CI

---

pkg/controller/integrationplatform/create_test.go
pkg/controller/integrationplatform/initialize_test.go
pkg/controller/integrationplatform/warm_test.go
pkg/platform/platform.go
pkg/util/knative/apis.go
pkg/util/knative/enabled.go
pkg/util/knative/knative.go

Fix #1125 
```release-note
NONE
```

Fix #1125: use all known knative types to check if it's enabled

---

.mvn/wrapper/maven-wrapper.properties
script/package_maven_artifacts.sh

Update to maven 3.6.3

---

pkg/apis/camel/v1/camelcatalog_types.go
pkg/apis/camel/v1/zz_generated.deepcopy.go
pkg/metadata/metadata_dependencies_test.go
pkg/util/camel/camel_runtime_catalog.go
pkg/util/camel/camel_util.go
pkg/util/source/inspector.go

fixes #1095
```release-note
NONE
```

Auto detect Camel components via FQN classnames

---

pkg/cmd/run.go

Follow up to #1178.
```release-note
NONE
```

fix: Avoid potential nil pointer dereference in wait & dev modes

---

pkg/trait/jolokia.go

```release-note
fix(jolokia): Order consistently Jolokia agent options when encoded as environment variable
```

fix(jolokia): Order consistently Jolokia agent options when encoded as environment variable

---

pkg/trait/jolokia.go
pkg/util/digest/digest.go
pkg/util/util.go

chore(jolokia): Declare client certificate Jolokia trait option as an array

---

deploy/crd-build.yaml
deploy/crd-camel-catalog.yaml
deploy/crd-integration-kit.yaml
deploy/crd-integration-platform.yaml
deploy/crd-integration.yaml
deploy/olm-catalog/camel-k/1.0.0-rc1/camel-k.v1.0.0-rc1.clusterserviceversion.yaml
deploy/olm-catalog/camel-k/1.0.0-rc1/crd-build.yaml
deploy/olm-catalog/camel-k/1.0.0-rc1/crd-camel-catalog.yaml
deploy/olm-catalog/camel-k/1.0.0-rc1/crd-integration-kit.yaml
deploy/olm-catalog/camel-k/1.0.0-rc1/crd-integration-platform.yaml
deploy/olm-catalog/camel-k/1.0.0-rc1/crd-integration.yaml
deploy/olm-catalog/camel-k/1.0.0-rc2-snapshot/camel-k.v1.0.0-rc2-snapshot.clusterserviceversion.yaml
deploy/olm-catalog/camel-k/1.0.0-rc2-snapshot/crd-build.yaml
deploy/olm-catalog/camel-k/1.0.0-rc2-snapshot/crd-camel-catalog.yaml
deploy/olm-catalog/camel-k/1.0.0-rc2-snapshot/crd-integration-kit.yaml
deploy/olm-catalog/camel-k/1.0.0-rc2-snapshot/crd-integration-platform.yaml
deploy/olm-catalog/camel-k/1.0.0-rc2-snapshot/crd-integration.yaml
deploy/resources.go

chore(crd): update the CRD versions

---

assets/json-schema/CamelCatalog.json
deploy/olm-catalog/camel-k/1.0.0-rc1/camel-k.v1.0.0-rc1.clusterserviceversion.yaml
deploy/olm-catalog/camel-k/1.0.0-rc2-snapshot/camel-k.v1.0.0-rc2-snapshot.clusterserviceversion.yaml

chore(olm): set empty spec in CSV to pass courier validation

---

pkg/cmd/describe_kit.go
pkg/cmd/describe_platform.go
pkg/cmd/kit_create.go

fixes #1221
```release-note
NONE
```

fix: Command execution fails with result must be a pointer

---

.github/workflows/pr-knative.yml

2nd attempt
```release-note
NONE
```

Fix #1162: Knative e2e tests with Kourier

---

pkg/install/openshift.go

Fixes #1242.
```release-note
fix(install): Check permission to create OpenShift ConsoleCLIDownload resource
```

fix(install): Check permission to create OpenShift ConsoleCLIDownload resource

---

e2e/test_support.go
e2e/uninstall_test.go
pkg/cmd/root.go
pkg/cmd/uninstall.go

Fixes #38.
Slightly modified from @ipolyzos previous PR #891.
```release-note
NONE
```

Add uninstall command

---

script/build_catalog.sh

chore: Run Maven in batch mode to reduce log noise

---

pkg/trait/environment.go
pkg/trait/environment_test.go
pkg/trait/trait_test.go
pkg/trait/trait_types.go

Allow to inject data from externally crafted secrets #1261 (camel-k bits)

---

examples/pulsar.groovy

Additional descriptive example with Apache Pulsar written in Groovy.
```release-note
NONE
```

Apache Pulsar and Groovy example

---

.github/workflows/openshift.yml

chore(ci): test openshift on GH actions

---

pkg/metadata/metadata_dependencies_test.go
pkg/util/source/inspector.go
pkg/util/source/inspector_xml.go
pkg/util/source/inspector_yaml.go

Fix Quarkus dependency detection

---

examples/pulsar.groovy

fix typo puslar -> pulsar

---

e2e/test_support.go

Fix output redirection for external `kamel` bin.

[FIX] Fix output redirection for external bin

---

pkg/platform/defaults.go

fix(platform): Default to pod build strategy for Kaniko

---

.github/workflows/build.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/openshift.yml
.github/workflows/validate.yml
e2e/files/knative3.groovy
e2e/knative_test.go
pkg/trait/container.go

Fix #1205
Fix #1257
```release-note
NONE
```

Some small Knative fixes

---

pkg/cmd/run.go

Fixes #1300 
```release-note
NONE
```

Unable to run the polyglot sample 

---

e2e/test_support.go

I have found that https://github.com/apache/camel-k/blob/master/e2e/test_support.go#L938-L943 does not work on OCP. This is caused by https://github.com/openshift/origin/issues/3819.
This is my workaround. I know that it is not perfect because `update` operation on project is not enabled by default for a regular user.
Do you see any other options how to fix this?

Workaround. Labels are not supported on ProjectRequest

---

pkg/apis/camel/v1/camelcatalog_types_support.go

Wrong knative dependency #1337

---

pkg/trait/container.go
pkg/trait/container_probes_test.go

Fix probes port detection

---

pkg/builder/builder_steps.go
pkg/builder/builder_types.go

chore(builder): small refactor to image context lookup

---

pkg/util/source/inspector_yaml.go
pkg/util/source/inspector_yaml_test.go

Fix YAML rest-dsl inspections

---

docs/modules/ROOT/pages/traits/cron.adoc

```release-note
NONE
```
Fixes #1401

Fixed cron trait docs

---

pkg/install/optional.go
pkg/metadata/metadata.go
pkg/metadata/metadata_capabilities_test.go
pkg/util/source/inspector.go
pkg/util/source/inspector_groovy.go
pkg/util/source/inspector_java_script.go
pkg/util/source/inspector_java_source.go
pkg/util/source/inspector_kotlin.go
pkg/util/source/inspector_xml.go
pkg/util/source/inspector_yaml.go

Properly handle platform-http component in routes

---

deploy/templates/groovy.tmpl
deploy/templates/java.tmpl
deploy/templates/js.tmpl
deploy/templates/kts.tmpl
deploy/templates/xml.tmpl
deploy/templates/yaml.tmpl

Fixes #1417
```release-note
NONE
```

Add license headers to files generated with kamel init

---

.github/workflows/knative.yml
e2e/yaks/knative/receiver.groovy
e2e/yaks/knative/source.yaml
e2e/yaks/knative/sources.feature
e2e/yaks/knative/yaks-config.yaml
e2e/yaks/yaks-config.yaml

chore(CI): add knative sources test with YAKS

---

.github/workflows/knative.yml

Attempt to upgrade knative CI

---

release.adoc

Update the document with information on how to update the homebrew formula of _kamel_ for new releases.
```release-note
Camel K CLI is also available on homebrew and linuxbrew
```

information to update the homebrew formula

---

examples/saga/Payment.java

Remove unused import package in example

---

docs/modules/traits/pages/quarkus.adoc

Fixed link in Quarkus.adoc

---

docs/modules/ROOT/pages/uninstalling.adoc

Update the documentation for the **uninstall** command as per #1445 to reflect changes in #1465

Uninstall all doc

---

examples/routes-rest.js

fix: Use platform HTTP server in REST DSL example

---

pkg/builder/spectrum/publisher.go

chore(builder): enable Spectrum to publish to authenticated registries

---

.travis.yml

chore(ci): install latest openjdk in Travis

---

.github/workflows/build.yml
.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/openshift.yml
.github/workflows/release.yml

chore(ci): bump setup jdk action in CI

---

.github/workflows/stale.yaml

Add stale action

---

.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/openshift.yml

chore(ci): fix ci repository configuration

---

.github/workflows/backport.yml

chore: add a backport action

---

pkg/util/olm/operator.go

Set the OLM channel used on install to 'stable'

#1524 set the OLM channel used on install to 'stable'

---

pkg/util/olm/operator.go

 #1524 set the OLM channel used on install to 'stable'

---

script/Makefile
script/install_crc.sh

solves #1410 
In the future, we can try to leverage https://github.com/code-ready/crc/issues/1230 to have something similar to what is done for minishift install. I'll add a note on the website once merged. Thanks!
```release-note
NONE
```

support make install-crc #1410

---

.github/workflows/backport.yml

Fixes #1559
```release-note
NONE
```

Switch to Syndesis backport github action

---

.github/workflows/backport.yml

Added back token for gh action

---

pkg/util/util.go

fix: bug in utility function

---

.github/workflows/backport.yml

Added token as parameter to backport gh action

---

pkg/cmd/run.go

Fix typo fo -> of

---

docs/modules/ROOT/pages/developers.adoc
docs/modules/ROOT/pages/installation/crc.adoc
docs/modules/ROOT/pages/installation/installation.adoc
docs/modules/ROOT/pages/uninstalling.adoc

add documentation for CRC #1410
Thanks !
```release-note
NONE
```

add documentation for CRC #1410

---

docs/modules/ROOT/pages/observability/monitoring.adoc

This adds the _Discovery_, _Alerting_ and _Autoscaling_ sections to the monitoring documentation.
Completes #1586.
```release-note
NONE
```

doc: Complete the monitoring documentation

---

deploy/traits.yaml

Fix typo missing space "featuresare" -> "features are"

---

.github/workflows/release.yml
script/Makefile
script/set_go_modules_version.sh
script/trigger_nightly_build.sh

Fix #1601
```release-note
NONE
```

Fix #1601: add v prefix to future tags

---

.asf.yaml

See https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#git.asf.yamlfeatures-Repositorymetadata
```release-note
NONE
```

Init .asf.yaml file

---

proposals/assets/camel-k-monitoring.svg
proposals/monitoring-security.adoc

doc: Update secured monitoring proposal for Quarkus/Knative single-port

---

proposals/monitoring-security.adoc

fix(doc): PodMonitoring -> PodMonitor

---

e2e/common/dev_mode_test.go
examples/SampleModeline.java
pkg/cmd/run.go

Fix #1536: take modeline changes into account in dev mode

---

cmd/kamel/main.go

Fixes https://github.com/apache/camel-k/issues/1646
```release-note
NONE
```

Add support for oidc

---

script/git_tag.sh

chore(release): create additional tags for go modules

---

docs/modules/ROOT/pages/architecture/cr/build.adoc
docs/modules/ROOT/pages/architecture/cr/camel-catalog.adoc
docs/modules/ROOT/pages/architecture/cr/integration-kit.adoc
docs/modules/ROOT/pages/architecture/cr/integration-platform.adoc
docs/modules/ROOT/pages/architecture/operator.adoc
docs/modules/ROOT/pages/observability/monitoring.adoc

Fixes (mainly typo) in documentation

---

pkg/cmd/completion_bash.go

Thanks!
```release-note
NONE
```

Add describe command completion

---

.github/workflows/automatic-changelog-update.yml

Added an automatic changelog Github action

---

.github/workflows/automatic-changelog-update.yml

Changelog updater: run every hour

---

.github/workflows/automatic-changelog-update.yml

Automatic changelog: Let's run during the night only one time

---

cmd/kamel/main.go

Backport #1647 to 1.1.x.
```release-note
Fixed support for OIDC and IKS
```

Add support for oidc (#1647)

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/running/run-from-github.adoc

Add documentation about kamel run from github

---

docs/modules/ROOT/pages/kamelets/kamelets.adoc

Change in keyword from "explicity" to "explicitly"
```release-note
NONE
```

Document Update

---

README.adoc
helm/camel-k/README.md

```release-note
Official chat moved from Gitter to Zulip (https://camel.zulipchat.com)
```

Switch from Gitter to Zulip

---

e2e/yaks/kamelets/yaks-config.yaml

Fixes this error ```Error from server (NotFound): kameletbindings.camel.apache.org "timer-source" not found```

[fix] Use correct name of kameletbinding

---

docs/modules/ROOT/pages/architecture/architecture.adoc

fix(doc): Set architecture diagram width explicitly

---

script/Makefile
script/build_catalog.sh

chore(build): remove reference to staging repo

---

.github/workflows/automatic-changelog-update.yml

Added workflow dispatch to changelog gh action

---

e2e/knative/files/display.groovy
e2e/knative/kamelet_test.go
e2e/support/test_support.go
pkg/cmd/reset.go
pkg/controller/kameletbinding/common.go
pkg/controller/kameletbinding/initialize.go
pkg/controller/kameletbinding/kamelet_binding_controller.go
pkg/controller/kameletbinding/monitor.go

Fix #1785
```release-note
NONE
```

Fix #1785: propagate klb changes to integrations

---

pkg/util/camel/camel_runtime_catalog.go
pkg/util/source/inspector.go
pkg/util/source/inspector_yaml.go
pkg/util/source/inspector_yaml_test.go

Fix #1549
```release-note
NONE
```

Fix #1549: auto-detect json in YAML

---

.github/workflows/knative.yml
e2e/yaks/common/kamelet-binding-broker/kamelet.feature
e2e/yaks/common/kamelet-binding/kamelet.feature
e2e/yaks/common/kamelet/kamelet.feature
e2e/yaks/common/knative-sinkbinding/sinkbinding.feature
e2e/yaks/common/knative/sources.feature

chore(test): upgrade YAKS to 0.1.0

---

docs/modules/ROOT/nav-end.adoc
docs/modules/ROOT/pages/observability/operator.adoc
docs/modules/ROOT/pages/troubleshooting/operating.adoc

chore(doc): Add standard operation procedures to troubleshooting guide

---

e2e/yaks/common/apache-kamelet-catalog/kamelet.feature

fix: Fix kamelet.feature for YAKS version 0.1.0

---

e2e/common/jolokia_test.go

As a starter I added an e2e test for Jolokia trait.
```release-note
NONE
```

chore(e2e): add test for Jolokia trait #1547

---

config/crd/bases/camel.apache.org_kameletbindings.yaml
deploy/crd-kamelet-binding.yaml
deploy/olm-catalog/camel-k-dev/1.3.0-snapshot/kameletbindings.camel.apache.org.crd.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml

Follows-up #1852.
```release-note
NONE
```

chore(crd): Regenerate KameletBinding CRD

---

deploy/traits.yaml
docs/modules/traits/pages/environment.adoc

chore(doc): generate doc for environment trait

---

pkg/cmd/uninstall.go
pkg/install/secret.go

feat(uninstall): add --skip-registry-secret option and make uninstall remove registry secret #1859

---

e2e/common/affinity_test.go

chore(e2e): add test for Affinity trait #1547

---

docs/modules/ROOT/pages/installation/digitalocean.adoc

Fix typo DigitalOcen --> DigitalOcean

---

e2e/yaks/openshift/monitoring/dependencyInstall.sh
e2e/yaks/openshift/monitoring/obtainToken.sh

Backport  #1880 to 1.3.x

---

pkg/cmd/modeline.go

Backport #1873 to 1.3.x

---

.github/workflows/build.yml
.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/local.yml
.github/workflows/openshift.yml
.github/workflows/release.yml

Setup JDK with the authorised `AdoptOpenJDK/install-jdk@v1` action.
```release-note
NONE
```

fix(ci): Use AdoptOpenJDK/install-jdk@v1 action

---

.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/openshift.yml
.github/workflows/stale.yaml
script/Makefile

chore: Remove duplicated version target in Makefile

---

pkg/cmd/install.go

Fix #1884
```release-note
NONE
```

fix(cli): remove install camel-version flag

---

examples/saga/Flight.java
examples/saga/Saga.java
examples/saga/Train.java
pkg/builder/runtime/quarkus.go

Fix saga example

---

examples/kamelets/timer-source-log-sink/timer-source.kamelet.yaml
examples/kamelets/timer-source/timer-source.kamelet.yaml

chore(examples): kamelets properties fix

---

pkg/install/cluster.go

chore(crd): Use conversion-gen API for structured conversion of CRDs to v1beta1

---

docs/modules/ROOT/pages/contributing/developers.adoc

Correct the documented syntax for Dependency trait usage

---

pkg/trait/builder.go
pkg/trait/quarkus.go
pkg/trait/quarkus_test.go

chore(build): Sort builder steps by phase in Build spec

---

.github/workflows/backport.yml
.gitmodules

Added Backport Github action

---

README.adoc

Test PR do not merge

---

README.adoc

Revert "Test PR do not merge"

---

.github/workflows/backport.yml

Remove node configuration from backport action. It is not needed

---

.github/workflows/backport.yml

Backport action: Added license

---

script/Makefile

fix(OLM): OLM bundle generation fixes

---

.github/workflows/automatic-changelog-update.yml
.gitmodules

Re-introduce changelog action

---

README.adoc

Fix a little typo good for testing backport action

---

config/manifests/bases/camel-k.clusterserviceversion.yaml

```release-note
fix(OLM): Add missing internal-objects annotation to Kustomize base CSV manifest
```

fix(OLM): Add missing internal-objects annotation to Kustomize base CSV manifest

---

config/manifests/bases/camel-k.clusterserviceversion.yaml

```release-note
fix(OLM): Fix generated OLM bundle installation
```

fix(OLM): Remove replaces field from Kustomize base CSV manifest

---

.gitmodules

Switch to a different backport implementation

---

README.adoc

I want to be picky, so I'm opening this PR to test the backport action.

Picky commit for testing backport action

---

.gitmodules

Revert "Switch to a different backport implementation"

---

config/rbac/operator-role-olm.yaml
config/rbac/operator-role-strimzi.yaml
deploy/operator-role-olm.yaml
deploy/operator-role-strimzi.yaml
helm/camel-k/templates/operator-role.yaml

Backport fix to #1992: allow accessing Strimzi "kafkatopics" instead of "topics"

---

docs/modules/ROOT/pages/configuration/configmap-secret.adoc
pkg/trait/container.go
pkg/trait/cron.go
pkg/trait/deployment.go
pkg/trait/environment.go
pkg/trait/knative_service.go
pkg/trait/knative_service_test.go
pkg/trait/trait_test.go
pkg/trait/trait_types.go
pkg/trait/util.go
pkg/trait/util_test.go

Fixes #1998.
```release-note
feat(conf): Mount source and resource ConfigMaps as subPaths instead of volumes
```

feat(conf): Mount source and resource ConfigMaps as subPaths instead of volumes

---

docs/modules/ROOT/pages/contributing/local-development.adoc

doc: camel k runtime local instructions

---

config/rbac/operator-role-olm.yaml

fix(olm): Add back lost rules to OLM role

---

helm/camel-k/templates/operator-role.yaml

chore(helm): Remove duplicated rule for servicebindings

---

helm/camel-k/templates/operator-role.yaml

fix(helm): Add missing permissions for PodDisruptionBudget resources

---

config/rbac/operator-role-kubernetes.yaml
config/rbac/operator-role-olm.yaml
config/rbac/operator-role-openshift.yaml
deploy/olm-catalog/camel-k-dev/1.4.0-snapshot/camel-k.v1.4.0-snapshot.clusterserviceversion.yaml
helm/camel-k/templates/operator-role.yaml

```release-note
fix(pdb): Add missing watch verb to PodDisruptionBudget resources RBAC
```
/cc @mmelko

fix(pdb): Add missing watch verb to PodDisruptionBudget resources RBAC

---

pkg/controller/integration/integration_controller.go
pkg/install/openshift.go
pkg/util/kubernetes/discovery.go

Fixes #2018.
```release-note
NONE
```

fix: ServiceBinding SAR check does not guaranty CRD is installed

---

docs/modules/ROOT/pages/troubleshooting/debugging.adoc

Point to documentation for debugging using VS Code

---

.github/workflows/knative.yml

fix(ci): Use kubectl wait command to check Knative readiness

---

.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml

chore(ci): Pin the Kubernetes version deployed by Kind

---

config/manifests/bases/camel-k.clusterserviceversion.yaml
deploy/olm-catalog/camel-k-dev/1.4.0-snapshot/camel-k.v1.4.0-snapshot.clusterserviceversion.yaml

chore(olm): Update IntegrationPlatform creation step in CSV description

---

docs/modules/ROOT/pages/troubleshooting/debugging.adoc

For the moment lets remove absolute path

---

.github/workflows/knative.yml

Backport #2036 to 1.3.x branch.
```release-note
NONE
```

Backport #2036 to 1.3.x branch

---

pkg/apis/camel/v1/integration_types.go
pkg/client/camel/clientset/versioned/typed/camel/v1/fake/fake_integration.go
pkg/client/camel/clientset/versioned/typed/camel/v1/integration.go

chore(api): Add Scale methods to the Integration generated client API

---

e2e/common/upgrade_test.go

Wait for operator to start before scaling it to zero

---

e2e/common/run_test.go
e2e/common/scale_test.go
e2e/support/test_support.go

chore(test): Add integration scaling e2e tests

---

pkg/cmd/completion_bash.go

```release-note
NONE
```
Thanks !

feat: add command completion for connect flag

---

e2e/common/pdb_test.go
e2e/support/test_support.go

test: Add PodDisruptionBudget trait e2e tests

---

e2e/common/scale_test.go

chore(e2e): Add test case to Integration scaling e2e tests

---

addons/strimzi/duck/v1beta1/doc.go
addons/strimzi/duck/v1beta1/duck_types.go
pkg/apis/camel/v1/camelcatalog_types.go
pkg/apis/camel/v1/doc.go
pkg/apis/camel/v1alpha1/doc.go
pkg/apis/camel/v1alpha1/kamelet_binding_types.go

fix(api): Remove deprecated deepcopy-gen markers

---

.github/workflows/openshift.yml
e2e/common/pdb_test.go
e2e/common/traits/pdb_test.go

test: Add eviction cases to the PodDisruptionBudget trait e2e tests

---

e2e/common/scale_test.go
e2e/common/traits/pdb_test.go
e2e/support/test_support.go

chore(e2e): Assert Integration readiness condition in scaling e2e tests

---

e2e/support/test_support.go

Operator deployment labels are different (does not contain"camel.apache.org/component=operator"`) when the deployment is created by the OLM. Migrate ScaleOperator function to get by name instead of the labels.

Operator labels are different when OLM is used

---

pkg/cmd/util_dependencies.go
pkg/platform/defaults.go
pkg/util/maven/maven_project.go
pkg/util/maven/maven_settings.go
pkg/util/maven/maven_settings_test.go
pkg/util/maven/maven_types.go

Fix #200: Add support for mirrorOf attribute

---

e2e/common/uninstall_test.go

Disable OLM in uninstall tests

---

go.mod
go.sum
pkg/trait/service_binding.go
pkg/trait/trait_types.go

#2077 thanks !
```release-note
NONE
```

Upgrade sbo

---

e2e/builder/global_test.go
e2e/support/test_support.go
go.mod
go.sum
pkg/cmd/operator/operator.go
pkg/install/operator.go
pkg/platform/operator.go

```release-note
chore: Rely on Lease from controller-runtime for leader election
```

chore: Rely on Lease from controller-runtime for leader election

---

e2e/common/metrics_test.go
e2e/common/operator_metrics_test.go
e2e/support/test_support.go
e2e/support/util/log_counter.go
e2e/support/util/log_walker.go
e2e/support/util/structured_log.go
go.mod
go.sum
pkg/apis/camel/v1/integration_types_support.go
pkg/controller/build/schedule_routine.go
pkg/controller/integration/monitor.go

test: Add metrics e2e tests

---

docs/modules/ROOT/pages/installation/installation.adoc
docs/modules/ROOT/pages/installation/k3s.adoc
docs/modules/ROOT/pages/installation/registry/k3s.adoc

Added documentation about installing Camel K on K3s
```release-note
NONE
```

doc: added documentation about deploying Camel K on k3s

---

docs/modules/ROOT/nav-end.adoc
docs/modules/ROOT/pages/contributing/e2e.adoc

Adding some instructions on how to execute E2E integration test locally.
```release-note
NONE
```

doc(test): basic e2e local instructions

---

.github/workflows/automatic-changelog-update.yml
.github/workflows/backport.yml
.github/workflows/build.yml
.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/local.yml
.github/workflows/openshift.yml
.github/workflows/release.yml
.github/workflows/stale.yaml
.github/workflows/validate.yml

fix(ci): Free more disk space and pin OS version

---

examples/knative/README.md

Fix link in example knative readme

---

go.mod
go.sum

Thanks !
```release-note
NONE
```

chore: upgrade Service Binding Operator to v0.6.0

---

pkg/cmd/run.go

Fixes #1584.
```release-note
chore(cli): Improve run command --dependency option description
```

chore(cli): Improve run command --dependency option description

---

.github/workflows/knative.yml

chore(ci): upgrade YAKS version

---

pkg/cmd/local_build.go
pkg/cmd/local_run.go
pkg/cmd/util_dependencies.go

chore(cli): Fix error handling in local commands

---

e2e/common/build/maven_ca_secret_test.go

chore(e2e): Rely on staging repository in Maven CA e2e tests

---

script/cross_compile.sh

chore(release): disable dynamic linking in released artifacts

---

.github/workflows/automatic-changelog-update.yml
README.adoc
docs/charts/index.yaml
docs/modules/ROOT/pages/architecture/cr/build.adoc
docs/modules/ROOT/pages/architecture/cr/camel-catalog.adoc
docs/modules/ROOT/pages/architecture/cr/integration-kit.adoc
docs/modules/ROOT/pages/architecture/cr/integration-platform.adoc
docs/modules/ROOT/pages/architecture/cr/integration.adoc
docs/modules/ROOT/pages/architecture/operator.adoc
docs/modules/ROOT/pages/contributing/developers.adoc
docs/modules/ROOT/pages/running/run-from-github.adoc
docs/modules/ROOT/pages/tutorials/tekton/tekton.adoc
e2e/common/cli/run_test.go
e2e/common/scale_test.go
script/Makefile

chore: change references to use "main"

---

.github/workflows/upgrade.yml

fix(ci): Use Docker to build OLM index image

---

pkg/platform/defaults.go

```release-note
fix(build): Default to routine build strategy for local IntegrationPlatform
```

fix(build): Default to routine build strategy for local IntegrationPlatform

---

pkg/platform/defaults.go

```release-note
fix(build): Default to routine build strategy for local IntegrationPlatform
```

fix(build): Default to routine build strategy for local IntegrationPlatform (1.4.x back port)

---

config/manifests/bases/camel-k.clusterserviceversion.yaml
script/set_version.sh

fix(olm): Update CSV base template

---

docs/modules/ROOT/pages/configuration/configmap-secret.adoc

Remove a reference to the old logging configuration page

---

.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/openshift.yml
.github/workflows/upgrade.yml

Solves ticket #2263
```release-note
NONE
```

Consolidate make targets used in Github actions

---

.github/workflows/builder.yml
.github/workflows/kubernetes.yml
.github/workflows/local.yml
.github/workflows/openshift.yml
.github/workflows/upgrade.yml
.github/workflows/validate.yml

Use different job id names to avoid confusion when using GH CLI

---

pkg/util/source/inspector_yaml.go
pkg/util/source/inspector_yaml_test.go

* Steps field was only parsed when part of the "from", not when under "route"
* Unit test to validate both from and route steps property
Fix #2098 
```release-note
fix(source): yaml route steps
```

fix(source): yaml route steps

---

README.adoc

- Fixes OpenShift badge
- Updates badges links to point to the corresponding GitHub Actions workflows
```release-note
NONE
```

chore: Update README badges

---

.asf.yaml

Update the project link to point directly to the Camel K home page.
```release-note
NONE
```

chore: Update .asf.yaml file with project page link

---

e2e/common/operator_metrics_test.go
e2e/support/test_support.go
e2e/support/util/structured_log.go
pkg/builder/builder.go

chore: Make phase structured logging key a string

---

docs/modules/ROOT/nav.adoc

Added K3s to the registry section of navbar

---

.github/workflows/build.yml
.github/workflows/builder.yml
.github/workflows/knative.yml
.github/workflows/kubernetes.yml
.github/workflows/local.yml
.github/workflows/openshift.yml
.github/workflows/upgrade.yml
.github/workflows/validate.yml

chore(ci): Use `github.ref` instead of `github.head_ref` as concurrency group key

---

e2e/yaks/common/kamelet-binding-broker/yaks-config.yaml
e2e/yaks/common/kamelet-binding-http/yaks-config.yaml

[TEST] Increase timeouts for slow infra

---

pkg/trait/route.go
pkg/trait/route_test.go

Fixes https://github.com/apache/camel-k/issues/2313
```release-note
NONE
```

Fix Route Trait Crash

---

docs/modules/ROOT/pages/contributing/developers.adoc

In the developers document, it mentions to fork the project.  This adds a link to the github repository that they should fork.
```release-note
NONE
```

Add link to the github repo

---

.github/workflows/kubernetes.yml
e2e/service-binding/ServiceBinding.java
e2e/service-binding/service_binding_test.go
script/Makefile

Fixes #2236, thanks !
```release-note
NONE
```

Fix #2236: Add Service Binding E2E test

---

README.adoc

Seems like the sample code got moved into a sub directory.
This updates the README file to point to the right place.
```release-note
NONE
```

Update README to reflect where Sample.java is

---

pkg/trait/dependencies_test.go

Fix tests for aligning with camel-k-runtime

---

.github/workflows/knative.yml

chore(ci): kourier versions not necessarily bound to knative-serving

---

docs/modules/ROOT/pages/observability/integration-logging.adoc

Fixes website build

---

docs/modules/ROOT/pages/scaling/integration.adoc

Fixes #2380.
```release-note
chore(doc): Add autoscaling with Knative documentation
```

chore(doc): Add autoscaling with Knative documentation

---

config/crd/bases/camel.apache.org_kamelets.yaml
deploy/olm-catalog/camel-k-dev/1.5.0-snapshot/camel.apache.org_kamelets.yaml
e2e/knative/knative_platform_test.go
e2e/yaks/common/kamelet-beans/beans-source.kamelet.yaml
e2e/yaks/common/kamelet-beans/kamelet.feature
e2e/yaks/common/kamelet-beans/yaks-config.yaml
helm/camel-k/crds/crd-kamelet.yaml
pkg/apis/camel/v1/common_types.go
pkg/apis/camel/v1alpha1/kamelet_types.go
pkg/apis/camel/v1alpha1/kamelet_types_support.go
pkg/cmd/run.go
pkg/kamelet/initialize.go
pkg/trait/init.go
pkg/trait/kamelets.go
pkg/trait/kamelets_test.go
pkg/util/digest/digest.go
pkg/util/dsl/flow.go
pkg/util/dsl/flow_test.go
pkg/util/dsl/template.go
pkg/util/dsl/template_test.go

Fix #2271: add support for beans in kamelets (camel-main)

---

pkg/builder/s2i.go

Completes #2269.
```release-note
chore(build): Cancel s2i Build on context cancellation or timeout
```

chore(build): Cancel s2i Build on context cancellation or timeout

---

pkg/trait/pull_secret.go

Fix #2394
```release-note
NONE
```

fix(trait): ImagePullSecrets are not configured when the Integration is running

---

e2e/common/traits/pull_secret_test.go

fix(e2e): Remove image pull secret e2e test race conditions

---

docs/modules/ROOT/pages/troubleshooting/debugging.adoc

it is a more recent version which has important improvements
```release-note
NONE
```

Update link to video to debug in VS Code

---

e2e/common/cli/run_test.go
e2e/support/test_support.go

Follows up #2410.
```release-note
NONE
```

chore(e2e): Check Deployment progressing condition after re-run

---

pkg/trait/knative.go

Use bool pointer util functions instead of bare bool pointer manipulations to make it clear the intentions of code.
```release-note
NONE
```

refactor(trait): use bool pointer util functions in knative trait

---

docs/modules/ROOT/pages/contributing/developers.adoc

Precise requirements on Minikube instance for development

---

docs/modules/ROOT/pages/tutorials/tutorials.adoc

Closes #2347
```release-note
NONE
```

fix(doc): examples link

---

README.adoc

With this PR we're just presenting the main features of the project in the github landing page, remanding to the official documentation. Plus, I've add a bit of colors with some emoj :rainbow: 
Closes #1502
```release-note
NONE
```

doc: readme cleanup

---

docs/modules/ROOT/pages/configuration/runtime-config.adoc
e2e/common/config/config_test.go
e2e/common/config/files/config-configmap-properties-route.groovy
examples/user-config/config-secret-property-route.groovy

* Documentation
* Example
* E2E test
Closes #1838
```release-note
NONE
```

fix(cmd/run): secret/configmap as property file

---

docs/antora.yml

Publish camel-k 1.4 documentation to website

---

docs/modules/ROOT/pages/kamelets/kameletbindings-error-handler.adoc

Fixed camel website links in 1.4.x docs from absolute to relative

---

build/maven/pom-catalog.xml

This reverts commit 5f1f807f209868ac6c3a1c158aa50fba54020728.
```release-note
NONE
```

Revert "Temporarily disable qute due to Camel Quarkus issue #2701"

---

docs/modules/ROOT/pages/observability/monitoring/integration.adoc
docs/modules/traits/pages/quarkus.adoc

Align to Quarkus documentation

---

docs/modules/ROOT/pages/observability/integration.adoc
docs/modules/traits/pages/quarkus.adoc

Docs quarkus 1.4

---

pkg/apis/camel/v1/knative/types.go
pkg/trait/knative.go

Leftovers from #2430.
```release-note
NONE
```

chore: Remove Camel Sources support from Knative trait

---

pkg/trait/cron.go

As described in
- https://github.com/apache/camel-k/issues/2439
- https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Cron.20and.20duration.20max.20messages
```release-note
NONE
```

fix cron trait issue

---

docs/modules/ROOT/pages/architecture/operator.adoc
docs/modules/ROOT/pages/architecture/runtime.adoc
docs/modules/ROOT/pages/architecture/traits.adoc
docs/modules/traits/pages/traits.adoc

Ref #2273
```release-note
NONE
```

doc(architecture): trait section

---

.github/workflows/kubernetes.yml
go.mod
go.sum

Thanks !
```release-note
NONE
```

chore(sbo-trait): Upgrade Service Binding Operator to v0.8.0

---

examples/amqp/AmqpConnectionBeanConsumer.java
examples/amqp/AmqpConnectionBeanProducer.java
examples/amqp/README.md
examples/amqp/amqp.properties
examples/amqp/artemis/README.md
examples/amqp/artemis/artemis-amqp.yaml
examples/amqp/artemis/artemis-service.yaml
examples/databases/postgres-deploy/README.md

Showing how to leverage camel quarkus amqp connection bean declaration mechanics
```release-note
NONE
```

chore(examples): AMQP connection bean

---

pkg/trait/pull_secret_test.go

chore(trait): pull-secret unit test

---

examples/languages/hello.xml

Use https instead of http for xsd location

---

e2e/common/files/TimerKameletIntegration.java
e2e/common/files/timer-source.kamelet.yaml
e2e/common/kamelet_test.go

[test] Remove 3rd party dependencies

---

script/cross_compile.sh

chore: add support for darwin/atm64

---

pkg/controller/build/monitor_routine.go

```release-note
fix(builder): Fix race-condition when Build transitions to running phase
```

fix(builder): Fix race-condition when Build transitions to running phase

---

config/manifests/bases/camel-k.clusterserviceversion.yaml

fix(e2e): Update base CSV for 1.5.x release branch

---

pkg/controller/build/monitor_pod.go

fix(controller): panic on nil annotation

---

pkg/controller/build/monitor_pod.go

[backport] fix(controller): panic on nil annotation

---

pkg/apis/camel/v1/integration_types_support.go
pkg/apis/camel/v1/integration_types_support_test.go

Closes #2525
```release-note
NONE
```

fix(api): property leading space

---

docs/modules/ROOT/pages/kamelets/kamelets-user.adoc
examples/kamelets/kameletbindings/README.md
examples/kamelets/kameletbindings/kb-env-vars.yaml
examples/kamelets/kameletbindings/kb-trait-annotation.yaml

Closes #2500
```release-note
NONE
```

doc(kamelets): trait annotation usage and examples

---

docs/modules/ROOT/pages/contributing/developers.adoc

Closes #2502
```release-note
NONE
```

doc: contribute links

---

docs/modules/ROOT/pages/configuration/build-time-properties.adoc
docs/modules/ROOT/pages/configuration/runtime-properties.adoc
e2e/common/config/config_test.go
pkg/cmd/run.go
pkg/cmd/run_help.go
pkg/cmd/run_help_test.go
pkg/cmd/run_test.go

Introduced a merge function which is in charge to merge all properties, giving priority to single declaration property options
Closes #2538
```release-note
fix(cli): property priority
```

fix(cli): property priority

---

docs/modules/ROOT/pages/configuration/dependencies.adoc

Closes #2085
```release-note
NONE
```

doc(dependencies): note on dynamic URIs

---

.github/workflows/knative.yml

fix(ci): Fix YAKS binary download

---

config/manifests/bases/camel-k.clusterserviceversion.yaml

Fixes the OLM upgrade e2e tests.
```release-note
NONE
```

chore(release): Update OLM base CSV manifest

---

docs/modules/ROOT/pages/observability/monitoring/operator.adoc

doc(native): Add package type tag to build metrics

---

docs/modules/ROOT/pages/architecture/runtime.adoc

Description of the runtime to replace the TBD
Closes #2273
```release-note
NONE
```

doc: architecture > runtime section

---

docs/modules/ROOT/pages/architecture/runtime.adoc

Fixed website build

---

pkg/apis/camel/v1/integration_types_support.go
pkg/trait/container.go

Fix #2638
```release-note
Integrations and Bindings with external images can be scaled correctly
```

Fix #2638: sync owned integration kit to avoid gc

---

e2e/builder/global_test.go

[TEST] Global test - support for openshift

---

pkg/controller/kamelet/kamelet_controller.go

As the number of Kamelets grows, so does the reconciliation requests that queue during the operator start. That PR enables Kamelets to be reconciled in parallel.
```release-note
chore: Parallel Kamelets reconciliation
```

chore: Parallel Kamelets reconciliation

---

.github/workflows/builder.yml
e2e/builder/build_test.go

fix(ci): Disable default Kamelets installation for builder e2e tests

---

pkg/controller/integration/build_kit.go

Users can edit the Integration while its Kit is building.
```release-note
fix: Handle Integration changes while waiting for Kit build
```

fix: Handle Integration changes while waiting for Kit build

---

docs/modules/ROOT/pages/contributing/developers.adoc

doc(dev): update required Go version to 1.16

---

go.mod
go.sum
pkg/trait/service_binding.go

Thanks !
```release-note
Upgraded Service Binding Operator to 1.0.0 GA
```

chore(sbo): upgrade Servce Binding Operator to 1.0.0 GA

---

e2e/common/integration_fail_test.go
e2e/common/kamelet_binding_test.go
pkg/controller/kameletbinding/common.go

Fix #2724
```release-note
NONE
```

Fix #2724: assign an ID to the binding main route

---

script/Makefile

chore(release): Remove staging repository

---

build/Dockerfile

```release-note
chore(build): Upgrade Maven to version 3.8.4
```

chore(build): Upgrade Maven to version 3.8.4

---

docs/modules/ROOT/pages/installation/scheduling.adoc

@astefanutti I've took the liberty to copy paste your comment from the referred issue
Closes #2768
```release-note
doc(install): suggested resource configuration
```

doc(install): suggested resource configuration

---

e2e/common/scale_integration_test.go
pkg/trait/container.go

Fix #2638
```release-note
NONE
```

Fix #2638: fix condition for external kit and add test

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/installation/installation.adoc
docs/modules/ROOT/pages/installation/registry/gcr.adoc
docs/modules/ROOT/pages/installation/registry/registry.adoc

Will fix a website build error as reported in https://github.com/apache/camel-k/pull/2778#issuecomment-978853119
```release-note
NONE
```

fix(doc): broken links

---

docs/modules/ROOT/pages/running/running.adoc
pkg/util/jitpack/jitpack.go

doc: no CLI integration run

---

docs/modules/ROOT/pages/installation/advanced/multi.adoc

Reported in https://github.com/apache/camel-website/pull/688
```release-note
NONE
```

fix(doc): header complain

---

cmd/util/license-check/main.go
pkg/builder/s2i.go
pkg/builder/spectrum.go
pkg/cmd/dump.go
pkg/cmd/init.go
pkg/cmd/modeline_test.go
pkg/cmd/root_test.go
pkg/cmd/trait_help.go
pkg/cmd/util_containerization.go
pkg/cmd/util_dependencies.go
pkg/controller/integrationplatform/create.go
pkg/controller/integrationplatform/create_test.go
pkg/install/cluster.go
pkg/install/common.go
pkg/install/operator.go
pkg/resources/resources_support.go
pkg/resources/resources_test.go
pkg/trait/openapi.go
pkg/util/camel/catalog.go
pkg/util/gzip/compress.go
pkg/util/sync/file_test.go
pkg/util/util.go

fix(lint): error return value are not checked

---

docs/modules/traits/pages/container.adoc
docs/modules/traits/pages/gc.adoc
docs/modules/traits/pages/quarkus.adoc
pkg/trait/container.go
resources/traits.yaml

Fixes #2761 
```release-note
NONE
```

Fix doc port name

---

script/gen_crd/gen_crd_api.sh

Makefile: for the generate-doc target don't use show-progress for wget

---

config/manifests/patch-delete-user-cluster-role.yaml

```release-note
fix(OLM): Remove aggregated cluster roles from OLM bundle
```

fix(OLM): Remove aggregated cluster roles from OLM bundle

---

docs/modules/ROOT/pages/kamelets/kamelets-user.adoc

Closes #2765
```release-note
doc(kamelets): custom repository
```

doc(kamelets): custom repository

---

docs/modules/ROOT/pages/configuration/dependencies.adoc

Closes #1789
```release-note
doc(jitpack): detailed info and link to example
```

doc(jitpack): detailed info and link to example

---

docs/antora.yml
docs/modules/ROOT/pages/index.adoc

See apache/camel-website#701
This must be merged at the same time as the corresponding camel-k-runtime PR

camel-website #701: RI info (1.7.x)

---

docs/antora.yml
docs/modules/ROOT/pages/index.adoc

See apache/camel-website#701
This must be merged at the same time as the corresponding camel-k-runtime PR

camel-website #701: RI info (1.6.x)

---

docs/antora.yml
docs/modules/ROOT/pages/index.adoc

See apache/camel-website#701
This must be merged at the same time as the corresponding camel-k-runtime PR

camel-website #701: RI info (1.4.x)

---

cmd/util/doc-gen/generators/traitmetadatagen.go
docs/modules/ROOT/partials/apis/crds-html.adoc
resources/traits.yaml

```release-note
fix: filter lint comment in traits
```

fix: filter lint comment in traits

---

docs/modules/ROOT/pages/installation/platform/iks.adoc
docs/modules/ROOT/pages/installation/registry/icr.adoc

doc: add more details about installation on IKS/ICR

---

docs/charts/index.yaml

Updated the helm index.yml file, by only adding the latest helm chart

---

release.adoc

Release Documentation: It's release-helm and not generate-helm command

---

e2e/common/traits/health_test.go

Fixes the health e2e tests.
```release-note
fix(e2e): Update health tests based on Camel 3.14 new health check responses
```

fix(e2e): Update health tests based on Camel 3.14 new health check responses

---

docs/antora.yml
docs/modules/ROOT/examples/js/ck.js
docs/modules/ROOT/pages/index.adoc

See https://github.com/apache/camel-website/issues/701

camel-website #701 camel-k RI table setup (main)

---

docs/antora.yml
docs/modules/ROOT/examples/js/ck.js
docs/modules/ROOT/pages/index.adoc

camel-website #701 camel-k RI table setup (1.7.x)

---

docs/antora.yml
docs/modules/ROOT/examples/js/ck.js
docs/modules/ROOT/pages/index.adoc

camel-website #701 camel-k RI table setup (1.4.x)

---

docs/source-map.yml
docs/source-watch.yml

fix(doc): Update source map and watch for 1.8.x

---

config/manifests/bases/camel-k.clusterserviceversion.yaml

chore(release): Update 1.8.x OLM base CSV manifest

---

.github/workflows/upgrade.yml

```release-note
fix(e2e): Do not add snapshot bundle to stable channel
```

fix(e2e): Do not add snapshot bundle to stable channel

---

e2e/upgrade/olm_upgrade_test.go
e2e/upgrade/util.go

This improves the stability of the OLM upgrade e2e tests, where the update of the Subscription for cross-channel upgrade could fail because of conflicts with concurrent updates performed by OLM.
```release-note
fix(e2e): Patch OLM Subscription to avoid conflicting updates
```

fix(e2e): Patch OLM Subscription to avoid conflicting updates

---

e2e/common/cli/global_kamelet_test.go

backport of https://github.com/apache/camel-k/pull/2679

[TEST] Global kamelet test - support for openshift

---

build/maven/pom-runtime.xml

Ref #apache/camel-k-runtime/issues/766
```release-note
chore(deps): remove kamelet-reify
```

chore(deps): remove kamelet-reify

---

e2e/builder/global_test.go
e2e/common/cli/global_kamelet_test.go
e2e/support/test_support.go

[TEST] Add Global operator + namespaced kamelet test

---

pkg/controller/kamelet/initialize.go
pkg/controller/kamelet/monitor.go

Closes #2988
```release-note
fix(kamelet): reconcile when errored
```

fix(kamelet): reconcile when errored

---

docs/modules/ROOT/pages/configuration/runtime-resources.adoc
e2e/common/config/config_test.go
e2e/common/config/files/resource-configmap-key-location-route.groovy
examples/user-config/resource-configmap-key-location-route.groovy
pkg/trait/mount.go
pkg/util/resource/config.go

Closes #2943
```release-note
fix(cmd/run): allow multiple resources
```

fix(cmd/run): allow multiple resources

---

pkg/cmd/local.go
pkg/cmd/local_build.go
pkg/cmd/local_run_test.go
pkg/cmd/root.go

chore(cmd): refactor kamel local commands

---

e2e/common/cli/install_test.go
e2e/support/test_support.go
e2e/support/test_util.go

[TEST] Add CliDownloadTest

---

e2e/common/build/maven_http_proxy_test.go

Enhance Http proxy test about the OLM

---

config/manifests/bases/camel-k.clusterserviceversion.yaml

fix(olm): Upgrade container image in base CSV manifest

---

config/manifests/bases/camel-k.clusterserviceversion.yaml
pkg/util/defaults/defaults.go
script/Makefile

chore(ci): 1.8.1 release post actions

---

docs/antora.yml

Update compatibility matrix reflectin main changes

---

docs/antora.yml

Docs: Fixed the camel-k-runtime in the compatibility matrix

---

release.adoc
script/prepare-operators.sh

```release-note
Fixes #3085 
```

Post release steps: Operators manifests

---

pkg/cmd/local_run.go
pkg/cmd/util_containerization.go

Fix #3029
```release-note
NONE
```

fix(cli): make sure kamel local run clean up dirs at ctrl+c

---

.github/workflows/release.yml

Fix the errors happening on the release action flow
```release-note
fix(ci): nightly build
```

fix(ci): nightly build

---

.github/workflows/nightly-tag.yaml
.github/workflows/release.yml

Closes #393 
```release-note
fix(ci): creating nightly tag
```

fix(ci): creating nightly tag

---

e2e/common/languages/files/xml.xml
examples/polyglot/routes.xml
pkg/util/modeline/parser_test.go
resources/templates/xml.tmpl

Issue: https://github.com/apache/camel-k/issues/3093

[#3093] wrong XSD url generated with XML initialiser

---

e2e/common/traits/route_test.go

Increase test timeout and make it configurable for slow CI.
```release-note
NONE
```

Stabilize route test

---

config/manager/operator-deployment.yaml
script/set_version.sh

Closes #3137 
```release-note
NONE
```

add k8s labels to deployment service

---

.github/workflows/release.yml

Closes #3130 
```release-note
chore(ci): nightly allow release update
```

chore(ci): nightly allow release update

---

pkg/util/defaults/defaults.go

chore(ci): defaults regen

---

docs/modules/ROOT/pages/cli/cli.adoc
docs/modules/ROOT/pages/configuration/dependencies.adoc

Ref apache/camel-website#819
```release-note
NONE
```

chore(doc): removing useless fragment

---

examples/traits/prometheus/MyIntegration.java
examples/traits/prometheus/README.md

Solves issue #3144 
cc @squakez 
I'm new to Apache camel-k and have taken it up as a prerequisite for understanding the integration and usage necessary for the Outreachy project "Camel-k API and examples". Please let me know if there are any other adjustments I can make; I assure I'm a quick learner.

Example to show usage of prometheus trait

---

examples/README.md
examples/olm/README.md

```release-note
chore(examples): olm installation
```

chore(examples): olm installation

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/cli/file-based-config.adoc

This fixes issue #1155 
```release-note
NONE
```

added a file-config doc

---

.github/actions/e2e-builder/exec-tests.sh
.github/actions/e2e-knative/exec-tests.sh
.github/actions/e2e-kubernetes/exec-tests.sh
.github/actions/e2e-upgrade/exec-tests.sh
.github/actions/kamel-build-bundle/action.yaml
.github/actions/kamel-build-bundle/build-index-image.sh
.github/actions/kamel-cleanup/cleanup.sh
.github/actions/kamel-cleanup/reset-proxy.sh
.github/actions/kamel-config-cluster/action.yaml
.github/actions/kamel-preflight-test/action.yml
.github/actions/kamel-preflight-test/preflight-test.sh
.github/actions/kamel-report-problematic/report-problematic.sh
.gitignore
e2e/common/build/maven_http_proxy_test.go
e2e/common/traits/openapi_test.go
e2e/upgrade/cli_upgrade_test.go
e2e/upgrade/olm_upgrade_test.go
pkg/apis/camel/v1/integration_types_support.go
pkg/controller/integration/build_kit.go
pkg/install/kamelets.go
pkg/trait/trait.go
pkg/util/command.go
script/Makefile
script/build_install_opm.sh

Migrates opm to file based indexes and fixes e2e upgrade tests
