apache/camel-k

docs/modules/ROOT/pages/observability/logging/operator.adoc
pkg/cmd/bind.go
pkg/cmd/operator/operator.go
pkg/install/optional.go
pkg/util/log/log.go

- Use zap log level enabler implementation to set global log level
- Use Camel K logger wrapper in operator
- Use Debug wrapper methods
- Add some documentation of LOG_LEVEL envvar and its setting via kamel CLI

fix(#3399): Improve operator log level adjustments

---

pkg/install/knative.go
pkg/install/optional.go

Use proper operator namespace in the service account role binding subject for global operators. Was using empty global operator watch namespace before which caused errors in the cluster role binding.
(cherry picked from commit 2ffdcfab6f8fa4ee90f9581b26ebf7cbe48aa685)
```release-note
Fix(Knative): Cluster role binding for Knative addressable resolver. Bring back permissions for messaging.knative.dev resources (e.g. channel)
```

[Backport 1.9.x] fix(#3390): Fix Knative addressable resolver cluster role binding

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
script/gen_crd/gen_crd_api.sh

This uses the fixed version of gen-crd-api-reference-docs that supports new Traits API defined under `camel/v1/trait`. Before the fix, the tool didn't accept sub directories under the API packages.
```release-note
NONE
```

fix(doc): fix gen-crd-api-reference-docs and regen API doc with Traits

---

.github/actions/kamel-config-cluster-ocp3/action.yml
.github/workflows/openshift.yml
e2e/namespace/install/kustomize/common.go
e2e/namespace/install/kustomize/operator_test.go
e2e/namespace/install/kustomize/setup_test.go
install/Makefile
install/script/check_crd_api_support.sh
script/check_crd_api_support.sh

* OCP3 has obsolete CRD API, which is handled in the golang binary but
not in the kustomize install
* Adds plumbing to the kustomize install to error out gracefully if the
CRD API is the obsolete version
* Adds env var to e2e tests to skip tests if cluster target is OCP3
* Modifies openshift github workflow to move the test-quarkus-native
to executing as cluster-admin
```release-note
NONE
```

Handle OCP3 in e2e kustomize install tests

---

e2e/namespace/install/cli/debug_test.go

[TEST] Add `kamel debug` test
```release-note
NONE
```

[TEST] Add kamel debug test

---

config/crd/bases/camel.apache.org_integrations.yaml
config/crd/bases/camel.apache.org_kameletbindings.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
pkg/apis/camel/v1/integration_types.go

```release-note
chore(api): refer to correct trait
```

chore(api): refer to correct trait

---

docs/modules/ROOT/pages/configuration/dependencies.adoc
docs/modules/ROOT/pages/configuration/runtime-resources.adoc
docs/modules/ROOT/pages/contributing/developers.adoc
e2e/global/common/build/incremental_build_test.go
e2e/global/common/config/config_test.go
examples/pulsar/pulsar.groovy
examples/saga/README.md
examples/traits/tracing/InventoryService.java
examples/traits/tracing/OrderService.java
examples/traits/tracing/README.md
examples/user-config/resource-file-binary-route.groovy
pkg/cmd/run.go

Fix #3291
```release-note
NONE
```

fix(doc): standardise Camel dependency notation in docs and examples

---

script/Makefile

Building multi-arch containers is broken on MacOS on ARM due to
incorrect check for the machine hardware name
```release-note
NONE
```

Fix building multi-arch containers on ARM on MacOS

---

helm/camel-k/README.md
helm/camel-k/templates/operator.yaml
helm/camel-k/values.yaml

one of the best practices for operating workloads in Kubernetes is to set resource requests and limits as well as securityContext related settings. 
This PR introduces the possibility to set those resource requests and limits as well as securityContext related settings. Since the exact settings cant be known and depend on the environment as well as the number and complexity of camel routes, users will be able to freely define their settings in the `values.yaml`.
```release-note
NONE
```

allow setting resources & securityContext in Helm Chart values

---

docs/modules/ROOT/pages/running/dev-mode.adoc

Since 1.3.x the file Sample.java has been moved, the doc should be changed consequently.
* Use the directory `examples/languages/` instead of simply `examples/`

Update the path of the file Sample.java

---

docs/modules/ROOT/pages/configuration/runtime-resources.adoc

* Fix unexpected accents
* Remove the dev mode flag from the command as it is not required and brings some noice
* Reformulate unclear sentences

Some improvements in runtime-resources.adoc

---

e2e/knative/kamelet_test.go
e2e/service-binding/service_binding_kamelet_test.go

[TEST] Replace existing kamelets

---

e2e/global/common/kamelet_binding_with_image_test.go
e2e/support/test_support.go
pkg/controller/integration/integration_controller.go
pkg/controller/integration/kits.go
pkg/controller/integration/kits_test.go
pkg/controller/kameletbinding/kamelet_binding_controller.go
pkg/controller/kameletbinding/monitor.go
pkg/trait/util.go
pkg/trait/util_test.go
pkg/util/digest/digest.go
pkg/util/kubernetes/util.go

```release-note
NONE
```
Fixes #3479

fix: camel-k ignores changes to traits configured using annotations 

---

e2e/global/common/integration_fail_test.go
e2e/global/common/kamelet_binding_test.go
pkg/trait/camel.go

Removed duplicated properties file created by the trait and merged into a single one.
Closes #3458
```release-note
fix(trait): camel to use a single properties file
```

fix(trait): camel to use a single properties file 

---

docs/modules/ROOT/pages/configuration/dependencies.adoc

* Adds the missing word
* Indicates the complete name of the dependency flag
* Removes the sentence about the example of jitpack as it doesn't exist anymore
* Reformulates unclear sentences

Some various improvements in dependencies.adoc

---

config/crd/bases/camel.apache.org_integrationplatforms.yaml
config/crd/bases/camel.apache.org_integrations.yaml
config/crd/bases/camel.apache.org_kameletbindings.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/knative-service.adoc
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
pkg/apis/camel/v1/trait/knative_service.go
pkg/trait/knative_service.go
pkg/trait/knative_service_test.go
resources/traits.yaml

I'd like take up this issue.(#1712) 
I also need this feature.
I'm not familiar with the manners, so please let me know if I am wrong.
**Modifications**
* Add visibilitys option
https://knative.dev/docs/serving/services/private-services/
```release-note
Feat(trait): Knative service visibility support
```

Feat(trait): Knative service visibility support

---

config/rbac/operator-role.yaml

When camel-k-operator is installed in global mode, [pkg/install/knative.go](https://github.com/apache/camel-k/blob/2ffdcfab6f8fa4ee90f9581b26ebf7cbe48aa685/pkg/install/knative.go#L82) wants to patch a `ClusterRoleBinding`, but it fails with 
```
Cannot bind the Knative addressable resolver aggregated ClusterRole: skipping
Error while binding the Knative Addressable resolver aggregated ClusterRole",
"error":"clusterrolebindings.rbac.authorization.k8s.io \"camel-k-operator-addressable-resolver\" is forbidden: User \"system:serviceaccount:cmiranda-ops:camel-k-operator\" cannot patch resource \"clusterrolebindings\" in API group \"rbac.authorization.k8s.io\" at the cluster scope"}
```
There is a missing permission to patch it.
```
$ k auth can-i -A patch …
```

fix(rbac): missing clusterrolebinding permission

---

pkg/trait/knative.go
pkg/trait/knative_service.go

Setting the sinkbing label when the knative service is
created seems the right place, instead to update the label
seems to trigger a new knative configuration
https://github.com/apache/camel-k/issues/3522
-->
```release-note
Fix knative service triggering new pods until node exhaustion
```

fix(knative): Fix the knative pods created until exhaustion

---

helm/camel-k/README.md
helm/camel-k/templates/operator-cluster-role-bindings.yaml
helm/camel-k/templates/operator-cluster-roles.yaml
helm/camel-k/templates/operator-role-binding.yaml
helm/camel-k/templates/operator.yaml
helm/camel-k/values.yaml

This PR introduces the ability to configure global installation of Camel K Operator via Helm Chart as mentioned in #3054

Add operator global option when installing with Helm Chart

---

helm/camel-k/README.md
helm/camel-k/templates/operator.yaml
helm/camel-k/values.yaml

This PR adds the option to configure tolerations on the operator's deployment manifest, so that the pod can be configured to be scheduled onto appropriate nodes with specific taints.

chore: add pod tolerations options to operator

---

.github/workflows/validate.yml
pkg/cmd/run.go
pkg/cmd/source/source.go

It just refactors `(o *runCmdOptions) createOrUpdateIntegration` method by splitting the long method into small submethods so that `nolint: maintidx` can be removed. It doesn't change any behaviours other than upgrading golangci-lint to 1.47.3.
```release-note
NONE
```

chore(cli): refactor run cmd to remove nolint maintidx

---

pkg/trait/trait_types.go
pkg/trait/trait_types_test.go

fixes #3543
When we try to run an integration that needs to mount a volume with filtering but without a path, it fails with `[spec.template.spec.volumes[2].secret.items[0].path: Required``
* Use the key when no mount path is proposed 
```release-note
fix(trait): force a volume path when key is set
```

fix(trait): force a volume path when key is set

---

.github/workflows/release.yml

- Run workflow only on Camel K repository
- Avoid to run workflow on forks because it will fail

chore(build): Restrict release workflow execution

---

pkg/util/kubernetes/replace.go

- Since we have migrated to Knative service v1 API remove obsolete beta v1 mappings when replacing resources
- In fact the code has been a duplication after the migration to service v1

chore(knative): Remove obsolete Knative service beta v1 mappings

---

e2e/global/knative/files/knative_broker_receiver.groovy
e2e/global/knative/files/knative_broker_sender.groovy
e2e/support/test_support.go
e2e/yaks/common/kamelet-binding-broker/kamelet.feature
e2e/yaks/common/kamelet-binding-broker/logger-sink-binding.yaml
e2e/yaks/common/kamelet-binding-broker/sample-broker.yaml
e2e/yaks/common/kamelet-binding-broker/timer-source-binding.yaml
e2e/yaks/common/kamelet-binding-broker/yaks-config.yaml
pkg/apis/camel/v1/knative/types.go
pkg/apis/camel/v1/knative/types_support.go
pkg/trait/knative.go
pkg/util/bindings/bindings_test.go
pkg/util/bindings/knative_ref.go

https://github.com/apache/camel-k/issues/2864
* Add e2e knative tests
* Change the kamelet-binding-broker yaks test to use a custom broker name
```release-note
Make knative broker name configurable
```
* WIP: This PR depends on a [camel-knative fix](https://github.com/apache/camel/pull/7818). This is for an early review.

fix(knative): Make knative broker name configurable

---

.github/actions/e2e-knative-yaks/action.yml
e2e/yaks/common/apache-kamelet-catalog/yaks-config.yaml
e2e/yaks/common/kamelet-beans/yaks-config.yaml
e2e/yaks/common/kamelet-binding-autoload/yaks-config.yaml
e2e/yaks/common/kamelet-binding-broker/yaks-config.yaml
e2e/yaks/common/kamelet-binding-http/yaks-config.yaml
e2e/yaks/common/kamelet-binding-property-encoding/yaks-config.yaml
e2e/yaks/common/kamelet-binding/yaks-config.yaml
e2e/yaks/common/kamelet-no-properties/yaks-config.yaml
e2e/yaks/common/kamelet-steps/yaks-config.yaml
e2e/yaks/common/kamelet/yaks-config.yaml
e2e/yaks/common/knative-broker/knative-broker.feature
e2e/yaks/common/knative-broker/yaks-config.yaml
e2e/yaks/common/knative-sinkbinding/yaks-config.yaml
e2e/yaks/openshift/monitoring/yaks-config.yaml

- Use global Camel K operator in YAKS E2E tests (avoid to install operator for each test)
- Optimize waiting time in knative broker tests
- Significantly reduces the YAKS E2e test job execution time (was ~90mins now is ~30mins)

chore(build): Use global operator in YAKS E2E tests

---

script/Makefile
script/maven_overlay.sh
script/package_maven_artifacts.sh

~It appears that the builder test is failing just because it's taking longer time to download dependencies from staging repo. Let's see if this simple fix can solve the failures.~
While it doesn't still fix the original builder e2e failures, it fixes `./script/package_maven_artifacts.sh` to make it aware of staging repo and it seems e2e results have become improved.
```release-note
NONE
```

fix(e2e): make package-artifacts to be aware of staging repo

---

pkg/cmd/delete.go
pkg/cmd/kamelet_delete.go
pkg/cmd/kit_delete.go
pkg/cmd/rebuild.go
pkg/cmd/rebuild_test.go
pkg/cmd/trait_help.go

fixes #3445
Allowing to accept no arguments to rebuild all the integrations is a bit risky so a new flag for this purpose must be explicitly provided by the end user.
* Add the flag `--all` to the rebuild command to rebuild all integrations
* Sanitize the name of the integration to align the code with the delete command
```release-note
The rebuild command no more supports empty arguments, either the flag `--all` must be set to rebuild all integrations, 
or the list of integration names to rebuild needs to be provided
```

feat(cli): Force arguments for the rebuild command

---

pkg/trait/trait_catalog.go

```release-note
fix: Panic with odd number of key / value arguments
```

fix: Panic with odd number of key / value arguments

---

.github/workflows/release-workflow.yml

Adding common e2e workflow as a first simple smoke test
Ref #3572
```release-note
feat(ci): smoke test before nightly release
```

feat(ci): smoke test before nightly release

---

release.adoc

```release-note
chore: add a post release bump chapter
```

chore: add a post release bump chapter

---

.github/workflows/release.yml

```release-note
chore(ci): support 1.10.x nightly release
```

chore(ci): support 1.10.x nightly release

---

e2e/namespace/upgrade/olm_install_test.go

[TEST] OLM fresh install test

---

e2e/upgrade/olm_upgrade_test.go
pkg/util/defaults/defaults_support.go

- stabilize upgrade test (Patch the Subscription to avoid conflicts with concurrent updates performed by OLM)
- test operator image installed by the OLM

Olm image test 1.8.x

---

e2e/namespace/install/cli/log_test.go
pkg/cmd/debug.go
pkg/cmd/log.go
pkg/cmd/run.go
pkg/util/kubernetes/log/annotation_scraper.go
pkg/util/kubernetes/log/pod_scraper.go
pkg/util/kubernetes/log/util.go

fixes #3004
When a pod has a lot of log entries, it can be convenient to be able to get only the last entries of the logs.
* Add an int flag `--tail` to get the specified amount of last lines of the logs. The default value is `-1` indicating that all lines of the logs are expected like the previous default behavior
```release-note
feat(cli): Add tail flag to the log command
```

feat(cli): Add tail flag to the log command

---

pkg/trait/platform.go

Complements #2696.
```release-note
feat: Auto-create platform when registry can be inferred from KEP-1755
```

feat: Auto-create platform when registry can be inferred from KEP-1755

---

.github/workflows/release-workflow.yml

Workaround to skip the execution of an action which is missing on release-1.9 branch.
Closes #3613 
```release-note
NONE
```

fix: do not run smoke tests on 1.9 nightly

---

.github/actions/e2e-common/action.yml

Creating an action needed by nightly release procedure to add some smoke test. Given that 1.9 diverges from `main` we're using a different strategy here, copying the build action and using this as smoke test.
Ref #3613
```release-note
fix(ci): nightly release workaround
```

fix(ci): nightly release workaround

---

e2e/global/common/files/TimerCustomKameletIntegration.java
e2e/global/common/files/kamelets/timer-custom-source.kamelet.yaml
e2e/global/common/kamelet_test.go
pkg/cmd/kamelet.go
pkg/cmd/kamelet_add_repo.go
pkg/cmd/kamelet_add_repo_test.go
pkg/cmd/kamelet_get.go
pkg/cmd/kit_get.go

fixes #2850
Up to now, the only way to define a Kamelet repository is to edit the integration platform to add it manually which is not really convenient. The idea of the improvement is to add a new command to be able to add Kamelet repositories.
* Add a new sub-command of `kamelet` called `add-repo`
* Align the code of some commands regarding how to run them with the rest of the commands (not directly related)
```release-note
feat(cli): Add add-repo command to add a repo for custom Kamelet catalog
```

feat(cli): Add add-repo command to add a repo for custom Kamelet catalog

---

e2e/global/common/kamelet_test.go

related to #3623
The e2e test for the add-repo command relies on an external GitHub repository which is not good for the sustainability of the test, it should rather use a folder in the camel-k repository
* Change the location of the custom repository for something in the camel-k repository
```release-note
NONE
```

test: Use camel-k repo in the test for the add-repo command

---

helm/camel-k/templates/operator.yaml

Fixed helm install failing due to lack of space.
```
$ helm install --generate-name camel-k/camel-k
Error: INSTALLATION FAILED: parse error at (camel-k/templates/operator.yaml:87): "-en"
```

Fixed helm install failing

---

docs/modules/ROOT/pages/configuration/build-time-properties.adoc
docs/modules/ROOT/pages/configuration/runtime-properties.adoc
e2e/global/common/config/config_test.go
pkg/cmd/run.go
pkg/cmd/run_help.go
pkg/cmd/run_help_test.go
pkg/cmd/run_test.go

fixes #3002
It would be nice to provide the possibility to use configmap and secret as runtime or build-time properties for the camel and builder traits.
* Add the support of `configmap:name-of-configmap` and `secret:name-of-secret` to the flags `property` and `build-property`
* Move the functions `extractProperties` and `mergePropertiesWithPrecedence` from `run_help.go` to `run.go` as we need to add a receiver
* Move the unit tests of the functions moved to the corresponding test file
* Add related E2E test
* Add related doc
```release-note
feat(cmd/run): secret/configmap as runtime/build-time properties
```

feat(cmd/run): secret/configmap as runtime/build-time properties

---

docs/modules/ROOT/pages/kamelets/kamelets-user.adoc

the type can now also be action, not only source and sink.
For instance, see https://github.com/apache/camel-kamelets/blob/b98e61105b8c782422028b0c2ea857a90c97a550/kamelets/avro-deserialize-action.kamelet.yaml#L29
```release-note
NONE
```

Update documentation for kamelet type that can also be action

---

e2e/namespace/install/cli/install_test.go
pkg/builder/buildah.go
pkg/builder/builder_support.go
pkg/builder/kaniko.go
pkg/cmd/install.go
pkg/cmd/install_test.go
pkg/platform/defaults.go

fixes #3308 
We don't have a direct way to fill the `platform.Spec.Build.PublishStrategyOptions`. It would be nice to include it in the `kamel install` as an option.
* Add a multi-valued flag called `build-publish-strategy-option` to the install command
* Remove the flags `kaniko-executor-image`, `kaniko-warmer-image` and `buildah-image`
* Deprecate the flag `kaniko-build-cache` in favor of `build-publish-strategy-option`
* Fix a suspicious call to the option `KanikoBuildCache` while `KanikoBuildCacheEnabled` was likely expected
* Add an E2E test to ensure that the options are properly set in the Integration Platform
```release-note
feat(cli): Allow to set build publish strategy options from install cmd #3631
```

feat(cli): Allow to set build publish strategy options from install cmd

---

e2e/namespace/install/cli/run_test.go
pkg/cmd/run.go
pkg/cmd/run_help.go
pkg/cmd/run_help_test.go

fixes #240
We allow `mvn:` dependencies with `camel:` and `runtime:` wrapper. We should allow users to specify HTTP dependencies on libs (to load custom JAR that are not present in Maven central).
* Downloads dependencies with `http` and `https` prefixes to a temporary folder
* Uploads the temporary file like local files
```release-note
feat(cli/run): Support dependencies defined using HTTP URLs
```

feat(cli/run): Support dependencies defined using HTTP URLs

---

.github/actions/release-nightly/action.yml
.github/workflows/release.yml

It looks like we need to pass the secrets from workflow to the action.
```release-note
NONE
```

fix: release action to use secrets properly

---

examples/openapi/README.md

`run` is failed because there is no `file:` prefix.
```
$ kamel run --dev --name greetings --open-api greetings-api.json greetings.groovy
Error: invalid openapi specification "greetings-api.json". It supports only file or configmap
```
To fix this, I added `file:`
```
$ kamel run --dev --name greetings --open-api file:greetings-api.json greetings.groovy
Integration "greetings" created
```

Fix README in examples/openapi

---

pkg/trait/ingress.go
pkg/trait/ingress_test.go

This changes the _ingress_ trait to configure service information into the configured rule instead of the default backend.
This enables platform specific ingress controllers, such as the OpenShift one, to translate ingress into their specific API, so the ingress is actually admitted, and it's possible for users to rely on the vanilla Kubernetes Ingress API.  
```release-note
trait(ingress): Configure backend in ingress rule
```

trait(ingress): Configure backend in ingress rule

---

.github/workflows/release.yml
docs/antora.yml
release.adoc

Some PR on `release-1.8.x` to follow up in order to update documentation on that branch.
```release-note
chore: enable latest LTS nightly
```

chore: enable latest LTS nightly

---

script/Makefile

Whenever troubleshooting e2e errors I always feel pain at reading the current CI output. What I've been doing is searching keywords multiple times to find where the tests failed.
Now I think that using `gotestfmt` might solve the issue, so I'm trying it here. Please check the outputs of e2e tests and let me know if you like it.
```release-note
NONE
```

chore(ci): experimental use of gotestfmt for e2e

---

pkg/controller/build/monitor_routine.go

This PR makes sure the reconciliation request context is passed to the build routine, so cancellation, as well as values, of the parent context, are taken into account while the build is performed.
```release-note
chore: Propagate reconcilation context to build routine
```

chore: Propagate reconcilation context to build routine

---

addons/register_aws_secrets.go
addons/vault/aws_secrets_manager.go
addons/vault/aws_secrets_manager_test.go
pkg/apis/camel/v1/common_types.go

This is a first addon for #3031

Added Support AWS Secrets Manager Vault from Camel

---

pkg/trait/quarkus.go
pkg/trait/quarkus_test.go

Propagate annotation trait configuration (`trait.camel.apache.org/*` annotations) from Integration to the IntegrationKit. This makes sure that the kit matches the integration once the native build is done.
Avoids Integration being stuck in BuildingKit phase as described in #3671 
Fixes #3671 
```release-note
Fix: Quarkus native mode for KameletBinding
```

fix(#3671): Fix native mode for KameletBinding

---

docs/modules/ROOT/pages/contributing/local-development.adoc
docs/modules/ROOT/pages/installation/advanced/multi.adoc
pkg/util/defaults/defaults_support.go

Manual backport of #3660 to 1.10.x 
The code base was using exclusively `KAMEL_OPERATOR_ID` as environment setting to identify the operator id. This caused problems after OLM based installation because `KAMEL_OPERATOR_ID` is not being used in this kind of installation. Simplify things by using also using `OPERATOR_ID` when obtaining an operator id from EnvVar settings. Still support `KAMEL_OPERATOR_ID` when installing via `kamel install` in order to overwrite the default id given in the CRDs.
```release-note
Fix: Also use OPERATOR_ID EnvVar to obtain the operator id
```

[Backport-1.10.x] fix(#3657): Also use OPERATOR_ID EnvVar to obtain the operator id

---

pkg/client/client.go
pkg/cmd/operator/operator.go
pkg/controller/add_build.go
pkg/controller/add_integration.go
pkg/controller/add_integrationkit.go
pkg/controller/add_integrationplatform.go
pkg/controller/add_kamelet.go
pkg/controller/add_kameletbinding.go
pkg/controller/build/build_controller.go
pkg/controller/controller.go
pkg/controller/integration/integration_controller.go
pkg/controller/integrationkit/integrationkit_controller.go
pkg/controller/integrationplatform/integrationplatform_controller.go
pkg/controller/kamelet/kamelet_controller.go
pkg/controller/kameletbinding/kamelet_binding_controller.go

This PR introduces an argument to the functions that add controllers to the runtime manager, so it's possible to reuse controllers with custom clients, while avoiding creating one client per controller. 
```release-note
chore: Add client argument to controllers
```

chore: Add client argument to controllers

---

pkg/cmd/operator/operator.go

```release-note
fix: Use SIGTERM and SIGINT aware context for bootstrap operations
```

fix: Use SIGTERM and SIGINT aware context for bootstrap operations

---

e2e/global/knative/knative_platform_test.go
pkg/controller/integration/platform_setup.go
pkg/controller/kameletbinding/integration.go
pkg/install/cluster.go
pkg/install/knative.go
pkg/install/operator.go
pkg/util/knative/enabled.go

This refactors the current logic to check whether Knative is installed, that is anyway debatable, so it uses the globally provided client. 
```release-note
chore: Use global client discovery API to check Knative install
```

chore: Use global client discovery API to check Knative install

---

pkg/cmd/run.go

Fix ##3265 is no longer needed for #3257 since spectrum 0.3.11 with container-tools/spectrum#8 fix is released. Let's not forget to remove the deprecation code.
```release-note
NONE
```

Remove deprecated spectrum fix

---

pkg/util/defaults/defaults.go
resources/traits.yaml
script/Makefile

This is for early checking errors. I already noticed errors in tracing trait and other tests.

Align to Camel-k-runtime 1.15.0 and camel-kamelets 0.9.1 tag

---

pkg/cmd/install.go

Avoids the default maven repositories being removed from the maven settings by the new specified repositories
```release-note
When overriding the maven repository settings, the default repositories should still be retained to avoid losing the base
dependencies.
```

Adds the default maven repositories if extra ones are added

---

script/Makefile

Backport #3651 to 1.10.x
```release-note
NONE
```

chore(ci): experimental use of gotestfmt for e2e (1.10.x)

---

script/Makefile

This is a small addition to Makefile. Since the output can be verbose I'd prefer to separate the main build (`make test`) from this `make test-fmt`. Anyone who wants to look into the local test failures can run `make test-fmt`.
```release-note
NONE
```

chore: add test-fmt make target

---

pkg/cmd/install.go

Avoids the default maven repositories being removed from the maven settings by the new specified repositories
```release-note
When overriding the maven repository settings, the default repositories should still be retained to avoid losing the base
dependencies.
```

Backport: Adds the default maven repositories if extra ones are added

---

pkg/trait/quarkus.go
pkg/trait/quarkus_test.go

Manual backport of #3682 
Propagate annotation trait configuration from Integration to IntegrationKit. This makes sure that the kit matches the integration once the native build is done.
```release-note
Fix: Quarkus native mode for KameletBinding
```

[BACKPORT-1.9.x] fix(#3671): Fix native mode for KameletBinding

---

pkg/cmd/bind.go
pkg/cmd/run.go

when in offline mode
Closes #3662
```release-note
fix(cli): don't verify operator in output mode
```

fix(cli): don't verify operator

---

pkg/cmd/bind.go
pkg/cmd/run.go

when in offline mode
Closes #3662
```release-note
fix(cli): don't verify operator when in offline mode
```

[backport] fix(cli): don't verify operator

---

e2e/global/common/config/config_test.go
e2e/namespace/install/cli/run_test.go
e2e/support/test_support.go

* Separating a test into functions make the test considerably slower. Therefore, splitting the test should only be a last resort course of action
* test_support.go
* Improves the delete integrations function to wait for the deletion to complete before moving on
```release-note
NONE
```

Due to slower performance revert tests to sub-tests from separate functions

---

script/Makefile

backport #3735
```release-note
NONE
```

chore: gotestfmt is renamed to gotesttools/gotestfmt (1.10.x)

---

e2e/global/common/kamelet_test.go
e2e/namespace/install/cli/files/TimerCustomKameletIntegration.java
e2e/namespace/install/cli/kamelet_test.go
pkg/cmd/kamelet.go
pkg/cmd/kamelet_add_repo.go
pkg/cmd/kamelet_remove_repo.go
pkg/cmd/kamelet_remove_repo_test.go

fixes #3667 
The subcommand `add-repo` is not compatible with a global operator as it is now, it should be reviewed to propose a way to use it in case a global operator is used.
* Add the subcommand `remove-repo` to be able to remove a repository in order to be able to clean up the Integration Platform used for the e2e test
* Update the active primary IntegrationPlaform of the namespace when the operator id is not set 
```release-note
feat(cli): Make add-repo and remove-repo compatible with a global operator
```

feat(cli): Make add-repo and remove-repo compatible with a global operator

---

e2e/namespace/install/cli/kamelet_test.go
go.mod
go.sum
script/Makefile
script/build_bundle_index.sh

Improvements to OLM bundle building of test index

---

helm/camel-k/templates/operator.yaml
helm/camel-k/values.yaml

Configuration of Log Level in Helm chart
```release-note
operator log level made configurable
```

change(helm): logLevel configuration enabled

---

script/get_catalog.sh

When the runtime is SNAPSHOT and uses a snapshot repository the downloaded artifact contains a timestamp which is not recognized when trying to move the file.
```release-note
NONE
```

Fix get_catalog.sh when runtime is snapshot

---

.github/workflows/release.yml

fix(ci): add cluster type for nightly releases

---

e2e/namespace/native/native_binding_test.go
e2e/namespace/native/native_test.go
e2e/support/test_support.go
script/Makefile

Attempt to address #3773 
```release-note
NONE
```

fix(e2e): increase build timeout for native build tests: 40m -> 60m (1.10.x)

---

e2e/namespace/native/native_binding_test.go
e2e/namespace/native/native_test.go
e2e/support/test_support.go
script/Makefile

Fix #3773. This should also fix the `native-it` failures with pull req #3764.
```release-note
NONE
```

fix(e2e): increase build timeout for native build tests: 40m -> 60m

---

e2e/global/builder/build_test.go
e2e/namespace/install/kustomize/operator_test.go
e2e/namespace/install/kustomize/setup_test.go
e2e/namespace/native/native_test.go

Since we've been doing without the `openshift` CI for some time, let's remove the OCP3 guards in E2E tests.
```release-note
NONE
```

chore(e2e): clean up OCP3 guards

---

e2e/namespace/install/cli/install_test.go
e2e/support/test_support.go
pkg/apis/camel/v1/integrationplatform_types.go
pkg/apis/camel/v1/integrationplatform_types_support.go
pkg/controller/integrationplatform/create.go
pkg/controller/integrationplatform/monitor.go

Fix #2555
```release-note
feat(controller): add Ready condition to IntegrationPlatform
```

feat(controller): add Ready condition to IntegrationPlatform

---

pkg/util/command.go
pkg/util/command_test.go
pkg/util/jvm/keystore.go
pkg/util/maven/maven_log.go
pkg/util/maven/maven_log_test.go

With this PR we introduce the possibility to parse any external command call output in order to use it for more meaningful error messages to be reported to the final user. In particular we'll collect the first error message line in the `mvn` execution used during build and add to the error in order to be eventually reported in the `IntegrationKit` error status.
Closes #3779
```release-note
feat(build): parse cmd execution for errors
```

feat(build): parse cmd execution for errors

---

pkg/util/command.go
pkg/util/command_test.go
pkg/util/jvm/keystore.go
pkg/util/maven/maven_log.go
pkg/util/maven/maven_log_test.go

Closes #3779
```release-note
feat(build): parse cmd execution for errors
```

[Backport] feat(build): parse cmd execution for errors

---

config/crd/bases/camel.apache.org_integrationkits.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
helm/camel-k/crds/crd-integration-kit.yaml
pkg/apis/camel/v1/integrationkit_types.go
pkg/apis/camel/v1/zz_generated.deepcopy.go
pkg/trait/camel.go
pkg/trait/quarkus.go
pkg/trait/trait_test.go

Closes #3758
```release-note
fix(trait): Camel trait as IntegrationKit
```

fix(trait): Camel trait as IntegrationKit

---

pkg/trait/jolokia.go
pkg/trait/jolokia_test.go

camel-k-runtime change https://github.com/apache/camel-k-runtime/pull/901
```release-note
NONE
```

Use jolokia version defined in camel-k-runtime

---

pkg/util/command_test.go
pkg/util/maven/maven_log_test.go

`/usr/bin/data` and `/usr/bin/mvn` does not exist on macOS aarch64 environment
Instead assume both binaries being part of the PATH

chore: Fix tests on macOS aarch64

---

.github/workflows/native.yaml
e2e/global/builder/build_test.go
e2e/namespace/native/native_binding_test.go
e2e/namespace/native/native_test.go
e2e/support/test_support.go
script/Makefile

Fix #3784
```release-note
NONE
```

chore(e2e): separate native-it and run it nightly

---

e2e/global/common/traits/files/NeverReady.java
e2e/global/common/traits/health_test.go
pkg/controller/integration/health.go
pkg/controller/integration/health_test.go
pkg/controller/integration/monitor.go
pkg/controller/integration/monitor_cronjob.go
pkg/controller/integration/monitor_deployment.go
pkg/controller/integration/monitor_knative.go

Fix #3761
```release-note
fix(controller): Ready condition message not always taken from Camel Health Checks
```

fix(controller): Ready condition message not always taken from Camel Health Checks

---

e2e/global/common/traits/files/NeverReady.java
e2e/global/common/traits/health_test.go
pkg/controller/integration/health.go
pkg/controller/integration/health_test.go
pkg/controller/integration/monitor.go
pkg/controller/integration/monitor_cronjob.go
pkg/controller/integration/monitor_deployment.go
pkg/controller/integration/monitor_knative.go
script/Makefile

Backport #3814
```release-note
fix(controller): Ready condition message not always taken from Camel Health Checks
```

fix(controller): Ready condition message not always taken from Camel Health Checks (1.10.x)

---

build/Dockerfile

Trying to address #3817. But we might need to downgrade to `ubi-quarkus-native-image:22.2.0-java11` for camel-k-runtime as well.
https://github.com/apache/camel-k-runtime/blob/main/pom.xml#L47
```release-note
chore(build): upgrade base image to ubi-quarkus-mandrel:22.2.0.0-Final-java11
chore(build): upgrade Maven to 3.8.6
```

chore(build): upgrade Maven and ubi-quarkus-mandrel base image

---

e2e/common/traits/pdb_test.go
pkg/trait/pdb.go
pkg/trait/pdb_test.go

Closes #3840
```release-note
fix(core): move to policy/v1
```

[backport 1.8.x] fix(core): move to policy/v1

---

e2e/global/common/traits/pdb_test.go
pkg/trait/pdb.go
pkg/trait/pdb_test.go

Closes #3840
```release-note
fix(core): move to policy/v1
```

[backport 1.10.x] fix(core): move to policy/v1

---

docs/antora.yml

Refs: #3852
Update dependencies versions configuration for documentation to match those of the 1.10.3 release.
```release-note
NONE
```

fix: upgrade configuration docs to reflect the last release 1.10.3

---

pkg/apis/camel/v1/camelcatalog_types_support.go
pkg/util/camel/camel_runtime_catalog.go
pkg/util/source/inspector.go
pkg/util/source/inspector_groovy_test.go
pkg/util/source/inspector_java_script_test.go
pkg/util/source/inspector_java_source_test.go
pkg/util/source/inspector_kotlin_test.go
pkg/util/source/inspector_xml.go
pkg/util/source/inspector_xml_test.go
pkg/util/source/inspector_yaml.go
pkg/util/source/inspector_yaml_test.go
pkg/util/source/test_support.go

This fixes an issue reported by @brunoNetId that Camel K doesn't resolve dataformat dependencies correctly unless doing explicitly `kamel run route.xml -d camel:jackson` for the following DSLs:
```xml
<to uri="dataformat:jackson:unmarshal"/>
```
```xml
<unmarshal>
<json/>
</unmarshal>
```
```xml
<unmarshal>
<json library="Jackson"/>
</unmarshal>
```
```release-note
fix(source): dataformat dependencies not resolved
```

fix(source): dataformat dependencies not resolved

---

pkg/util/command_test.go

* Fix: #3813
Signed-off-by: yugo-horie <u5.horie@gmail.com>
#3813 
We divided the test case each OS.
```release-note
TestRunAndLog to pass both linux and MacOS
```

chore(test) : TestRunAndLog to pass on mac os

---

pkg/trait/camel.go

backport #3858
```release-note
NONE
```

fix(trait): trait error "camel-catalog already exists" during upgrade (1.10.x)

---

.github/actions/release-nightly/action.yml

Running `native-it` as nightly smoke test looks great on `main` branch (less than 1 hour running):
📦 github.com/apache/camel-k/e2e/namespace/native
✅ TestNativeBinding (12m28.67s)
✅ TestNativeBinding/kamelet_binding_with_native_build (9m0.12s)
✅ TestNativeBinding/warm_up_before_native_build_testing (3m14.21s)
✅ TestNativeIntegrations (12m14.6s)
✅ TestNativeIntegrations/automatic_rollout_deployment_from_fast-jar_to_native_kit (8m47.86s)
✅ TestNativeIntegrations/unsupported_integration_source_language (870ms)
✅ TestNativeIntegrations/warm_up_before_native_build_testing (3m11.3s)
With this PR we enable the same on `release-1.10` branch.
```release-note
NONE
```

[backport 1.10] chore(ci): move native into nigtly release wf

---

e2e/global/common/traits/prometheus_test.go

The prometheus traits now are fully tested as it's possible to run the test on OCP 4.x.
In the trait `pod-monitor` now the default label is checked.
The test for the trait `pod-monitor-labels` has been added checking in the `PodMonitor` the presence of the specified label.

prometheus trait fully tested as in CI, the version of OCP is 4.x

---

e2e/global/knative/files/http_out.groovy
e2e/global/knative/knative_test.go
pkg/trait/service.go
pkg/trait/service_test.go

https://github.com/apache/camel-k/issues/3849
When knative-service and k8s service traits are enabled, the priority is to use knative-service in knative profile
```release-note
NONE
```

fix(service): Create k8s service when knative-service trait is disabled

---

e2e/global/knative/files/http_out.groovy
e2e/global/knative/knative_test.go
pkg/trait/service.go
pkg/trait/service_test.go

https://github.com/apache/camel-k/issues/3849
When knative-service and k8s service traits are enabled, the priority is to use knative-service in knative profile
(cherry picked from commit 07563546a5d04c53dab122e90bc768e08514defe)
```release-note
NONE
```

fix(service): Create k8s service when knative-service trait is disabled (1.10.x)

---

script/Makefile

Fixes #3800 
Make sure to add proper kamel CLI binary to Docker image when building on macOS

fix(#3800): Add proper kamel CLI to image build on macOS

---

e2e/global/common/scale_integration_test.go
e2e/support/test_support.go
pkg/client/camel/clientset/versioned/typed/camel/v1/fake/fake_integration.go
pkg/client/camel/clientset/versioned/typed/camel/v1/integration.go

Closes #3818
```release-note
fix(e2e): use generated API methods
```

fix(e2e): use generated API methods

---

examples/saga/Flight.java
examples/saga/Payment.java
examples/saga/README.md
examples/saga/Train.java

Fix for #3869.
Update REST services to no longer use [unsupported embedded routes](https://camel.apache.org/manual/camel-3x-upgrade-guide-3_16.html#_removed_support_for_embedded_routes).
Update Readme to to run the Saga route with `-d camel:direct` and include the direct component dependency.

Fix #3869: Update Saga Example

---

pkg/cmd/bind.go
pkg/cmd/bind_test.go

fixes #2586
The `kamel bind` command  uses 0 index start for the definition of step properties : 
```sh
kamel bind ... --step my-step-1 --step my-step-2 -p step-0.my-key=value1 -p step-1.my-key=value2
```
Having an index start at 1 is more user friendly : 
```shell
kamel bind ... --step my-step-1 --step my-step-2 -p step-1.my-key=value1 -p step-2.my-key=value2
```
* Modify the transformation from command to spec for steps in biding command code
* Add a unit test on step values
```release-note
feat(cli): Update Kamel bind step index in properties to start at 1 instead of 0
```

feat(cli): Update Kamel bind step index in properties to start at 1 instead of 0

---

pkg/cmd/install.go
pkg/install/cluster.go
pkg/install/operator.go
pkg/util/olm/available.go

To promote the Kustomize installation method, I'm checking the feature parity between the two methods. In order to make the task easier, I first refactored the `install` cmd. As a side product, I was able to remove two `// nolint: maintidx` comments.
```release-note
NONE
```

fix(cmd): refactor install cmd to remove maintidx lint

---

e2e/global/common/kamelet_binding_test.go
e2e/global/common/traits/errored_trait_test.go
e2e/support/test_support.go
pkg/apis/camel/v1alpha1/kamelet_binding_types.go
pkg/controller/integration/platform_setup.go
pkg/controller/kameletbinding/initialize.go
pkg/controller/kameletbinding/kamelet_binding_controller.go
pkg/controller/kameletbinding/monitor.go

With this PR we aim to improve the reconciliation loop of Integrations and KameletBindings. The Integration now fails and report the error that may happen during the execution of traits. We also change the reconciliation loop for KameletBindings in order to detect any failure (failing traits, or wrong spec), report an error and stop the reconciliation loop.
Closes #3389
Closes #3010
```release-note
fix: reconciliation loops behaviors
```

fix: reconciliation loops behaviors

---

pkg/cmd/completion_bash.go

Fixes #3628
Adding some completion on CLI basic commands to improve its usability through bash completion.
The completion uses `kubectl` commands to retrieve the results.
* `kamel get` autocomplete on integrations
*`kamel delete` autocomplete on integrations (no modification made)
* `kamel get kit` autocomplete on all kits
* `kamel delete kit` still autocomplete on non-platform kits (no modification made)
* `kamel kamelet delete` autocomplete on non-readonly and non-bundled kamelets (this is the command behavior)
* `kamel describe kamelet` autocomplete on all kamelets
Pre-existing limit : the completion never use the value of the namespace flag even if it is provided, it always use the kubectl config context namespace. For `kamel -n usernamespace get <TAB>`, completion runs  `kamel get `. …

feat(cli): Add autocomplete on integrations, kits, kamelets commands

---

.github/workflows/automatic-updates.yml
.github/workflows/release.yml
release.adoc
script/Makefile
script/bump_actions.sh

With this PR we automate the replacement of the oldest release action (and any other automated github action) with the last released.
```release-note
feat: automatic github actions bump 
```

feat: automatic github actions bump 

---

pkg/cmd/completion_bash.go

Fixes #3922
Make the autocompletion internal `kubectl` command and the CLI `kamel` command as consistant as possible in regards of namespace declaration.
* retrieve the namespace flag from the current command
* retrieve the namespace config with the `kamel config --list` command only if awk is available
* apply the namespace to the kubectl autocompletion command : flag namespace > config namespace > no specified namespace
The generated completion script was tested on Linux Fedora OS bash. 
Closes: #3922
```release-note
Use flag/config namespace for existing CLI completion kubectl commands
```

feat(cli): Add namespace in command autocompletion bash

---

e2e/global/common/config/config_test.go

Reverts the mistaken commented-out e2e tests in `config_test.go`. However, the test `"Property precedence` is failing consistently when executed locally on OCP4. Will aim to debug and diagnose the reason.
```release-note
NONE
```

Test config revertions

---

pkg/cmd/completion_bash.go
pkg/cmd/install.go

`--context` flag was replaced by `--kit` flag (#726) then `kit` flag was removed from `kamel install` command (#1609) therefore its completion code is no longer used.

chore(cli): Remove dead code on completion for context flag

---

.github/actions/automatic-updates/action.yml
.github/workflows/build.yml
.github/workflows/builder.yml
.github/workflows/common.yml
.github/workflows/install.yml
.github/workflows/knative.yml
.github/workflows/local.yml
.github/workflows/openshift.yml
.github/workflows/release.yml
.github/workflows/upgrade.yml

[backport 1.11.x] fix(ci): github rate limit and shell in update action

---

.github/actions/automatic-updates/action.yml
.github/workflows/build.yml
.github/workflows/builder.yml
.github/workflows/common.yml
.github/workflows/install.yml
.github/workflows/knative.yml
.github/workflows/local.yml
.github/workflows/openshift.yml
.github/workflows/upgrade.yml

[backport 1.10.x] fix(ci): github rate limit and shell in update action

---

.github/workflows/release.yml

Although not used by `main` release step, it is still required by `v_10` and `v_11` release steps, so, it cannot be removed.
```release-note
NONE
```

fix(ci): revert usage of TEST_CLUSTER

---

e2e/global/common/traits/container_test.go
pkg/controller/integration/monitor.go

Fixes #3941 
Ensure camel-k controller for integration condition status works well with any change in pod's container name declared in the integration.
Ensure that if pod's container.name is changed to something else than `integration` by trait `container.name`. 
Any change done directly on the pod and/or deployment description k8s object won't be managed by the camel-k controller on integrations.
```release-note
Ensure `container.name` trait is used by the integration's controller.
```

fix(controller): ensure `container.name` trait is used by the integration controller

---

e2e/namespace/install/kustomize/uninstall_test.go

Small e2e improvements in case they occasionally fail.
```release-note
NONE
```

fix(e2e): stabilise kustomize uninstall tests

---

script/Makefile

Close #3957
```release-note
NONE
```

fix(e2e): Kamelets tag compatibility with 3.19

---

e2e/namespace/install/cli/run_test.go

I cannot come up with a better solution. If the execution is sequential, temporary removing the environment variable should be fine.
Close #3952
```release-note
fix(test): temporary remove env var
```

fix(test): temporary remove env var

---

pkg/util/camel/camel_runtime_catalog.go
pkg/util/source/inspector.go
pkg/util/source/inspector_yaml_test.go
pkg/util/source/test_support.go

Do not raise errors during dependency inspection when using property placeholders in toURI. Fixes http-sink Kamelet
Fixes #3896

fix(#3896): Fix dependency inspector supporting property placeholders

---

docs/modules/ROOT/pages/kamelets/kamelets-dev.adoc

adding TIP for optional property placeholder syntax for non-required parameter which does not not define a default value in the Kamelet's `spec.definition.properties`.
Resolves https://github.com/apache/camel-k/issues/3986

Add TIP for optional prop placeholder for non-req param

---

e2e/namespace/install/operator_id_filtering_test.go

- Fix TestOperatorIDFiltering/Operators_can_handoff_scoped_integrations
- Just set new operator ID, there is no need to explicitly rebuild the integration
- Avoid race condition between rebuild command and the operator ID update
- Due to race conditions the test sometimes failed with concurrent resource modification error

fix(#3988): Fix flaky E2E test on operator multi tenancy

---

.github/actions/kamel-prepare-env/action.yml
e2e/namespace/upgrade/cli_upgrade_test.go
e2e/namespace/upgrade/olm_upgrade_test.go
pkg/util/defaults/defaults.go
script/Makefile

- feat: use eclipse-temurin:11 as runtime base image
- workaround: force eclipse-temurin:11 as runtime base image for upgrade tests
- feat: use eclipse temurin as java distribution for github actions
```release-note
NONE
```

 feat: switch to eclipse-temurin:11 as runtime base image (1.11.x)

---

.github/actions/kamel-prepare-env/action.yml
e2e/namespace/upgrade/cli_upgrade_test.go
e2e/namespace/upgrade/olm_upgrade_test.go
pkg/util/defaults/defaults.go
script/Makefile

- feat: use eclipse-temurin:11 as runtime base image
- workaround: force eclipse-temurin:11 as runtime base image for upgrade tests
- feat: use eclipse temurin as java distribution for github actions
```release-note
NONE
```

feat: switch to eclipse-temurin:11 as runtime base image (1.10.x)

---

e2e/support/gomega_support.go
e2e/support/test_util.go

Fixes #3992
This commit set a more reasonable default for gomega inetrnal timeout
and poll interval used for e2e testing.
The defaults are:
- **EventuallyTimeout** is set to 1s (not changed)
- **EventuallyPollingInterval** is set to 500ms
- **ConsistentlyDuration** is set to 100ms (not changed)
- **EventuallyPollingInterval** is set to 500ms
Values can be configured via env vars:
- E2E_DEFAULT_EVENTUALLY_TIMEOUT
- E2E_DEFAULT_EVENTUALLY_POLLING_INTERVAL
- E2E_DEFAULT_CONSISTENTLY_DURATION
- E2E_DEFAULT_CONSISTENTLY_POLLING_INTERVAL
```release-note
NONE
```

feat(e2e): Set a more reasonable default for gomega eventually's polling interval

---

e2e/global/common/scale_binding_test.go
e2e/namespace/install/cli/bind_test.go
e2e/namespace/install/cli/uninstall_test.go
e2e/namespace/install/operator_id_filtering_test.go
e2e/support/test_support.go

as a default. They are required only in some test.
```release-note
chore(test): don't install kamelet catalog
```

chore(test): don't install kamelet catalog

---

e2e/namespace/native/native_binding_test.go

Closes #4022
```release-note
fix(test): use Kamelet catalog
```

fix(test): use Kamelet catalog

---

script/package_maven_artifacts.sh

When using the SNAPSHOT version, use the camel-k-runtime distribution from the local directory instead of downloading it.
```release-note
NONE
```

Fix the package of camel-k-runtime when using SNAPSHOT version

---

e2e/yaks/common/kamelet-data-types/event-sink.kamelet.yaml
e2e/yaks/common/kamelet-data-types/event-source.kamelet.yaml

- Apache Camel Kamelets catalog main branch has moved to Camel 4
- Use 3.x branch instead to fix Jitpack dependency resolving

fix(#4044): Fix Kamelet utils version in e2e tests

---

e2e/namespace/upgrade/olm_upgrade_test.go

Backport the fix also to 1.10 upstream

olm_upgrade_test - use only major.minor.patch to verify csv in ik

---

.github/workflows/native.yml
.github/workflows/nightly-automatic-updates.yml
.github/workflows/nightly-native-test.yml
.github/workflows/nightly-release.yml

With this PR we let the contributor decide if running the Quarkus Native tests by adding a label to the PR.
```release-note
chore(ci): trigger native only when PR are labeled
```

chore(ci): trigger native only when PR are labeled

---

pkg/util/maven/maven_command.go

Resolves: #3956 
In case the settings-security.xml file is declared in the integration platform as [described in the documentation](https://camel.apache.org/camel-k/next/configuration/maven.html#maven-settings-security) it needs to be explicitly specified as part of the maven commands, else maven default to `${user.home}/.m2/settings-security.xml` instead of `/tmp/kit-xxxx/maven/settings-security.xml`.
```release-note
fix: Add maven settings-security.xml to maven command
```

fix(#3956): Add maven settings-security.xml to maven command

---

pkg/util/maven/maven_command.go

Backport of PR https://github.com/apache/camel-k/pull/4099 on `release-1.12.x`
```release-note
NONE
```

[release-1.12.x] fix(#3956): Add maven settings-security to maven command

---

pkg/util/maven/maven_command.go

Backport of PR #4099 on `release-1.10.x`
```release-note
NONE
```

[release-1.10.x] fix(#3956): Add maven settings-security to maven command

---

docs/modules/ROOT/pages/installation/advanced/resources.adoc

Fix a couple of typos and improve the overall language in the Advanced->Resource Management documentation

fix typos on resources.adoc and improve language

---

docs/modules/ROOT/pages/architecture/traits.adoc

Fix minor typos in the Traits documentation, also improve the language here and there.

fix typos on traits.adoc and improve the overall language

---

.github/actions/automatic-updates/action.yml
script/Makefile
script/update_default_ck_runtime.sh

This PR will automate the setting of Camel K Runtime dependency, taking last one available.
```release-note
feat(ci): scrape latest CK runtime available
```

feat(ci): scrape latest CK runtime available

---

.github/actions/automatic-updates/action.yml
script/Makefile
script/update_default_camel.sh

```release-note
chore(ci): camel kamelets catalog scraping
```

chore(ci): camel kamelets catalog scraping

---

pkg/cmd/version.go
pkg/cmd/version_test.go

```release-note
fix(cmd): compatibility check when not a semver
```

fix(cmd): compatibility check when not a semver

---

pkg/cmd/version.go
pkg/cmd/version_test.go

```release-note
fix(cmd): compatibility check when not a semver
```

[Backport 1.12.x] fix(cmd): compatibility check when not a semver

---

pkg/cmd/version.go
pkg/cmd/version_test.go

```release-note
fix(cmd): compatibility check when not a semver
```

[Backport 1.10.x] fix(cmd): compatibility check when not a semver

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/installation/installation.adoc
docs/modules/ROOT/pages/installation/platform/docker-desktop.adoc
docs/modules/ROOT/pages/installation/registry/registry.adoc

fixes #4150 
Some issues are raised due to a misconfiguration when using Docker Desktop because there is no guide to install Camel-K on this particular environment.
* Add a specific installation guide for Docker Desktop

Ref #4150: Add the installation guide for Docker Desktop

---

e2e/install/cli/uninstall_test.go
e2e/support/test_support.go
pkg/cmd/uninstall.go

Fixes #4160 
When using `kamel uninstall` command the CamelCatalogs CR are not removed from the cluster. When an operator with the same Runtime is installed, it is already considered as Ready so the builder image container is not builded again with the code from the operator.
Remove all the CamelCatalogs in the namespace of the operator on `kamel uninstall call` and add a `skip-camel-catalogs` flag.
```release-note
Fix(cli): Remove CamelCatalogs CR on kamel uninstall
```

fix(cli): Remove CamelCatalogs CR on kamel uninstall

---

e2e/namespace/native/files/Java2.java
e2e/namespace/native/files/yaml2.yaml
e2e/namespace/native/native_test.go
e2e/namespace/native/native_with_sources_test.go
pkg/controller/integration/kits.go
pkg/controller/integration/kits_test.go
pkg/resources/resources.go

```release-note
fix(builder): native from source should rebuild
```

[Backport 1.12.x] fix(builder): native from source should rebuild

---

pkg/cmd/run.go
pkg/cmd/run_test.go

Closes #4163
```release-note
fix(cmd): run does not expand camel properties
```

fix(cmd): run does not expand camel properties

---

pkg/cmd/run.go
pkg/cmd/run_test.go

```release-note
fix(cmd): run does not expand camel properties
```

[Backport 1.12.x] fix(cmd): run does not expand camel properties

---

pkg/cmd/rebuild.go
pkg/cmd/rebuild_test.go

Closes #4208
```release-note
fix(cmd): rebuild KameletBindings
```

fix(cmd): rebuild KameletBindings

---

addons/strimzi/duck/client/internalclientset/fake/register.go
addons/strimzi/duck/client/internalclientset/scheme/register.go
config/manifests/bases/camel-k.clusterserviceversion.yaml
pkg/client/camel/clientset/versioned/fake/register.go
pkg/client/camel/clientset/versioned/scheme/register.go
script/Makefile

```release-note
chore(olm): upgrade operator sdk
```

chore(olm): upgrade operator sdk

---

pkg/cmd/rebuild.go
pkg/cmd/rebuild_test.go

I realized that the `kamel rebuild` was developed to target Integrations by design. The bindings resource that created such Integrations were also refreshed by the operator. Sorry for the noise, reverting.
```release-note
NONE
```

chore: revert kamel rebuild changes

---

pkg/cmd/rebuild.go
pkg/cmd/rebuild_test.go
script/get_catalog.sh

Reverts apache/camel-k#4215
I think I was wrong about this. It seems the behavior of a rebuild is to always target the `Integration` (which is the one we need to rebuild). Once the rebuild is in place, also the related KameletBinding is changed accordingly.

Revert "[Backport 1.12.x] fix(cmd): rebuild KameletBindings"

---

pkg/apis/camel/v1/integration_types.go
pkg/trait/builder_test.go
pkg/trait/container.go
pkg/trait/container_probes_test.go
pkg/trait/container_test.go
pkg/trait/cron_test.go
pkg/trait/deployment.go
pkg/trait/deployment_test.go
pkg/trait/environment_test.go
pkg/trait/istio_test.go
pkg/trait/knative_service_test.go
pkg/trait/knative_test.go
pkg/trait/logging_test.go
pkg/trait/route_test.go
pkg/trait/service_test.go
pkg/trait/trait_test.go
pkg/trait/util.go
pkg/util/test/client.go

Fix https://github.com/apache/camel-k/issues/3803
The knative check, required the `Client` object in `Environment` for various tests.
```release-note
Fix: Improve error reporting in case of knative is required but not installed
```

Improve error reporting in case of knative is required but not installed

---

config/crd/bases/camel.apache.org_integrationplatforms.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
e2e/commonwithcustominstall/catalog_builder_test.go
e2e/support/test_support.go
helm/camel-k/crds/crd-integration-platform.yaml
pkg/apis/camel/v1/integrationplatform_types.go
pkg/apis/camel/v1/integrationplatform_types_support.go
pkg/apis/camel/v1/zz_generated.deepcopy.go
pkg/client/camel/applyconfiguration/camel/v1/integrationplatformbuildspec.go
pkg/controller/catalog/initialize.go
pkg/platform/defaults.go

Closes #4226
```release-note
fix(controller): camelcatalog default timeout
```

fix(controller): camelcatalog default timeout

---

pkg/apis/camel/v1alpha1/error_handler_types_support.go
pkg/controller/kameletbinding/error_handler.go
pkg/controller/kameletbinding/error_handler_test.go

Introduced a validation for each kind of error handler.
With this PR we make sure that every error handler type is validated against the expected configuration. `Validate()` func need to be configured for each type according the logic required for it (in this case it seems only the `sink` requires some validation).
Closes #3586
```release-note
fix: won't panic on error handler validation failure
```

fix: won't panic on error handler validation failure

---

pkg/cmd/promote_test.go
pkg/cmd/version.go
pkg/cmd/version_test.go

fix for #3836 
command output
```
kamel version --all -v
You're using Camel K 2.0.0-SNAPSHOT client with a 1.12.0 cluster operator, it's recommended to use the same version to improve compatibility.
Camel K Client 2.0.0-SNAPSHOT
Git Commit: 7747ea67f8ed620d31123d4511beda40b9e98f49
Camel K Operator 1.12.0
Name: camel-k
Publish Strategy: S2I
Registry Address: 
Runtime Version: 1.17.0
Git Commit: a62a06f7261436641850abcb1b2e01afafd4be3d
Go Os: linux
Go Version: go1.18.10
Camel Quarkus Version: 2.16.0
Camel Version: 3.20.1
Quarkus Version: 2.16.0.Final
Quarkus Native Builder Image: quay.io/quarkus/ubi-quarkus-mandrel:22.2.0.0-Final-java11
```

fix(#3836) Expose runtime details in kamel version -a -v

---

e2e/commonwithcustominstall/builder_test.go
e2e/support/test_support.go
pkg/controller/build/monitor_pod.go

The builder Pods may not have a /bin/kill command, but do have a builtin shell kill command available.
Closes #4241
```release-note
fix(ctrl): use builtin command kill
```

fix(ctrl): use builtin command kill

---

pkg/cmd/uninstall.go
pkg/install/operator.go

Closes #3829
```release-note
fix(cmd): uninstall kube-public rolebindings
```

fix(cmd): uninstall kube-public rolebindings

---

pkg/install/operator.go

Enhance #4251 
```release-note
chore(cmd): don't warn if rolebinding exists
```

chore(cmd): don't warn if rolebinding exists

---

e2e/commonwithcustominstall/platform_traits_test.go

fix(#3476) Add tests for enabling traits at IntegrationPlatform

---

pkg/cmd/uninstall.go
pkg/util/watch/watch.go

Closes #4246
```release-note
fix(cmd): uninstall to wait the operator pod
```

fix(cmd): uninstall to wait the operator pod

---

pkg/cmd/operator/operator.go

Closes #4299
```release-note
fix(operator): do not panic if cannot set GOMAXPROCS
```

[Backport 1.12.x] fix(operator): do not panic if cannot set GOMAXPROCS

---

pkg/cmd/operator/operator.go

Closes #4299
```release-note
fix(operator): do not panic if cannot set GOMAXPROCS
```

[Backport 1.10.x] fix(operator): do not panic if cannot set GOMAXPROCS

---

e2e/yaks/common/kamelet-beans/yaks-config.yaml
e2e/yaks/common/kamelet-binding-autoload/yaks-config.yaml
e2e/yaks/common/kamelet-binding-broker/yaks-config.yaml
e2e/yaks/common/kamelet-binding-http/yaks-config.yaml
e2e/yaks/common/kamelet-binding-property-encoding/yaks-config.yaml
e2e/yaks/common/kamelet-binding/yaks-config.yaml
e2e/yaks/common/kamelet-data-types/yaks-config.yaml
e2e/yaks/common/kamelet-steps/yaks-config.yaml
e2e/yaks/common/kamelet/yaks-config.yaml

- Wait for custom Kamelets to be in ready state to avoid test errors due to slow operator reconciliation loops
- Avoids Kamelet not found errors

fix(e2e): Stabilize YAKS E2E tests

---

docs/modules/ROOT/pages/cli/cli.adoc

I suggest to add to overview cli commands which are referenced in other parts of documentation (kamel install/uninstall/bind) or are often used (rebuild, reset, version)

Add often used cli commands

---

e2e/builder/build_test.go

- Wait for IntegrationPlatforms in user namespaces to become ready before starting new builds
- Avoids racing conditions on build and integration platform reconciliation loops
- Avoids 1st build to succeed before 3rd build has been scheduled (skips the max build limit)

fix(e2e): Improve max build limit E2E test

---

e2e/builder/build_test.go

- Wait for IntegrationPlatform to become ready after operator installation
- Avoids resources to get stuck in waiting for integration platform state

fix(e2e): Improve builder E2E tests

---

.github/actions/e2e-telemetry/action.yml
.github/actions/kamel-config-cluster/action.yaml

Upgrade e2e deployed operators:
* otlp collector
* olm
Update defaults for DefaultRuntimeVersion
```release-note
NONE
```

chore(e2e) Upgrade test operators

---

e2e/commonwithcustominstall/local_platform_test.go
e2e/support/test_support.go
pkg/platform/defaults.go
pkg/platform/defaults_test.go

Users are allowed to create namespace local IntegrationPlatform resources in order to overwrite settings used in the operator.
These namespace local platform settings should derive from the IntegrationPlatform being used by the operator by default. This means that only explicitly specified settings do overwrite the platform defaults used in the operator.
This PR makes sure that we use a consistent platform settings hierarchy where the global operator platform settings always represent the basis for user specified platform settings.
The changes in this PR:
- Makes sure to apply global integration platform settings when creating namespace local platform
- Global platform settings resist when the setting is not explicitly overwritten in the given user namespace integration platform
**Release …

fix: Consistent integration platform settings hierarchy

---

addons/strimzi/duck/client/internalclientset/fake/register.go
addons/strimzi/duck/client/internalclientset/scheme/register.go
config/crd/bases/camel.apache.org_camelcatalogs.yaml
config/crd/bases/camel.apache.org_integrationkits.yaml
config/crd/bases/camel.apache.org_integrationplatforms.yaml
config/crd/bases/camel.apache.org_integrations.yaml
helm/camel-k/crds/crd-camel-catalog.yaml
helm/camel-k/crds/crd-integration-kit.yaml
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration.yaml
pkg/apis/camel/v1/camelcatalog_types.go
pkg/apis/camel/v1/integration_types.go
pkg/apis/camel/v1/integrationkit_types.go
pkg/apis/camel/v1/integrationplatform_types.go
pkg/client/camel/clientset/versioned/fake/register.go
pkg/client/camel/clientset/versioned/scheme/register.go

With this PR we are exposing some useful information by default int kube CLI:
```
squake:~/workspace/camel-k [main]$ kubectl get it
NAME   PHASE     RUNTIME PROVIDER   RUNTIME VERSION   KIT                        REPLICAS
test   Running   quarkus            3.20.1-SNAPSHOT   kit-ch596vsqgf4s73emsj6g   1
squake:~/workspace/camel-k [main]$ kubectl get ik
NAME                       ALIAS            PHASE   TYPE       LAYOUT     IMAGE
kit-ch596vsqgf4s73emsj6g   my-awesome-kit   Ready   platform   fast-jar   10.100.175.64/default/camel-k-kit-ch596vsqgf4s73emsj6g@sha256:33fe9888322e13543e62f8c2618772821d34a1899efaa80c25f2d98309ca3c2e
squake:~/workspace/camel-k [main]$ kubectl get ip
NAME      PHASE   BUILD STRATEGY   PUBLISH STRATEGY   REGISTRY ADDRESS   DEFAULT RUNTIME
camel-k   Ready   pod …
```

feat(cli): provide useful info in kubectl CLI

---

script/Makefile

Closes #4328
```release-note
fix(ci): native test path
```

fix(ci): native test path

---

.github/workflows/nightly-coverage.yml

- Only run workflow on GitHub repository 'apache/camel-k'
- Avoids merge conflicts on forked repositories

chore: Restrict nightly coverage workflow execution

---

e2e/commonwithcustominstall/reset_test.go
script/Makefile

Closes #4316
```release-note
fix(e2e): increase commonwithcustominstall timeout
```

fix(e2e): increase commonwithcustominstall timeout

---

pkg/cmd/uninstall.go

- Make sure to remove IntegrationPlatform resources from operator namespace on uninstall
- Do not filter on label "app=camel-k" when removing IntegrationPlatform resources
```release-note
fix: Always uninstall IntegrationPlatform resources
```

fix: Always uninstall IntegrationPlatform resources

---

pkg/cmd/uninstall.go

[Backport 1.12.x] Always uninstall integration platform

---

pkg/util/bindings/knative_ref.go
pkg/util/bindings/knative_ref_test.go

- Only run the binding provider when Knative is installed on the cluster
- Only run the binding provider when referencing a known Knative resource (e.g. broker, channel, service)
Fixes #4336 
```release-note
fix: Restrict Knative binding provider execution
```

fix(#4336): Restrict Knative binding provider execution

---

pkg/cmd/uninstall.go

[Backport 1.10.x] fix: Always uninstall IntegrationPlatform resources

---

.gitignore

The file is autogenerated at each build, and is a source of conflict. We better ignore.
```release-note
chore: ignore resources.go
```

chore: ignore resources.go

---

pkg/util/bindings/knative_ref.go

- Also restrict v1alpha1 binding provider
- Only run the binding provider when Knative is installed on the cluster
- Only run the binding provider when referencing a known Knative resource (e.g. broker, channel, service)

fix(#4336): Restrict Knative binding provider execution for v1alpha1

---

pkg/cmd/operator/operator.go
pkg/trait/platform.go
pkg/trait/platform_test.go
pkg/util/bindings/knative_ref.go
pkg/util/bindings/knative_ref_test.go

[Backport 1.10.x] fix(#4336): Restrict Knative binding provider execution

---

pkg/cmd/promote.go

```release-note
fix(cmd): promote should load catalog from k8s
```

fix(cmd): promote should load catalog from k8s

---

.github/dependabot.yml

The idea of this PR is to increase the level of dependencies upgrade automation to try to be aligned to the last developments. We only control Kubernetes dependencies which are the ones from which we depends in its core and we may want to have under full control.
NOTE: of course, we should not blindly merge any upgrade but reviewing carefully, and never do that if there is even a single check failing.
```release-note
chore(deps): ignore only k8s dependencies
```

chore(deps): ignore only k8s dependencies

---

e2e/global/builder/build_test.go
e2e/support/util/dump.go

It was failing with: `Build step io.quarkus.deployment.index.ApplicationArchiveBuildStep#build threw an exception: java.lang.OutOfMemoryError: Java heap space",`
Also increase the available lines when dumping operator log to retrive more information for investigation
This should fix the recent CI e2e tests of builder spectrum tests.
```release-note
NONE
```

Increase memory for builder spectrum knative test

---

pkg/cmd/promote.go

[Backport 1.10.x] fix(cmd): promote should load catalog from k8s

---

.github/dependabot.yml
go.mod
go.sum
pkg/cmd/version.go
pkg/cmd/version_test.go

Ref #4326
```release-note
chore(deps): remove camelcase dependency
```

chore(deps): remove camelcase dependency

---

pkg/trait/knative_service.go
pkg/trait/knative_service_test.go

The Knative service trait is responsible for choosing a Knative service as deployment strategy for an integration. This PR restricts the trait to integrations that either use passive consumers (e.g. knative, seda) or expose at least one Http endpoint (e.g. rest, http-platform)
Before that users could forcibly enable the trait also on active consumers (e.g. timer) which lead to errors on the Knative serving controllers. The trait has been using a Knative service with `min-scale=1` for these integrations. Now we use a normal deployment instead.
- Only apply Knative service trait on integrations that either use passive consumers or expos at least one Http endpoint
- Integrations are considered unsuitable for Knative service trait when they exclusively use active consumers that are not Http …

fix: Restrict Knative service trait to Http exposed and passive endpoints

---

pkg/cmd/promote.go

[Backport 1.12.x] fix(cmd): promote should load catalog from k8s

---

pkg/trait/knative_service.go
pkg/trait/knative_service_test.go

Manual backport of #4368
- Only apply Knative service trait on integrations that either use passive consumers or expos at least one Http endpoint
- Integrations are considered unsuitable for Knative service trait when they exclusively use active consumers that are not Http based
- Do not use Knative service with `min-scale=1` for unsuitable integrations instead use normal deployment

[Backport-1.12.x] fix: Restrict Knative service trait to Http exposed and passive endpoints

---

.github/actions/kamel-config-cluster/action.yaml

Remove unused ocp3 option from CI cluster config

---

go.mod
pkg/cmd/run_support.go
pkg/trait/jvm.go

Ref #4326 
```release-note
chore(deps): remove gopkg.in/inf.v0
```

chore(deps): remove gopkg.in/inf.v0

---

build/Dockerfile
pkg/controller/build/build_pod.go
pkg/install/operator.go

Since the new builder pod is configured to run with non root user and a persistent volume has been created there have been some permission/copy issues I fixed while working on #4297. The permissions issues can be fixed two different way on kubernetes security : extend root user or extend non-root user. 
Since it make more sense to try to avoid root (as a general rule) and some Dockerfile already use user with ID 1000 (same for group ID), I made some first modifications to try to have more non-root user for operator and builder pods.
There are also some warnings on integration containers security validations, but they will be dealt with #4297.
* Dockerfile : sets the group for folders used for dependencies is 1000
* Force 1000 as User ID/ Group ID/FS Group ID to be coherent with the one …

feat(core): Change Operator and Builder Pod user as non root 1000

---

docs/modules/ROOT/pages/configuration/dependencies.adoc
pkg/cmd/run_support.go
pkg/util/camel/camel_dependencies.go
pkg/util/camel/camel_dependencies_test.go

- Reuse logic in validate function just logging a warning and those validate function raising errors
- Remove unused function ValidateDependencies
- Add some unit tests
- Add some documentation on Camel dependency resolution via catalog
Successor PR to #4402 
Basically keeps the old logic of throwing errors when a dependency is not in the Camel catalog but adds some new unit tests and some improvements on the dependency validation functions

chore: Improve Camel dependency validation

---

docs/modules/ROOT/pages/configuration/dependencies.adoc
pkg/cmd/local/local.go
pkg/cmd/run_support.go
pkg/util/camel/camel_dependencies.go
pkg/util/camel/camel_dependencies_test.go

- Reuse logic in validate function just logging a warning and those validate function raising errors
- Remove unused function ValidateDependencies
- Add some unit tests
- Add some documentation on Camel dependency resolution via catalog
Manual backport of #4411

[Backport-1.12.x] chore: Improve Camel dependency validation

---

pkg/builder/s2i.go
pkg/controller/build/build_pod.go
pkg/controller/catalog/initialize.go
pkg/util/s2i/build.go

Ref #4297
Add S2I support for builder image generation for better support on Openshift.
* Add initialize builder image on catalog:
* creates (or replace) a BuildConfig resource
* creates (or replace) an ImageStream resource
* create a new builder image from dockerfile and source binary
* Light refactoring of S2I code
The `HOME` env variable has been added on builder image execution to some errors on file permissions without.
```release-note
Add S2I support for builder image generation
```

feat(core): Support S2I for builder image generation

---

.github/actions/coverage-badge/action.yml
.github/workflows/nightly-coverage.yml
README.adoc

Removed 3rd party dependencies from coverage badge workflow.
Added option to run the workflow manually.
```release-note
NONE
```

Removed coverage badge 3rd party dependency

---

build/Dockerfile
pkg/controller/build/build_pod.go
pkg/install/operator.go
pkg/resources/resources.go

Revert "feat(core): Fix Operator and Builder Pod user as non root 1000"
This reverts commit 8272026321f79a8bedfdacf357c806210338888c.
The user 0 (root) is set on:
* Dockerfile's folders that the operatory copy 
* SecurityContext.FSGroup of the operator's pod
```release-note
Revert usage of non-root user (1000) on operator and builder pods FS.
```

Fix some OLM tests recently broken

---

cmd/manager/main.go
cmd/util/vfs-gen/main.go
cmd/util/vfs-gen/multifs/multidir.go
go.mod
go.sum
pkg/resources/resources_support.go

Ref #4326
The vfs-gen is mandatory for the CRD modifications to be detected when building (`make build`), else the changes are not deployed with a `make install`.
```release-note
chore(deps): revert vfs-gen removal
```

chore(deps): revert vfs-gen removal

---

.github/actions/e2e-install-upgrade/action.yml
.github/actions/e2e-install-upgrade/exec-tests.sh
.github/workflows/install.yml
e2e/install/upgrade/cli_upgrade_test.go
e2e/install/upgrade/files/yaml.yaml
e2e/install/upgrade/olm_upgrade_test.go
script/Makefile

```release-note
chore(ci): split upgrade from install
```

chore(e2e): split upgrade from install

---

e2e/install/upgrade/cli_upgrade_test.go
e2e/install/upgrade/olm_upgrade_test.go

Closes #4478
```release-note
fix(e2e): remove workaround pre 1.12.1
```

fix(e2e): remove workaround pre 1.12.1

---

e2e/support/util/dump.go

To facilitate analysis, there are situations when the last 50 lines is not enough.
```release-note
NONE
```

Increase log lines to 150 when dumping pod logs in e2e tests

---

docs/modules/ROOT/pages/architecture/traits.adoc
e2e/common/traits/camel_test.go
pkg/controller/integration/kits.go
pkg/resources/resources.go
pkg/trait/builder.go
pkg/trait/camel.go
pkg/trait/quarkus.go
pkg/trait/registry.go
pkg/trait/trait_types.go

With this func we have a lower level of granularity, giving the possibility to each trait to define when influences a build.
Closes #4511
```release-note
feat(trait): add InfluencesBuild() func
```

feat(trait): add InfluencesBuild() func

---

pkg/trait/camel.go

Closes #4504
```release-note
fix(trait): retrieve non cached version of generated Camel Catalog
```

fix(trait): retrieve non cached version of generated Camel Catalog

---

.gitignore
build/Dockerfile
docs/modules/ROOT/pages/contributing/remote-debugging.adoc
pkg/cmd/install.go
pkg/install/operator.go
script/Makefile

fixes #4513
Since the code refactoring for Camel-K 2, it is much harder to debug the operator, especially on MacOS. The goal of this task is to provide a way to remote debug the operator in order to be closer to the target environment and to be local OS agnostic.
* Add a debug mode in the makefile to add the required flags at build time to make the program compatible with the remote debugging
* Publish a specific image with delve installed in debug mode
* Configure the pod in such a way that the operator is launched through delve
* Add a doc describing how to use it
* Add MacOS files to git ignore 
```release-note
Allow to remote debug the Operator
```

Ref #4513: Allow to remote debug the Operator

---

docs/modules/ROOT/pages/installation/platform/kind.adoc

fixes #4236 
There is no documentation about how to install Camel-K on Kind with a local registry, we should add it.
* Add a new section to the existing doc related to Kind for the use case with a local registry
* Improve the existing code blocks to indicate that they are shell sources

Ref #4236: Describe how to install kind with a local registry

---

build/Dockerfile
config/rbac/operator-role.yaml
pkg/controller/build/build_pod.go
pkg/controller/build/monitor_pod.go
pkg/controller/catalog/initialize.go
pkg/install/operator.go
pkg/util/openshift/openshift.go
pkg/util/openshift/openshift_test.go

Ref #4476
For compatibility with S2I publish  strategy:
* Change default Dockerfile user from 1001 to 1001:0 with 775 permissions to be able the write with group 0
* Add builder pod security context compatible with OCP SecurityContextConstraint restricted-v2 (https://docs.openshift.com/container-platform/4.12/authentication/managing-security-context-constraints.html)
* Change Dockerfile S2I to user compatible with SecurityContextConstraint
* Add permission to get a namespace to operator to ensure SecurityContextConstraint labels in namespace are accessible
* Remove root FsGroup on operator as it is no longer needed
This has been tested on:
* OCP (CRC) with default project on routine/pod strategy
* OCP (CRC) with user created project on routine/pod strategy
* spectrum on routine/pod …

fix(core): Permissions on operator and builder pods (S2I compatibility)

---

script/cross_compile.sh

Closes #4526
```release-note
fix(ci): proper arch label
```

fix(ci): proper arch label

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/ROOT/partials/apis/kamelets-crds.adoc
script/gen_crd/gen-crd-api-config.json
script/gen_crd/gen-kamelets-crd-api-config.json
script/gen_crd/gen_crd_api.sh

Fix  [Camel K API doc has dead links to k8s ObjectMeta]( https://github.com/apache/camel-k/issues/4540) 
```release-note
NONE
```

Fix kubernetes version link in the generated api docs

---

e2e/support/util/dump.go
pkg/cmd/dump.go

Dump CamelCatalog at the end to avoid heavy log scrolling during failure analysis

chore: Change order of how resources get dumped

---

pkg/cmd/version.go

fix 
```
➜  /tmp ./kamel version -av
Unable to retrieve the operator version: CamelCatalog can't be found in openshift-operators namespace
Camel K Client 2.0.0-nightly
Git Commit: 612d1cd286616c58a75d6820e05c984c73dd6f7d
Unable to retrieve operator version: CamelCatalog can't be found in openshift-operators namespace
```
with global operator installation

Fix Unable to retrieve CamelCatalog with global installation

---

build/Dockerfile
pkg/controller/catalog/initialize.go
pkg/util/defaults/defaults.go
resources/camel-catalog-2.16.0.yaml
script/Makefile
script/update_docs.sh

As we now don't depend on the runtime directly, it makes sense to use a final release instead of a snapshot.
```release-note
chore: use fixed default runtime version
```

chore: use fixed default runtime version

---

pkg/cmd/run.go

Closes #4566
Closes #4543
```release-note
fix(cli): skip k8s lookup when dry-run
```

fix(cli): skip k8s lookup when dry-run

---

docs/modules/ROOT/pages/running/runtime-version.adoc

```release-note
chore(doc): detailed builder runtime info
```

chore(doc): detailed builder runtime info

---

e2e/commonwithcustominstall/operator_metrics_test.go
pkg/controller/build/build_controller.go
pkg/controller/build/initialize_pod.go
pkg/controller/build/initialize_routine.go
pkg/controller/build/monitor_routine.go
pkg/controller/build/schedule.go
pkg/controller/catalog/catalog_controller.go
pkg/controller/catalog/initialize.go
pkg/controller/integration/initialize.go
pkg/controller/integration/integration_controller.go
pkg/controller/integrationkit/initialize.go
pkg/controller/integrationkit/integrationkit_controller.go
pkg/controller/integrationplatform/initialize.go
pkg/controller/integrationplatform/integrationplatform_controller.go
pkg/controller/kamelet/initialize.go
pkg/controller/kamelet/kamelet_controller.go
pkg/controller/kameletbinding/initialize.go
pkg/controller/kameletbinding/kameletbinding_controller.go
pkg/controller/pipe/initialize.go
pkg/controller/pipe/pipe_controller.go

- Reduce amount of informational log events by using Debug level on events like "Reconciling ...", "Invoking action ..."
- Use Debug level for each "Reconciling ..." log event
- Use new "Initializing ..." Info level log event when a resource is initializing (used in metrics tests to verify metrics)
- Log error details on state transition to Phase "Error" for resources Integration, Build, KameletBinding and Pipe
```release-note
chore: Refactor operator logs
```

chore: Refactor operator logs

---

e2e/commonwithcustominstall/operator_metrics_test.go
pkg/controller/build/build_controller.go
pkg/controller/build/initialize_pod.go
pkg/controller/build/initialize_routine.go
pkg/controller/build/monitor_routine.go
pkg/controller/build/schedule.go
pkg/controller/catalog/catalog_controller.go
pkg/controller/catalog/initialize.go
pkg/controller/integration/initialize.go
pkg/controller/integration/integration_controller.go
pkg/controller/integrationkit/initialize.go
pkg/controller/integrationkit/integrationkit_controller.go
pkg/controller/integrationplatform/initialize.go
pkg/controller/integrationplatform/integrationplatform_controller.go
pkg/controller/kamelet/initialize.go
pkg/controller/kamelet/kamelet_controller.go
pkg/controller/kameletbinding/initialize.go
pkg/controller/kameletbinding/kameletbinding_controller.go
pkg/controller/pipe/initialize.go
pkg/controller/pipe/pipe_controller.go

- Reduce amount of informational log events by using Debug level on events like "Reconciling ...", "Invoking action ..."
- Use Debug level for each "Reconciling ..." log event
- Use new "Initializing ..." Info level log event when a resource is initializing (used in metrics tests to verify metrics)
- Log error details on state transition to Phase "Error" for resources Integration, Build, KameletBinding and Pipe
```release-note
chore: Refactor operator logs
```

[Backport-2.0.x] chore: Refactor operator logs (#4586)

---

.github/workflows/coverage.yml

Closes #4571
```release-note
fix(ci): run coverage only on golang code changes
```

fix(ci): run coverage only on golang code changes

---

.github/actions/e2e-install-olm/action.yml
.github/actions/e2e-install-upgrade/action.yml
cicd/tekton/kamel-run/0.1/kamel-run.yaml
cicd/tekton/kamel-run/0.1/tests/pre-apply-task-hook.sh

Closes https://github.com/apache/camel-k/issues/4597
```release-note
fix(ci): update CLIs URL
```

fix(ci): update CLIs URL 

---

config/crd/bases/camel.apache.org_builds.yaml
config/crd/bases/camel.apache.org_integrationkits.yaml
config/crd/bases/camel.apache.org_integrationplatforms.yaml
config/crd/bases/camel.apache.org_integrations.yaml
config/crd/bases/camel.apache.org_kameletbindings.yaml
config/crd/bases/camel.apache.org_pipes.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/builder.adoc
e2e/common/traits/builder_test.go
helm/camel-k/crds/crd-build.yaml
helm/camel-k/crds/crd-integration-kit.yaml
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/common_types_support.go
pkg/apis/camel/v1/common_types_support_test.go
pkg/apis/camel/v1/maven_types.go
pkg/apis/camel/v1/trait/builder.go
pkg/apis/camel/v1/zz_generated.deepcopy.go
pkg/builder/project.go
pkg/client/camel/applyconfiguration/camel/v1/mavenbuildspec.go
pkg/client/camel/applyconfiguration/camel/v1/mavenspec.go
pkg/cmd/install.go
pkg/trait/builder.go
pkg/trait/builder_test.go
pkg/util/maven/maven_project.go
pkg/util/maven/maven_project_test.go
pkg/util/maven/maven_types.go
resources/traits.yaml

Ref #4560
* Add builder.maven-profile property referencing a secret or a configmap : `[configmap|secret]:name[/key]`
* Inject the given profile into the pom.xml generated in the project
* Some refactoring on configmap/secret decoding from cli
Example: 
* Creates a secret or a configmap: `kubectl create secret generic maven-profile-owasp --from-file=owasp-profile.xml`
* Use it in the builder trait: `-t builder.maven-profile=secret:maven-profile-owasp/owasp-profile.xml`
```release-note
Add maven profile to Integration in builder trait as the maven-profile property referencing a secret or a configmap
```

feat(trait): Add maven profile to Integration in builder trait

---

docs/modules/ROOT/pages/troubleshooting/known-issues.adoc

Ref #4569
```release-note
NONE
```

fix(doc): Add openshift builder image re-creation as known issue

---

.github/actions/e2e-common/exec-tests.sh
.github/actions/kamel-prepare-env/action.yml
pkg/builder/buildah.go
pkg/util/defaults/defaults.go
script/Makefile

Will be required to run Camel Quarkus 3/Camel 4 applications.
```release-note
chore(ci): default JDK 17 base image
```

chore(ci): default JDK 17 base image

---

docs/modules/ROOT/pages/configuration/dependencies.adoc
pkg/metadata/metadata_dependencies_test.go
pkg/metadata/metadata_http_test.go
release.adoc

Closes #4609 
```release-note
fix: use non deprecated components
```

fix: use non deprecated components

---

e2e/common/config/files/TimerKameletIntegrationConfiguration.java
e2e/common/config/files/TimerKameletIntegrationNamedConfiguration.java
e2e/common/config/files/timer-kamelet-integration-inlined-configuration.yaml
e2e/common/config/files/timer-kamelet-integration-parameters-configuration.yaml
e2e/common/config/kamelet_config_test.go
e2e/common/config/pipe_config_test.go
e2e/support/test_support.go

Strengthen the tests on configuration via secret/configmap to define what type of configurations actually works.
* Test of Integrations using kamelets and properties/secrets
* Test of Pipes using kamelets and properties/secrets
```release-note
chore(e2e): Test on kamelets configurations
```

chore(e2e): Test on kamelets configurations

---

.github/workflows/security.yaml

Ref #3753 
Adding the [govulncheck](https://go.dev/blog/govulncheck) tool to the project CI will provides more visibility on vulnerabilities of the golang code.
The govulncheck looks into the dependencies but also [how they are used in the code](https://brandur.org/fragments/govulncheck-ci). As a result, it has been activated for any change on not only in go.mod/go.sum files but also on any golang file (*.go) changed.
It is active on PRs and main/release branches changes.
For now I decided not to use the [recently created github action](https://github.com/golang/govulncheck-action/tree/master) as I plan to see if other security tools  like [gosec](https://github.com/securego/gosec) could be added.
```release-note
feat(ci): Add govulncheck as ci workflow
```

feat(ci): Add govulncheck as ci workflow

---

pkg/cmd/promote.go
pkg/cmd/promote_test.go

This PR addresses a few enhancements which are helping GitOps or in general deployment operations. They are following up the some limitations founds in the proposed [Camel K GitOps strategy](https://camel.apache.org/blog/2023/07/camel-k-gitops/).
First of all, we get rid of the destination checks when in dry-run mode. Second, we introduce a simple flag which helps putting in place any unopinionated deployment strategy, for example:
```
$ kamel promote test -i --to test
10.110.251.124/default/camel-k-kit-cj1ra5e9j3ks738a7bbg@sha256:99835a5da746fc3d7f96d0ae50c64df0e29eb3e8d131e61bfdfd617fdaa078ba
```
Finally we allow to specify the operator ID tenant which must be used to take care of the promoted integration, ie `kamel promote test -x my-production-operator-id --to test`
Closes …

feat(cmd): improve `kamel promote`

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/cron.adoc
pkg/apis/camel/v1/trait/cron.go
resources/traits.yaml

Fix doc related to when the timer is materialized as a CronJOb
```release-note
NONE
```

Fix cron trait doc, timer usage is missing information

---

pkg/trait/builder.go
pkg/trait/builder_test.go

Ref #4558
Adding a custom task with the `builder` trait result in an unclear error message and cause.
* Add an IntegrationKit Status Condition Error when a custom builder task is specified on a integration platform defined with `routine` build strategy
* Some refactoring to avoid adding tasks to the pipeline when the error fires (else it results in a panic error later)
```release-note
feat(trait): Fail IntegrationKit when custom task defined with build strategy routine
```

feat(trait): Fail IntegrationKit when custom task defined with build strategy routine

---

.github/actions/e2e-telemetry/action.yml
.github/workflows/common.yml
.github/workflows/coverage.yml
.github/workflows/install.yml

* Upgrade telemetry otlp collector version in telemetry workflow
* Fix not up to date actions in some ci workflows:
* github action setup-go@v4
* github action checkout@v3
```release-note
NONE
```

chore(ci): Updates of otlp collector and some github actions

---

addons/vault/aws/aws_secrets_manager.go
addons/vault/azure/azure_key_vault.go
addons/vault/gcp/gcp_secret_manager.go
addons/vault/hashicorp/hashicorp_vault.go
pkg/apis/camel/v1/common_types.go
pkg/resources/resources.go
pkg/trait/jolokia.go
pkg/trait/knative.go
pkg/trait/prometheus.go

This PR will address the design available at [next runtime release](https://github.com/apache/camel-k-runtime/pull/1040).
This PR is different from original #4456 because we don't need to explicitly check for the usage of the capability. There is already a mechanism in the trait that will take care to include all the dependencies.
Once the runtime is available we can remove the dependencies which are now provided in the same trait.
Ref #4166
```release-note
feat(trait): prepare to remove runtime dependencies
```

feat(trait): prepare to remove runtime dependencies

---

pkg/apis/camel/v1/trait/route.go
pkg/trait/route.go
pkg/trait/route_test.go

- Added route annotations implementation
- Added unit tests
- Added documentation
_CLI parameter usage example for clarity:_
`-t "route.annotations.'haproxy.router.openshift.io/balance'=true"`
_This can be repeated to add multiple annotations_
```release-note
feat: added annotations support for route trait
```

feat: added annotations support for route trait

---

cicd/tekton/kamel-run/0.1/support/camel-k-tekton.yaml

Closes #4666
Add permission to list the `camelcatalogs` CR to the Role linked to camel-k-tekton SA.
```release-note
feat(cicd): add permission to list the `camelcatalogs` CR for Tekton
```

fix(cicd): Add list camelcatalog permission in tekton SA

---

go.mod
go.sum
pkg/install/openshift.go

```release-note
chore(deps): bump openshift api
```

chore(deps): bump openshift api

---

config/rbac/operator-role.yaml
docs/modules/ROOT/pages/contributing/developers.adoc
helm/camel-k/templates/operator-cluster-roles.yaml
helm/camel-k/templates/operator-role.yaml

```release-note
Fix missing roles in Helm and update helm documentation
```

Fix: Helm roles and doc (2.0.x)

---

release.adoc
script/git_tag.sh

```release-note
fix(doc): multi arch build notice
```

fix(doc): multi arch build notice

---

e2e/common/misc/maven_repository_test.go
e2e/support/test_support.go
pkg/builder/quarkus.go

Fixes #4608 
Use maven repositories from `kamel run --maven-repository` command flag also as plugin repository in the generated maven project.
**Note:** This `--maven-repository` flag values from `run` command are not added in the generated settings.xml file but embedded in the pom.xml generated file.
This flag is translated in integration CR as:
```
spec:
repositories:
- https://repository.apache.org/content/groups/snapshots-group@id=apache@snapshots@noreleases
```
```release-note
fix(cli): Use maven repository CLI flag for plugins
```

fix(cli): Use maven repository CLI flag for plugins

---

config/crd/bases/camel.apache.org_integrationplatforms.yaml
config/crd/bases/camel.apache.org_integrations.yaml
config/crd/bases/camel.apache.org_kameletbindings.yaml
config/crd/bases/camel.apache.org_pipes.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/knative-service.adoc
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/trait/knative_service.go
pkg/apis/camel/v1/trait/zz_generated.deepcopy.go
pkg/trait/knative_service.go
pkg/trait/knative_service_test.go
resources/traits.yaml

- Added route annotations implementation
- Added unit tests
- Added documentation
_CLI parameter usage example for clarity:_
`-t "knaive-service.annotations.'haproxy.router.openshift.io/balance'=true"`
_This can be repeated to add multiple annotations_
```release-note
feat: added annotations support for knative service trait
```

feat: knative service trait annotation support

---

pkg/cmd/version.go
pkg/controller/catalog/initialize.go

Fix https://github.com/apache/camel-k/issues/4715
* When there is a catalog build error, show in the operator log
* Only prints catalog information when it's available
In case there is an error when parsing the camelcatalog version, the camelcatalog controller will create a new one.
```release-note
NONE
```

Fix operator check of the catalog

---

e2e/support/test_support.go

Closes #4754 
Add into test_support init the setLogger().
```release-note
NONE
```

fix(e2e): init controller-runtime log.SetLogger()

---

e2e/common/config/files/TimerKameletIntegrationConfiguration01.java
e2e/common/config/files/TimerKameletIntegrationConfiguration03.java
e2e/common/config/files/TimerKameletIntegrationConfiguration04.java
e2e/common/config/files/TimerKameletIntegrationNamedConfiguration.java
e2e/common/config/files/TimerKameletIntegrationNamedConfiguration05.java
e2e/common/config/files/TimerKameletIntegrationNamedConfiguration06.java
e2e/common/config/files/TimerKameletIntegrationNamedConfiguration07.java
e2e/common/config/files/TimerKameletIntegrationNamedConfiguration08.java
e2e/common/config/files/timer-kamelet-integration-inlined-configuration-01.yaml
e2e/common/config/files/timer-kamelet-integration-parameters-configuration-02.yaml
e2e/common/config/files/timer-kamelet-integration-parameters-configuration-03.yaml
e2e/common/config/files/timer-kamelet-integration-parameters-configuration-04.yaml
e2e/common/config/kamelet_config_test.go

ref #4750
Remove duplicate usage of "my-own-timer-source" kamelet.
```release-note
fix(e2e): Fix E2E test using kamelet my-own-timer-source
```

fix(e2e): Fix E2E test using kamelet my-own-timer-source

---

config/manager/operator-deployment.yaml
e2e/install/cli/install_test.go
e2e/support/test_support.go
helm/camel-k/templates/operator.yaml
pkg/install/operator.go
pkg/trait/container.go
pkg/util/kubernetes/security.go

Closes #4424
Add the valid openshift security contexts, as done with the builder pod,  to :
* operator pod
* integration pod
```release-note
Add the valid openshift security context to integration and operator pods
```

feat(core): Remove Openshift security warning message

---

e2e/common/config/files/TimerKameletIntegrationConfiguration09.java
e2e/common/config/kamelet_config_test.go

Ref #4750
Refactor config e2e test for kamelets with a labeled secret.
Note : follow-up on https://github.com/apache/camel-k/pull/4753
```release-note
fix(e2e): Kamelets Default config as a labeled secret
```

fix(e2e): Kamelets Default config as a labeled secret

---

pkg/cmd/run.go

Closes #4770 
Init the setLogger() for CLI's --dev mode.
Note: same issue as #4754 
```release-note
fix(cli): dev mode init controller-runtime log.SetLogger()
```

fix(cli): dev mode init controller-runtime log.SetLogger()

---

e2e/common/misc/maven_repository_test.go

Let's fix this as the original PR containing this change could take long before being merged.
Closes #4774
```release-note
fix(e2e): existing dependency
```

fix(e2e): existing dependency

---

docs/modules/ROOT/nav-end.adoc
docs/modules/ROOT/pages/troubleshooting/known-issues.adoc
docs/modules/ROOT/pages/troubleshooting/troubleshooting.adoc
e2e/common/support/startup_test.go
e2e/commonwithcustominstall/builder_test.go
e2e/commonwithcustominstall/catalog_builder_test.go
e2e/install/cli/global_test.go
e2e/install/cli/install_test.go
e2e/knative/support/startup_test.go
pkg/apis/camel/v1/integration_types_support.go
pkg/apis/camel/v1/integrationplatform_types.go
pkg/controller/integrationkit/initialize.go
pkg/controller/integrationplatform/create.go
pkg/controller/integrationplatform/initialize.go
pkg/controller/integrationplatform/monitor.go
pkg/resources/resources.go

This PR will introduce a monitor check to make sure that an IntegrationPlatform registry exists (if not on Openshift). This is an improvement to avoid common mistakes with missing registry.
The PR also make the IntegrationKit failure to bubble up into the Integration conditions in order to simplify the troubleshoot of a failing Integration.
Closes https://github.com/apache/camel-k/issues/4647
```release-note
feat(ctrl): verify existence of registry
```

feat(ctrl): verify existence of registry

---

addons/vault/azure/azure_key_vault.go
addons/vault/azure/azure_key_vault_test.go
docs/modules/traits/pages/aws-secrets-manager.adoc
docs/modules/traits/pages/azure-key-vault.adoc
resources/traits.yaml

Related to #4743 
```release-note
Implementing the requested feature in Azure Key Vault addon
```

Kamelet - Inject secret in Vaults - Azure Key Vault

---

addons/vault/hashicorp/hashicorp_vault.go
addons/vault/hashicorp/hashicorp_vault_test.go
docs/modules/traits/pages/aws-secrets-manager.adoc
docs/modules/traits/pages/hashicorp-vault.adoc
resources/traits.yaml

Fixes #4743 
```release-note
Implementing the requested feature in Hashicorp Vault addon
```
For GCP there is nothing to do since we are pointing a file containing the service account key.

Kamelet - Inject secret in Vaults - Hashicorp Vault

---

docs/modules/ROOT/nav-end.adoc
docs/modules/ROOT/pages/contributing/local-development.adoc
docs/modules/ROOT/pages/contributing/local-execution.adoc

This was removed as we temporary introduced the dynamic builder. Now that is gone, the local execution can be still a way to debug the operator.
Ref #4513
```release-note
chore(doc): bring back support for local operator execution
```

chore(doc): bring back support for local operator execution

---

config/crd/bases/camel.apache.org_pipes.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/pipe_types.go
pkg/controller/pipe/initialize.go
pkg/controller/pipe/integration.go
pkg/controller/pipe/monitor.go
resources/traits.yaml

Closes #4780
```release-note
fix(api): deprecate .spec.integration Pipe
```

fix(api): deprecate .spec.integration Pipe

---

pkg/apis/camel/v1/camelcatalog_types_support.go
pkg/cmd/version.go
pkg/cmd/version_test.go
pkg/trait/builder.go
pkg/util/jib/configuration.go
pkg/util/jib/configuration_test.go

Ref #4703
Extracted jib plugin versions to camel-k-runtime:
* use camelcatalog CR .spec.runtime.metadata values
* set default values for catalog backward compatibility
NOTE:
Linked to: apache/camel-k-runtime#1096
```release-note
feat(core): Move jib plugins versions to camelcatalog from camel-k-runtime
```

feat(core): Move jib plugins versions to camelcatalog

---

e2e/common/misc/files/InvalidJava.java
e2e/common/misc/integration_fail_test.go

Ref #4781 
Added recovery in tests for:
* Integration with invalid dependencies
* Integration with unknown dependencies
* Integration with unknown component in route
* Integration with route compilation error
```release-note
e2e(ctrl): Add reconciliation recovery tests
```

e2e(ctrl): Add reconciliation recovery tests

---

config/crd/bases/camel.apache.org_integrationkits.yaml
config/crd/bases/camel.apache.org_integrationplatforms.yaml
config/crd/bases/camel.apache.org_integrations.yaml
config/crd/bases/camel.apache.org_kameletbindings.yaml
config/crd/bases/camel.apache.org_pipes.yaml
docs/modules/ROOT/pages/architecture/incremental-image.adoc
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/builder.adoc
e2e/commonwithcustominstall/incremental_build_test.go
helm/camel-k/crds/crd-integration-kit.yaml
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/trait/builder.go
pkg/apis/camel/v1/trait/zz_generated.deepcopy.go
pkg/builder/image.go
pkg/trait/builder.go
pkg/trait/quarkus.go
pkg/trait/quarkus_test.go
resources/traits.yaml

We introduce an option to disable the incremental image option. Not advisable, but still some feature some user may require.
Closes #3011
```release-note
feat(trait): disable incremental image option
```

feat(trait): disable incremental image option

---

.github/workflows/coverage.yml

Let's avoid adding many messages when no useful info.
```release-note
chore(ci): no coverage message when coverage unchanged
```

chore(ci): no coverage message when coverage unchanged

---

pkg/controller/integration/monitor.go
pkg/trait/health.go
pkg/trait/jvm.go

When the integration is in Error with the Kit condition in error, then if the integration kit referenced is still in error then finish the reconciliation process without any change to the integration.
Fix the health trait to avoid panic errors.
```release-note
Change reconciliation of integration in error
```

fix(ctrl): Change reconciliation of int in error

---

.gitignore
docs/modules/ROOT/pages/contributing/e2e.adoc
docs/modules/ROOT/pages/installation/advanced/advanced.adoc
e2e/support/test_support.go
pkg/cmd/install.go
pkg/cmd/install_test.go

Added `build-catalog-tool-timeout` parameter to the `install` command.
Added `CAMEL_K_BUILD_CATALOG_TOOL_TIMEOUT` to e2e tests scripts to leverage the new install parameter. 
Updated doc.
Small addition to .gitignore
This is useful in environment where the default timeout of 2 minutes is not sufficient.
```release-note
NONE
```

Added build-catalog-tool-timeout parameter to install command.

---

pkg/trait/route.go

- removed unnecessary defaul value for Host in Route trait.
_As we are  currently not setting a specific default value for Host, this line is unnecessary and could cause problems if left in._
```release-note
NONE
```

fix: removed unnecessary defaul value in route trait

---

.github/actions/kamel-prepare-env/action.yml
config/crd/bases/camel.apache.org_builds.yaml
config/crd/bases/camel.apache.org_integrationkits.yaml
config/crd/bases/camel.apache.org_integrationplatforms.yaml
config/crd/bases/camel.apache.org_integrations.yaml
config/crd/bases/camel.apache.org_kameletbindings.yaml
config/crd/bases/camel.apache.org_pipes.yaml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/builder.adoc
e2e/commonwithcustominstall/incremental_build_test.go
helm/camel-k/crds/crd-build.yaml
helm/camel-k/crds/crd-integration-kit.yaml
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/build_types.go
pkg/apis/camel/v1/integrationkit_types.go
pkg/apis/camel/v1/trait/builder.go
pkg/builder/image.go
pkg/builder/jib.go
pkg/builder/spectrum.go
pkg/client/camel/applyconfiguration/camel/v1/buildstatus.go
pkg/client/camel/applyconfiguration/camel/v1/integrationkitstatus.go
pkg/controller/integrationkit/build.go
pkg/trait/builder.go
resources/traits.yaml

With this PR we set the root image from which an incremental kit has started. We use this information to select properly the kit to inherit, making sure we start a new hierarchy if the base image has changed.
The base image can be easily now be overridden using `builder.base-image` trait property.
This would be the result making changes to the base image on the fly.
```
k get ik
NAME                       ALIAS   PHASE   TYPE       LAYOUT     IMAGE                                                                                                                          ROOT
kit-ckofr2pbtegs738g3mog           Ready   platform   fast-jar   10.102.33.4/default/camel-k-kit-ckofr2pbtegs738g3mog@sha256:bab614cad6e0daa2e803fe9cbf7c890ef3481b00437d69cd631c4e5914dcc7e0   eclipse-temurin:17 …
```

feat(build): add root image info

---

docs/modules/ROOT/pages/contributing/e2e.adoc

As a follow up to #4821 I have opened this with the doc improvements useful for main.
```release-note
NONE
```

chore: improved e2e tests documentation.

---

.github/actions/automatic-updates/action.yml
.github/actions/kamel-prepare-env/action.yml
.github/actions/release-nightly/action.yml
.github/workflows/coverage.yml
.github/workflows/nightly-automatic-updates.yml
.github/workflows/nightly-release.yml
.github/workflows/security.yaml
.github/workflows/validate.yml

Closes #4641
Ensure we use the latest minor version available of golang in every workflow.
Nothing more need to be done. I checked and all of the workflow (expect the "stale" workflow and it does not need golang) define golang version either directly either through the action `kamel-prepare-env` called in the workflow pipeline.
```release-note
chore(ci): Use latest minor version of golang in ci workflows
```

chore(ci): Use latest minor version of golang in ci workflows

---

examples/rest/routes-rest.js
examples/saga/Flight.java
examples/saga/Payment.java
examples/saga/Train.java
examples/saga/lra-coordinator.yaml

Examples `saga` and `route` contain obsolete code - RestDefinition doesn't contain route() since Camel 3.16; updated via [Camel migration guide ](https://camel.apache.org/manual/camel-3x-upgrade-guide-3_16.html#_rest_dsl).

Remove route() from examples

---

docs/modules/ROOT/pages/configuration/runtime-config.adoc
docs/modules/ROOT/pages/configuration/runtime-resources.adoc

Ref #4853 
*Note*
To be backported on 2.x.
```release-note
NONE
```

fix(doc): Remove ambiguous local files usage on config/resources

---

pkg/trait/mount.go

```release-note
chore(trait): execute mount only when deploying
```

chore(trait): execute mount only when deploying

---

.github/actions/kamel-config-cluster-kind/action.yml
e2e/install/kustomize/operator_test.go
install/setup/kustomization.yaml
pkg/util/registry/kep_1755.go

Change kubernetes CLI usage to actually get the configmap `local-registry-hosting` in namespace `kube-public` for kind action registry configuration from KEP-1755.
```release-note
fix(core): Access configmap from another namespace for KEP-1755
```

fix(core): Access configmap from another namespace for KEP-1755

---

pkg/builder/runtime_support.go

Closes #4892
```release-note
fix(build): use maven context arguments
```

fix(build): use maven context arguments

---

config/crd/bases/camel.apache.org_integrationplatforms.yaml
helm/camel-k/crds/crd-integration-platform.yaml
pkg/apis/camel/v1/integrationplatform_types.go

We need to deprecate IP as it is too generic and collide with many other CRs.
```release-note
chore(api): introduce itp shortname
```

chore(api): introduce itp shortname

---

e2e/common/config/config_reload_test.go

Fix #4902 
* Fix the default hotreload for secrets
* Randomize the integration names
Note: For some unknown reason the test was passing before enforcing the default value to `false` in CRD.
```release-note
NONE
```

fix(e2e): HotReload tests should not reload by default

---

e2e/common/config/config_test.go
e2e/common/config/files/property-secret-route.groovy

Ref #4841 
Add e2e test and some additional cleaning.
Note: should be updated when https://issues.apache.org/jira/browse/CAMEL-20054 is available via Camel-K-Runtime.
```release-note
NONE
```

chore(e2e): Regression test on referenced secret(/cm) properties

---

.github/workflows/validate.yml
cmd/util/json-schema-gen/main.go

Add validation on more path code changes
```release-note
NONE
```

fix(ci): Remove golint warning for imports

---

pkg/util/camel/camel_runtime_catalog.go
pkg/util/camel/camel_runtime_catalog_test.go

- Support URL query parameters when resolving components by given scheme
- Do not resolve URLs that use parameter placeholder as a scheme
- Properly extract scheme from URL that has query parameters
Fixes #4916 
```release-note
fix: Improve component resolver
```

fix(#4916): Improve component resolver

---

e2e/common/traits/health_test.go

https://github.com/apache/camel-k/issues/3997

test(health): #3997 structured conditions for scaled integrations

---

e2e/common/cli/dev_mode_test.go

Randomize integration names in dev mode e2e tests to avoid concurrent write errors with CLI runs.
```release-note
chore(e2e): Randomize integration name in dev mode e2e tests
```

chore(e2e): Dev mode flaky test randomize name

---

pkg/trait/mount.go

```release-note
chore(trait): run mount only when necessary
```

chore(trait): run mount only when necessary

---

script/check_crd_api_support.sh

Closes #4929 
kubectl and oc CLI answers with different result to explain command:
```bash
$"kubectl" explain customresourcedefinitions | grep VERSION | awk '{print $2}'
v1
$ "oc" explain customresourcedefinitions | grep VERSION | awk '{print $2}'
apiextensions.k8s.io/v1
```
Root cause:
```bash
$ kubectl explain customresourcedefinitions
GROUP:      apiextensions.k8s.io
KIND:       CustomResourceDefinition
VERSION:    v1
$ oc explain customresourcedefinitions
KIND:     CustomResourceDefinition
VERSION:  apiextensions.k8s.io/v1
```
```release-note
fix(e2e): Error in check crd support script
```

fix(e2e): Error in check crd support script

---

java/crds/pom.xml

Add `sundrio` to generate builder pattern for the model classes of the generated CRD.
With the upcoming version of `kubernetes-client-bom-with-deps` we should be able to remove the explicit versions of `sundrio` and `lombok` too.

[java] Add sundrio to generate builders

---

pkg/trait/container.go
pkg/trait/container_test.go
pkg/util/test/client.go

In global mode the integration pod securityContext needs to be generated from the integration namespace.
Test done on global/non-global operator deployment on OCP 4.12.13
```release-note
fix(core): Openshift securityContext on global operator
```

Fix(core): Openshift securityContext on global operator

---

script/check_crd_api_support.sh

Backport fix #4930 
```release-note
fix(e2e): Error in check crd support script
```

[Backport 2.1.x] fix(e2e): Error in check crd support script

---

e2e/install/kustomize/setup_test.go
e2e/install/upgrade/helm_upgrade_test.go
e2e/support/test_support.go
helm/camel-k/README.md

Ref #4923 
Add helm upgrade test using manual upgrade of CRDs and update the documentation.
```release-note
fix: Helm upgrade procedure with CRD management
```

fix(e2e): Upgrade helm procedure test

---

e2e/yaks/common/knative-sinkbinding-http/sinkbinding.feature

Change the default polling configuration to the most commonly used one in other yaks feature files to fix the recurring flaky failures of this test.
See: https://github.com/apache/camel-k/actions/runs/7047787985/job/19182852523?pr=4946
```release-note
fix(e2e): Set default configuration knative http yaks test
```

fix(e2e): Set default configuration knative http yaks test

---

.github/actions/kamel-config-cluster-kind/action.yml

Rollback kind image change done in [#4946](https://github.com/apache/camel-k/pull/4946) that might be the root cause for custom operator e2e test failure on metrics.
```release-note
NONE
```

fix(ci): Rollback kind image

---

e2e/install/upgrade/helm_upgrade_test.go

Ref #4923
Restricting helm upgrade test to main branch as it requires the last release chart.
```release-note
fix(e2e): Execute helm upgrade test only on main branch
```

fix(e2e): Execute helm upgrade test only on main branch

---

pkg/trait/builder.go
pkg/trait/builder_test.go

Closes #4956
```release-note
fix(build): don't override user provided resources
```

fix(build): don't override user provided resources

---

e2e/install/kustomize/setup_test.go
e2e/install/upgrade/helm_upgrade_test.go
e2e/support/test_support.go
helm/camel-k/README.md

Backport fix https://github.com/apache/camel-k/pull/4927
```release-note
fix: Helm upgrade procedure with CRD management
```

[Backport 2.1.x]: Upgrade helm procedure test

---

pkg/util/bindings/catalog.go
pkg/util/bindings/catalog_test.go

- Allow explicit references to default Kamelets in operator namespace
- Keep check on cross-namespace reference for other resources (e.g. Knative Broker)
- Keep raising cross-namespace check errors for Kamelet references to other user namespaces
```release-note
fix: Pipe cross-namespace check for Kamelets in operator namespace
```

fix(#4961): Improve cross-namespace check for Kamelet refs

---

docs/modules/ROOT/pages/index.adoc

it is fixing camel-website build which had error:
```
➤ YN0000: [build:antora  ] [build:antora-perf] [09:37:43.441] WARN
(asciidoctor):
➤ YN0000: [build:antora  ] [build:antora-perf]     file:
docs/modules/ROOT/pages/index.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source:
https://github.com/apache/camel-k.git (refname: main, start path: docs)
➤ YN0000: [build:antora  ] [build:antora-perf]     msg: {
➤ YN0000: [build:antora  ] [build:antora-perf]       "msg":
"jsonpathTable block macro must follow a table, not a paragraph",
➤ YN0000: [build:antora  ] [build:antora-perf]       "useId": 0,
➤ YN0000: [build:antora  ] [build:antora-perf]
"@djencks/asciidoctor-antora-indexer": "indexTable"
➤ YN0000: [build:antora  ] [build:antora-perf]     }
```
relates to #4886 …

Remove index table which is not refering to any table

---

.github/actions/kamel-config-cluster-kind/action.yml

Ref #4954
Only upgrade kind-action to 2.0.2
```release-note
chore(ci): Upgrade kind-action to 2.0.2
```

chore(ci): Upgrade kind-action to 2.0.2

---

pkg/util/camel/camel_runtime_catalog.go
pkg/util/camel/camel_runtime_catalog_test.go

Fix https://github.com/apache/camel-k/issues/4972
```release-note
Enhancement of the dependency calculation for dynamic endpoints
```

Fix: Fail to run route with toD #4972

---

e2e/yaks/common/apache-kamelet-catalog/kamelet.feature
e2e/yaks/common/kamelet-beans/kamelet.feature
e2e/yaks/common/kamelet-binding-autoload/kamelet-autoload.feature
e2e/yaks/common/kamelet-binding-broker/kamelet.feature
e2e/yaks/common/kamelet-binding-http/kamelet.feature
e2e/yaks/common/kamelet-binding-property-encoding/properties.feature
e2e/yaks/common/kamelet-binding/kamelet.feature
e2e/yaks/common/kamelet-data-types/kamelet-data-types.feature
e2e/yaks/common/kamelet-no-properties/kamelet-no-props.feature
e2e/yaks/common/kamelet-steps/steps-binding.feature
e2e/yaks/common/kamelet/kamelet.feature
e2e/yaks/common/knative-broker/knative-broker.feature
e2e/yaks/common/knative-sinkbinding/sinkbinding.feature

- Make sure to remove resources after test
- Avoids reconciling of leftover resources in Camel K operator logs
- Either use auto removal or explicitly remove resources

chore: Improve YAKS E2E tests

---

pkg/cmd/run.go
pkg/util/kubernetes/log/annotation_scraper.go
pkg/util/kubernetes/log/pod_scraper.go
pkg/util/kubernetes/portforward.go
pkg/util/log/log.go

Closes #4891
```release-note
fix(cmd): move log in init to catch all options
```

fix(cmd): move log in init to catch all options

---

e2e/commonwithcustominstall/builder_test.go
pkg/controller/integrationkit/build.go

Ref #4988 
```release-note
fix(core): Fix tooling image on multi-arch
```

fix(core): Fix tooling image on multi-arch

---

.github/workflows/coverage.yml

This fixes a minor GitHub Actions workflow injection vulnerability by sanitizing the branch name from the PR head.
I'm just making a PR because most risk is mitigated as the workflow does not use secrets and the `GITHUB_TOKEN` permissions are restricted to `pull-requests: write` and `issues: write`. The worst an attacker could do is modify other PR descriptions, titles, mess with issues - a nuisance but not a supply chain attack.
```release-note
NONE
```

fix(ci): Sanitize PR head.ref

---

.github/actions/e2e-build/action.yml
.github/actions/release-nightly/action.yml

```release-note
fix(ci): golang caching is already part of go actions
```

fix(ci): golang caching is already part of go actions

---

pkg/builder/jib.go
pkg/builder/spectrum.go
pkg/util/jib/configuration.go
pkg/util/registry/registry.go
pkg/util/registry/registry_test.go

Ref #5007 
Manage registry secret for Jib strategy in a similar way that spectrum strategy does.
```release-note
fix(#5007): Jib publish strategy registry secret
```

fix(#5007): Jib publish strategy registry secret

---

pkg/controller/integration/monitor.go
pkg/controller/integration/monitor_cronjob.go
pkg/controller/integration/monitor_deployment.go
pkg/controller/integration/monitor_knative.go

When the user uses a startup probe, the Integration won't turn as running until the condition is reached
Closes #4977
```release-note
fix(ctrl): monitor Pod ready condition
```

fix(ctrl): monitor Pod ready condition

---

pkg/util/dsl/flow.go
pkg/util/dsl/flow_test.go

There was a similar issue before:
https://github.com/apache/camel-k/issues/2616
However, in the new CRD version(v1), this issue has not been resolved.
After operator reads and regenerates yaml from CRD, there is still a problem with scientific notation. This issue is currently fixed
```release-note
NONE
```

fix(trait) Fixed a scientific notation issue with camel when generating yaml

---

.github/dependabot.yml
java/crds/pom.xml

Cleanup PR, to use the new Fabric8 BOM to get the aligned versions of `sundrio` and `lombok`.
I noticed that fabric8 was not getting updated and added an entry to dependabot.

Bump Fabric8, use the BOM and dependabot

---

docs/modules/ROOT/pages/installation/registry/dockerhub.adoc
pkg/util/registry/registry.go
pkg/util/registry/registry_test.go

Ref #5017 
Ref #5007 
* change default secret generation from CLI for Jib compatibility
* update documentation with configuration for docker hub registry
```release-note
fix(core): Fix docker hub registry configuration
```

fix(core): Fix docker hub registry configuration

---

pkg/builder/quarkus.go
script/camel-k-runtime-archetype/pom.xml

- Make sure to support factory finder service discovery resource paths for data type transformers in different Camel runtimes
- Enables Pipes to use data type transformers that get resolved during runtime with service discovery
- Camel 3.x uses `META-INF/services/org/apache/camel/datatype/converter/*`
- Camel 4.0 uses `META-INF/services/org/apache/camel/datatype/transformer/*`
- Camel 4.2 uses `META-INF/services/org/apache/camel/transformer/*`
```release-note
fix(#5047): Update Quarkus service discovery setting for data type transformer
```

fix(#5047): Update Quarkus service discovery setting for data type transformer

---

pkg/util/bindings/kamelet.go
pkg/util/bindings/kamelet_test.go

- Allows data type references in Pipes to use component scheme as a prefix in the transformer name (e.g. format=aws2-s3:application-cloudevents)
- This is in addition to specifying "scheme" and "format" properties on the data type reference
```release-note
fix(#5048): Support component scheme prefix in data type references
```

fix(#5048): Support component scheme prefix in data type references

---

pkg/trait/quarkus.go
pkg/trait/quarkus_test.go

Makes sure JVM mode is executed before native mode.
fixes: #5001
```release-note
fix(#5001): Execute Quarkus JVM buildMode before native buildMode
```

fix(#5001): Execute Quarkus JVM buildMode before native buildMode

---

docs/modules/ROOT/pages/languages/languages.adoc

These links are currently broken and prevent successful website builds.
Docs: https://docs.antora.org/antora/latest/page/page-links/#toke

fix: use relative paths

---

pkg/trait/camel.go

- When new runtime version is used on integration the camel trait creates the catalog if it does not exist already
- Use proper catalog namespace to verify that the catalog resource has been created during the camel trait execution
Fixes #4776 
```release-note
NONE
```

fix(#4776): Fix catalog loading in camel trait

---

.github/actions/e2e-build/action.yml
.github/actions/java-build/action.yml
.github/actions/kamel-prepare-env/action.yml
.github/actions/release-nightly/action.yml
.github/workflows/build.yml
.github/workflows/builder.yml
.github/workflows/comment-pr.yaml
.github/workflows/common.yml
.github/workflows/install.yml
.github/workflows/java.yml
.github/workflows/knative.yml
.github/workflows/native.yml
.github/workflows/nightly-automatic-updates.yml
.github/workflows/nightly-latest-runtime.yml
.github/workflows/nightly-native-test.yml
.github/workflows/nightly-release.yml
.github/workflows/security.yaml
.github/workflows/stale.yaml
.github/workflows/telemetry.yml
.github/workflows/validate.yml

Global upgrade of following actions:
* actions/setup-java v3 -> v4
* actions/upload-artifact v2 -> v4
* actions/github-script v3 -> v7
* actions/checkout v3 -> v4
* docker/login-action v2 -> v3
* docker/setup-qemu-action v2 -> v3
* actions/stale v3 -> v9
```release-note
chore(ci): Upgrade github ci  actions
```

chore(ci): Upgrade github ci  actions

---

pkg/apis/camel/v1/integrationplatform_types.go
pkg/controller/integrationplatform/catalog.go
pkg/controller/integrationplatform/catalog_test.go
pkg/controller/integrationplatform/integrationplatform_controller.go
pkg/controller/integrationplatform/monitor.go
pkg/controller/integrationplatform/monitor_test.go
pkg/platform/defaults.go
pkg/trait/camel.go
pkg/trait/registry.go
pkg/util/camel/camel_runtime.go
pkg/util/defaults/defaults.go
pkg/util/maven/maven_command.go
pkg/util/test/client.go
pkg/util/util_test.go
script/Makefile

- Create CamelCatalog for new runtimeVersion that has been set on IntegrationPlatform
- Improve CamelCatalog availability checks on IntegrationPlatform controller
- Adds new condition on IntegrationPlatform representing the availability of the catalog
- Sets IntegrationPlatform to error phase when catalog is not available
This adds auto creation of the CamelCatalog resource in the IntegrationPlatform controller. When a user sets a new runtimeVersion for the IntegrationPlatform resource the catalog will be created as part of the reconcile loop. This ensures that the catalog is created straightaway after the configuration change has happened and that potential errors due to the camel catalog creation are reported on the IntegrationPlatform conditions.
Users still may set the runtimeVersion …

Create CamelCatalog on IntegrationPlatform controller

---

.github/workflows/comment-pr.yaml

Fix comment PR github actions workflow (github.issues).
```release-note
fix(ci): Comment PR github action issues uses octokit 
```

fix(ci): Comment PR github action issues uses octokit 

---

pkg/trait/camel.go

- When new runtime version is used on integration the camel trait creates the catalog if it does not exist already
- Use proper catalog namespace to verify that the catalog resource has been created during the camel trait execution
(cherry picked from commit 29162470e8fafc9df62df819dcb8cc72f4903570)
```release-note
NONE
```

[BACKPORT-2.2.x] fix(#4776): Fix catalog loading in camel trait

---

helm/camel-k/README.md
helm/camel-k/templates/operator.yaml
helm/camel-k/values.yaml

This resolves #5103 
```release-note
It is now possible to set the operator nodeSelector in the helm values file.
```

feat(#5103): Adding nodeSelector to the operator helm chart

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/cron.adoc
pkg/apis/camel/v1/trait/cron.go
resources/traits.yaml

Backport from https://github.com/apache/camel-k/pull/5127
```release-note
fix(doc): Add warning on cron trait for native build
```

[Backport 2.2.x]: fix(doc): Add warning on cron trait for native build

---

pkg/controller/integrationplatform/catalog.go
pkg/controller/integrationplatform/catalog_test.go

The nightly check is failing when camel-k-runtime is a snapshot release, so the apache snapshot repository must be added to the settings.xml when testing.
```release-note
NONE
```

fix(test): add apache-snapshot repository as the test may run agains a camel-k-runtime snaphost release

---

e2e/common/config/config_reload_test.go
e2e/support/test_support.go
pkg/util/digest/digest.go
pkg/util/digest/digest_test.go

Proposal of fix to https://github.com/apache/camel-k/issues/5114 - use Name, Namespace and Data/StringData to compute digest of Configmap and Secret.

Compute digest of configmap and secret from its data

---

pkg/util/digest/digest.go

Proposal of improvement to https://github.com/apache/camel-k/pull/5115 - reduce number of writes to `hash` object (failing test `TestRunDevMode`)

Reduce write to hash, prepare string from secret, configmap

---

pkg/cmd/run.go

We cannot support this any longer. Connecting from the CLI to the container registry does not seem a secure thing to do. Moreover we are aiming to replace the CLI with Camel JBang.
```release-note
chore(cmd): deprecate -d file feature
```

chore(cmd): deprecate -d file feature

---

e2e/common/config/config_test.go
pkg/trait/mount.go
pkg/trait/service_binding.go
pkg/trait/service_binding_test.go
pkg/trait/trait_types.go
pkg/util/kubernetes/collection.go
pkg/util/test/client.go

```release-note
fix(trait): service binding
```

fix(trait): service binding

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/knative.adoc
pkg/apis/camel/v1/knative/types.go
pkg/apis/camel/v1/knative/types_support.go
pkg/apis/camel/v1/knative/types_support_test.go
pkg/apis/camel/v1/trait/knative.go
pkg/trait/knative.go
pkg/trait/knative_service_test.go
pkg/trait/knative_test.go

With this PR we move the configuration from the env var to the properties.
```release-note
chore(knative): configure via properties
```

chore(knative): configure via properties

---

pkg/trait/camel.go
pkg/trait/camel_test.go
pkg/trait/kamelets.go
pkg/trait/kamelets_support.go
pkg/trait/openapi.go
pkg/trait/trait_types.go

Cleaning PR to include some constant instead of hardcoded values.
```release-note
chore: use constants for config types
```

chore: use constants for config types

---

e2e/builder/build_test.go
e2e/common/traits/builder_test.go
e2e/support/test_support.go
pkg/apis/camel/v1/build_types.go
pkg/controller/build/build_monitor.go
pkg/controller/build/build_monitor_test.go
pkg/controller/build/schedule.go

* Add on Build.Status a "Scheduled" condition containing the reason for it's scheduling status
Ref #4542
```release-note
feat(build): Add Build waiting condition
```

feat(build): Add Build waiting condition

---

e2e/advanced/build_order_strategy_test.go
pkg/apis/camel/v1/build_type_support_test.go
pkg/apis/camel/v1/build_types_support.go

The `TestRunBuildOrderStrategyMatchingDependencies` uses to be flaky. I've investigated and the root cause seems to be the heuristic we are using to detect matching dependencies. The following piece of code `missing >= len(required)/2` seem to be the problem, in the sense that when the number of `required` is odd, then, the code is rounded to a integer value that is not matching the condition. The ideal solution is to add +1 to that division, or removing the equality which would sort the same effect.
This PR address the problem. The heuristic used is strengthen against this corner case and validated with a few unit test.
```release-note
fix(builder): strenghten matching dependencies heuristic
```

fix(builder): strenghten matching dependencies heuristic

---

.github/actions/release-nightly/action.yml

Backport from #5182
```release-note
chore(ci): upgrade release-action action
```

[Backport 2.1.x]: chore(ci): upgrade release-action action

---

.github/actions/release-nightly/action.yml

Backport from #5182
```release-note
chore(ci): upgrade release-action action
```

[Backport 2.2.x]: chore(ci): upgrade release-action action

---

addons/vault/aws/aws_secrets_manager.go
addons/vault/azure/azure_key_vault.go
addons/vault/gcp/gcp_secret_manager.go
addons/vault/hashicorp/hashicorp_vault.go
pkg/trait/knative.go
pkg/trait/prometheus.go
pkg/util/camel/camel_runtime_test.go

Removing some deprecated code no longer required since runtime version 2.16. Additionally taking the opportunity and adding some unit test to improve coverage.
```release-note
fix(trait): catalog to drive dependencies
```

fix(trait): catalog to drive dependencies

---

pkg/builder/quarkus.go
pkg/builder/quarkus_test.go

Moving from maven based approach to a file approach in order to let be able to use any character which may be a limitation in pom.xml
Closes #5195
```release-note
fix(quarkus): build time properties into file
```

fix(quarkus): build time properties into file

---

e2e/common/misc/pipe_test.go
pkg/trait/error_handler.go

Change the func name to highlight the fact the ErrorHandler is a global one. Additionally we make a stricter check to make sure that the simple look into the log for the body logged is what we expect instead of a generic string which may be part of the log somewhere else.
```release-note
fix(e2e): stricter pipe test check
```

fix(e2e): stricter pipe test check

---

pkg/builder/quarkus_test.go
pkg/controller/integrationplatform/catalog_test.go
pkg/util/camel/camel_runtime_test.go
script/get_catalog.sh

Night checks against latest runtime are failing due to missing apache snapshot repository. This PR aims to fix it.
```release-note
fix(ci): add snapshot repo
```

fix(ci): add snapshot repo

---

build/Dockerfile

Closes #5231 
```release-note
fix(build): Upgrade container image to golang 1.21
```

fix(build): Upgrade container image to golang 1.21

---

pkg/builder/quarkus.go
pkg/builder/quarkus_test.go

This PR fixes the Quarkus native execution which is actually failing due to the fact that we are overriding some `application.properties` configuration by mistake.
```release-note
fix(quarkus): don't override application.properties
```

[Regression] fix(quarkus): don't override application.properties

---

pkg/controller/integration/build_kit.go
pkg/controller/integration/monitor.go

Change of a digest would reset an Integration, but a rebuild may not be required.
Closes #5219
```release-note
fix(ctrl): message digest change
```

fix(ctrl): message digest change

---

docs/modules/ROOT/pages/architecture/traits.adoc
e2e/common/misc/pipe_test.go
e2e/common/traits/builder_test.go
pkg/controller/integration/kits.go
pkg/controller/integration/kits_test.go
pkg/controller/integration/monitor.go
pkg/trait/builder.go
pkg/trait/builder_test.go
pkg/trait/camel.go
pkg/trait/camel_test.go
pkg/trait/quarkus.go
pkg/trait/quarkus_test.go
pkg/trait/registry.go
pkg/trait/trait_types.go
pkg/trait/util.go
pkg/trait/util_test.go

Reverting #4512 which introduced a function diverging the match from the original design
This PR aims to fix a diverging design I introduced some times ago. With this one we move back to the original design making correct usage of `Comparable` interface in trait which is used by the operator to distinguish when to reuse or rebuild an Integration based only on certain IntegrationKit traits changes (ie, runtime version, builder properties).
```release-note
fix(traits): use Comparable matches
```

fix(traits): use Comparable matches

---

build/Dockerfile
script/Makefile

CrossRef: https://github.com/apache/camel-k/issues/5169
```
$ go run ./cmd/kamel install                                                                                                            
OLM is not available in the cluster. Fallback to regular installation.
Using arch specific operator image: docker.io/apache/camel-k:2.3.0-SNAPSHOT-arm64
Using arch specific base image: eclipse-temurin:17@sha256:a90cec83bb9b9ab19a63e377b20c3aa4e076b16c52d36e83c62c451b6d034e22
Camel K installed in namespace default 
```

Install operator image according to the target architecture

---

pkg/resources/config/samples/bases/camel_v1alpha1_kamelet.yaml

When generating the operator bundle metadata, there is a missing sample for v1alpha1 Kamelet.
```release-note
NONE
```

Add Kamelet v1alpha1 sample

---

pkg/resources/config/samples/bases/camel_v1alpha1_kamelet.yaml

Fix wrong Kamelet sample content

---

.github/actions/release-nightly/action.yml
docs/modules/ROOT/pages/contributing/developers.adoc
script/Makefile

To build all image variants, call
```
make images-all
```
Support push for `CUSTOM_IMAGE` (i.e. not just `STAGING_IMAGE`)

[#5252] release-nightly does not build/push multiarch manifest

---

pkg/apis/camel/v1/integration_types_support.go
pkg/controller/pipe/integration.go
pkg/controller/pipe/integration_test.go
pkg/trait/error_handler.go
pkg/trait/error_handler_test.go

YAML DSL in Camel should use camel case instead of kebap case. PR also adds some unit tests
```release-note
NONE
```

chore: Use camel case for Pipe error handler ref

---

.github/workflows/native.yml
.github/workflows/nightly-native-test.yml

Closes #4885
```release-note
fix(ci): use ubuntu which now have 16 GB memory
```

fix(ci): use ubuntu which now have 16 GB memory

---

pkg/trait/knative.go
pkg/trait/knative_service_test.go
pkg/trait/knative_test.go

https://github.com/apache/camel-k/issues/5145
Remove the SortChannelFakeClient function since it's not used.
```release-note
Only enable knative trait when there is a knative endpoint
```

Only enable knative trait when there is a knative endpoint

---

script/Makefile

Fixes #5288 
- Add Makefile build-platform to build the platform specific kamel CLI binary (e.g. darwin/arm64)
- Image build statically builds the linux binary for the Docker image and additionally builds platform specific kamel CLI binary if running on host other than linux
- Enables developers running on platforms other than linux to directly use the built kamel CLI binary
`make images` will build the linux binary and add it to the Docker image as usual. In addition to that platform specific kamel CLI binary is built at the end of the process when running on platforms other that linux. This enable the developer to just call `make images` and directly use the built kamel CLI binary on the host (e.g. `kamel install`)
Also developers running on platform other than linux may call `make …

fix(#5288): Makefile building platform specific kamel CLI binary

---

e2e/support/test_support.go

Enable optional installation which connects to remote mvn repository in e2e tests (https://camel.apache.org/camel-k/next/installation/advanced/maven.html#ca-certificates); provide path to certificate via `CAMEL_K_TEST_MAVEN_CA_PEM_PATH` -  in branch `release-2.2.x`.

Add optional install to tests - branch 2.2.x

---

pkg/trait/service_binding.go
pkg/trait/service_binding_test.go

Leverage changes introduced in https://github.com/apache/camel-k-runtime/pull/1192
```release-note
feat(traits): service binding refactoring
```

feat(traits): service binding refactoring

---

e2e/install/upgrade/helm_upgrade_test.go

As we're about to release 2.3 we want to have a clean check execution. This test is wrong as it deletes the CRDs. We need to rework it as suggested in https://github.com/apache/camel-k/issues/5304#issuecomment-2031259175
Temporarily skipping to allow releasing 2.3. Beware that it's the test which is wrong. The Helm upgrade procedure still stands, but it fails as there is an introduction of a new CRD which has to be injested manually.
Ref #5304
```release-note
NONE
```

fix(e2e): temporarily disable test

---

e2e/advanced/platform_traits_test.go
pkg/trait/logging.go
pkg/trait/logging_test.go

Leverage changes introduced in https://github.com/apache/camel-k-runtime/pull/1192
```release-note
feat(traits): logging refactoring
```

feat(traits): logging refactoring

---

pkg/install/operator.go

The CLI install in openshift on global operator fails because it can't find the file. 
```release-note
fix(cli): openshift cli install global operator rbac path
```

fix(cli): openshift cli install rbac path

---

.github/actions/release-nightly/action.yml

Closes #5311
```release-note
doc: adjust nightly release description
```

doc: adjust nightly release description

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/camel.adoc
helm/camel-k/crds/crd-integration-kit.yaml
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration-profile.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/trait/camel.go
pkg/resources/config/crd/bases/camel.apache.org_integrationkits.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_kameletbindings.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/camel.go
pkg/trait/camel_test.go

With this PR we fix a minor problem that was impeding us to make use of the semantic version jolly. Once this is merged we'll be able to run:
```
kamel run test.yaml -t camel.runtime-version=2.x
```
which will resolve to the best match of the existing CamelCatalogs. For example, given:
```
NAME                   RUNTIME PROVIDER   RUNTIME VERSION   RUNTIME CAMEL VERSION   PHASE
camel-catalog-2.16.0   quarkus            2.16.0            3.20.1                  Ready
camel-catalog-3.8.1    quarkus            3.8.1             4.4.1                   Ready
```
It will pick up version 2.1.6.0
Closes https://github.com/apache/camel-k/issues/4739
```release-note
feat(trait): allow usage of semver for camel.runtime-version 
```

feat(trait): allow usage of semver for camel.runtime-version 

---

pkg/install/operator.go

Backport from https://github.com/apache/camel-k/pull/5316
```release-note
fix(cli): openshift cli install global operator rbac path
```

[Backport 2.3.x]: fix(cli): openshift cli install rbac path

---

e2e/install/kustomize/operator_test.go

- Make sure to wait some time for registry address to be set on IntegrationPlatform status
```release-note
NONE
```

fix(#5326): Fix flaky E2E test

---

e2e/install/kustomize/operator_test.go

- Make sure to wait some time for registry address to be set on IntegrationPlatform status
(cherry picked from commit f6d38bfc927fadefd556861679b9b5b9cc10f9de)
```release-note
NONE
```

[BACKPORT-2.3.x] fix(#5326): Fix flaky E2E test

---

pkg/resources/config/manifests/bases/camel-k.clusterserviceversion.yaml

Fixes #5341 
```release-note
fix: Add IntegrationProfile to CSV
```

fix(#5341): Add IntegrationProfile to CSV

---

e2e/common/traits/health_test.go

- Avoid failing assertion on condition status ready=false due to temporary deployment ready condition status
```release-note
NONE
```

fix(#4922): Fix flaky TestHealthTrait

---

e2e/advanced/synthetic_test.go
pkg/install/operator.go

Ref #5349 
```release-note
fix(install): No duplicate envvars on operator pod container
```

fix(install): No duplicate envvars on operator pod container

---

e2e/common/traits/health_test.go

- Avoid failing assertion on condition status ready=false due to temporary deployment ready condition status
```release-note
NONE
```

[BACKPORT-2.3.x] fix(#4922): Fix flaky TestHealthTrait

---

.github/workflows/builder.yml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
helm/camel-k/crds/crd-build.yaml
pkg/apis/camel/v1/build_types.go
pkg/apis/camel/v1/integrationplatform_types.go
pkg/apis/camel/v1/trait/builder.go
pkg/resources/config/crd/bases/camel.apache.org_builds.yaml
pkg/trait/builder.go

Will report a deprecation condition message in the Integration like:
```
- firstTruthyTime: "2024-04-12T13:29:14Z"
lastTransitionTime: "2024-04-12T13:29:14Z"
lastUpdateTime: "2024-04-12T13:29:14Z"
message: Spectrum publishing strategy is deprecated and may be removed in future
releases. Make sure to use any supported publishing strategy instead.
reason: TraitConfiguration
status: "True"
type: BuilderTraitInfo
```
Closes #5314 
```release-note
feat(trait): Spectrum deprecation notice
```

feat(trait): Spectrum deprecation notice

---

e2e/common/config/config_test.go
e2e/common/traits/gc_test.go
e2e/knative/files/PlatformHttpServer.java
e2e/knative/gc_test.go
pkg/apis/camel/v1/integration_types_support.go
pkg/trait/gc.go
pkg/trait/gc_test.go
pkg/trait/trait.go
pkg/util/test/client.go

- Run garbage collection trait also in Integration initialization phase
- Fallback to minimal set of deletable types when auto discovery fails (e.g. in OpenShift)
- Add some unit and E2E test
```release-note
NONE
```

fix: Fix garbage collection trait

---

e2e/common/config/config_test.go
e2e/common/traits/gc_test.go
e2e/knative/files/PlatformHttpServer.java
e2e/knative/gc_test.go
pkg/apis/camel/v1/integration_types_support.go
pkg/trait/gc.go
pkg/trait/gc_test.go
pkg/trait/trait.go
pkg/util/test/client.go

- Run garbage collection trait also in Integration initialization phase
- Fallback to minimal set of deletable types when auto discovery fails (e.g. in OpenShift)
- Add some unit and E2E test
```release-note
NONE
```

[BACKPORT-2.3.x] fix: Fix garbage collection trait

---

pkg/builder/quarkus_test.go
pkg/controller/integration/metrics_test.go

Backport of https://github.com/apache/camel-k/pull/5364
```release-note
chore(ci): Fix license check
```

[Backport 2.3.x]: chore(ci): Fix license check

---

e2e/common/config/config_test.go

Ref #4841
The bugfix is done : https://issues.apache.org/jira/browse/CAMEL-20054
```release-note
chore(e2e): Remove unnecessary jvm.option in test
```

chore(e2e): Remove unnecessary jvm.option in test

---

e2e/common/config/config_test.go

Backport of #5371 
Ref apache#4841
```release-note
chore(e2e): Remove unnecessary jvm.option in test
```

[Backport 2.3.x]: chore(e2e): Remove unnecessary jvm.option in test

---

pkg/trait/trait_condition_types.go

Closes #5381
```release-note
fix(trait): condition kit type
```

fix(trait): condition kit type

---

pkg/client/client.go

ctrlClientWrapper synchronizes all Reader/Writer access across clients of this type
https://github.com/kubernetes-sigs/controller-runtime/issues/2782
https://github.com/apache/camel-k/issues/5315

(fix#5315): concurrent map read and map write

---

e2e/common/misc/pipe_with_image_test.go

Image quay.io/fuse_qe/echo-server:0.3.2, 3 was verified on x86, IBM PPC, s390x.

Replaced echo-server image by multiarch

---

e2e/knative/default.go
e2e/knative/gc_test.go
e2e/knative/kamelet_test.go
e2e/knative/knative_test.go
e2e/knative/openapi_test.go
e2e/knative/pod_test.go

- Enables better error analysis due to automatic dump of resources on test failure
```release-note
NONE
```

chore(e2e): Use new test namespace in Knative E2E tests

---

helm/camel-k/templates/operator-cluster-roles.yaml
helm/camel-k/templates/operator-role.yaml

Adding missing types on helm chart for
* eventing
* messaging
APIs of knative
the non-helm manifests have those (kept same order)
-->
```release-note
NONE
```

Adding eventing core types on RBAC

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/builder.adoc
helm/camel-k/crds/crd-integration-kit.yaml
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration-profile.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/trait/builder.go
pkg/resources/config/crd/bases/camel.apache.org_integrationkits.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_kameletbindings.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml

Ref #5372 
Add warning on resource namespace for maven profile.
```release-note
doc(trait): Maven profile cm/secret additional information
```

doc(trait): Maven profile cm/secret additional information

---

pkg/trait/container.go
pkg/trait/container_probes_test.go
pkg/trait/container_test.go
pkg/trait/health.go
pkg/trait/prometheus.go
pkg/trait/route.go
pkg/trait/trait_types.go

Using a func that determine the default port name based on the controller strategy adopted
Close #5409
```release-note
NONE
```

[Backport 2.3.x] fix(trait): controller strategy default service port name

---

pkg/controller/integration/platform_setup.go
pkg/controller/kameletbinding/integration.go
pkg/controller/pipe/integration.go
pkg/trait/gc.go
pkg/trait/knative.go
pkg/trait/knative_service.go
pkg/trait/knative_service_test.go
pkg/trait/knative_test.go
pkg/util/knative/enabled.go
pkg/util/knative/knative.go
pkg/util/kubernetes/collection.go
pkg/util/test/client.go

Fixes #5402
- Use Knative profile when Serving or Eventing is installed on cluster
- Make sure to enable Knative trait when Serving or Eventing is installed
- Enable knative-service trait only when Knative Serving is installed
- Garbage collect Serving and Eventing resources in gc trait only when Serving/Eventing is installed on the cluster
- Do not use Serving service in Knative trigger when not installed on cluster
- Use arbitrary Service as a subscriber in Knative trigger when Serving is not available
```release-note
fix(#5402): Evaluate Knative profile based on Serving/Eventing installed
```

fix(#5402): Evaluate Knative profile based on Serving/Eventing installed

---

pkg/controller/integration/platform_setup.go
pkg/controller/kameletbinding/integration.go
pkg/controller/pipe/integration.go
pkg/trait/gc.go
pkg/trait/knative.go
pkg/trait/knative_service.go
pkg/trait/knative_service_test.go
pkg/trait/knative_test.go
pkg/util/knative/enabled.go
pkg/util/knative/knative.go
pkg/util/kubernetes/collection.go
pkg/util/test/client.go

- Use Knative profile when Serving or Eventing is installed on cluster
- Make sure to enable Knative trait when Serving or Eventing is installed
- Enable knative-service trait only when Knative Serving is installed
- Garbage collect Serving and Eventing resources in gc trait only when Serving/Eventing is installed on the cluster
- Do not use Serving service in Knative trigger when not installed on cluster
- Use arbitrary Service as a subscriber in Knative trigger when Serving is not available
```release-note
fix(#5402): Evaluate Knative profile based on Serving/Eventing installed
```

[BACKPORT-2.3.x] fix(#5402): Evaluate Knative profile based on Serving/Eventing installed

---

pkg/cmd/run.go

[Backport 2.3.x] chore(cmd): error if no default catalog found

---

e2e/README.md
e2e/support/test_support.go

- Provide envvars to the user to enable/disable copy catalog e2e test optimization
- Provide envvars to the user to enable/disable copy integration kit e2e test optimization
- Add some documentation on available e2e test envvars
```release-note
NONE
```

chore(e2e): Allow to disable copy optimizations on E2E tests

---

e2e/README.md
e2e/support/test_support.go

- Provide envvars to the user to enable/disable copy catalog e2e test optimization
- Provide envvars to the user to enable/disable copy integration kit e2e test optimization
- Add some documentation on available e2e test envvars
```release-note
NONE
```

[Backport-2.3.x] chore(e2e): Allow to disable copy optimizations on E2E tests

---

.github/workflows/comment-pr.yaml
e2e/advanced/files/deploy.yaml

Backport of https://github.com/apache/camel-k/pull/5442
```release-note
chore(release): fix missing licenses
```

[Backport 2.3.x]: chore(release): fix missing licenses

---

cmd/util/check_jdk_version/main.go
docs/modules/ROOT/pages/contributing/developers.adoc
script/Makefile

fixes(#5439): Build should enforce a required jdk version

---

docs/modules/ROOT/pages/installation/advanced/offline.adoc
script/maven-settings-offline-template.xml
script/offline_dependencies.sh

- Enhance the offline script 
. Use `quarkus:go-offline`.
. build a minimum project to resolve dependencies not resolved with the previous script.
. The user can download only the script to run it.
- Enhance documentation
```release-note
Enhance the offline script and documentation.
```

Enhance offline script and documentation

---

e2e/common/cli/get_test.go
e2e/common/misc/files/cron-fallback.yaml
e2e/common/misc/files/cron-quartz.yaml
e2e/common/misc/files/cron-timer.yaml
e2e/common/misc/files/cron-trait-yaml.yaml
e2e/common/misc/files/cron-yaml.yaml
e2e/common/misc/integration_fail_test.go
e2e/common/traits/health_test.go
e2e/common/traits/master_test.go
pkg/apis/camel/v1/trait/health.go
pkg/cmd/debug.go
pkg/cmd/debug_test.go
pkg/trait/health.go
pkg/trait/health_test.go
pkg/trait/jvm.go
pkg/trait/trait_test.go

Closes #5024
```release-note
feat(trait): enable health trait by default
```

feat(trait): enable health trait by default

---

helm/camel-k/crds/crd-integration.yaml
pkg/apis/camel/v1/integration_types.go
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml

Useful to get the readiness information from cluster tooling
```
$ kubectl get it -w
NAME   PHASE          READY   RUNTIME PROVIDER   RUNTIME VERSION   KIT                        REPLICAS
test   Building Kit           quarkus            3.8.1             kit-coqas3g4uf3s73fba8p0   
test   Deploying              quarkus            3.8.1             kit-coqas3g4uf3s73fba8p0   
test   Running        False   quarkus            3.8.1             kit-coqas3g4uf3s73fba8p0   1
test   Running        False   quarkus            3.8.1             kit-coqas3g4uf3s73fba8p0   1
test   Running        True    quarkus            3.8.1             kit-coqas3g4uf3s73fba8p0   1
```
```release-note
feat(api): show integration readiness
```

feat(api): show integration readiness

---

docs/modules/ROOT/pages/installation/advanced/offline.adoc
script/maven-settings-offline-template.xml
script/offline_dependencies.sh

- Enhance the offline script to use quarkus:go-offline and to build a minimum project to resolve dependencies not resolved with the previous script
- Enhance documentation
(cherry picked from commit 6fee6d6a0026817103db246c03b21952fd147276)
```release-note
Enhance the offline script and documentation.
```

[backport 2.3] Enhance offline script and documentation (#5447)

---

e2e/common/traits/health_test.go

* moved back the check to correctly expect constantly the readiness to be False
* added the properties as expected by Camel
Closes #5351
```release-note
fix(e2e): add readiness workaround as expected by Camel framework
```

fix(e2e): add readiness workaround as expected by Camel framework

---

pkg/kamelet/repository/github_repository.go
pkg/kamelet/repository/github_repository_test.go

Closes #5173
```release-note
fix(kamelets): parse the url used to download kamelet
```

fix(kamelets): parse the url used to download kamelet

---

.github/workflows/validate.yml
.golangci.yml
addons/master/master.go
pkg/apis/camel/v1/maven_types_support.go
pkg/cmd/run.go
script/Makefile

chore: update golagci-lint to v1.158.0

---

script/Makefile

Incorrect content of the build/_maven_overlay directory causes the build project failure

---

.github/workflows/security.yaml
.github/workflows/validate.yml
.gitignore
script/Makefile

chore: use the same make targhet for lkint and vuln check locally and on ci

---

pkg/builder/jib.go
pkg/platform/defaults.go

This adds `-Djib.from.platforms=linux/arm64` when there is no explicit `-t builder.platforms` trait. 
Unlike previous attempts, this change should not interfere with the upgrade functionality.
On arm64, try this ...
```
make images
kamel install
kamel run --dev ./e2e/advanced/files/Java.java
```

fix(#5292): Simplify run cmd for archs other than amd64

---

e2e/advanced/build_order_strategy_test.go
e2e/advanced/builder_test.go
e2e/advanced/debug_test.go
e2e/advanced/operator_id_filtering_test.go
e2e/common/misc/integration_fail_test.go
e2e/support/test_support.go
pkg/cmd/run.go
pkg/util/kubernetes/portforward.go

Some fixes mostly to prevent flaky tests run. It is part of the work done in https://github.com/apache/camel-k/pull/5119

Test fixes

---

.golangci.yml
script/Makefile

This PR aims to reduce the number of excluded lints, ideally we should revisit the usefulness of the disabled ones and re-enable them.

cleanup golagci-lint configuration

---

pkg/platform/platform.go
pkg/util/maven/maven_command.go

`MAVEN_CMD` has the precedence over the maven wrapper, either set via the
`MAVEN_WRAPPER` env var or copied from a local path. This commit changes
the evaluation order to reflect ordering which avoid to perform a
useless file copy and also make it easy to run the operator off cluster
since the `mvnw` location may not exist
```release-note
NONE
```

fix(maven): move check for MAVEN_CMD before maven wrapper setup

---

pkg/builder/jib.go
pkg/cmd/dump.go
pkg/util/maven/maven_command.go
pkg/util/maven/maven_log.go
pkg/util/maven/maven_log_test.go
pkg/util/maven/maven_project.go
pkg/util/maven/maven_repositories.go
pkg/util/tar/util_compress.go

cleanup pkg/util packages

---

e2e/advanced/incremental_build_test.go

Small fix of e2e/advanced/incremental_build_test.go after https://github.com/apache/camel-k/pull/5415
```release-note
NONE
```

fix(tests): Minor fix to incremental_build_test.go after fixing of copykits.

---

e2e/common/traits/route_test.go

Route Trait should only contains `annotations` param in the test.
As it is skipped on non-openshift infra, we missed the error in the test code.
```release-note
fix(e2e): Route trait schema valid in OCP
```

fix(e2e): Route trait schema valid in OCP

---

e2e/install/upgrade/cli_upgrade_test.go
e2e/install/upgrade/olm_upgrade_test.go
e2e/support/test_support.go
pkg/trait/environment.go

This PR is making sure that we use Integration status version and runtime version for environment variables. During upgrade process those parameter are not updated as the Integration digest is not changing either.
We cannot move this yet on main branch as there are other changes there affecting Deployment that would require additional attention.
```release-note
fix(e2e): don't rollout Pods on operator upgrade
```

[Release 2.3.x] fix(e2e): don't rollout Pods on operator upgrade

---

e2e/advanced/tekton_test.go

Backport of https://github.com/apache/camel-k/pull/5505
```release-note
fix(e2e): Tekton test permission failure with olm install command
```

[Backport 2.3.x]: fix(e2e): Tekton test permission failure with olm install command

---

e2e/common/traits/files/NeverReady.java
e2e/common/traits/health_test.go

Due to how camel works stopping a route using the message bus inside the route can not assure that the route is reported always as stopped, there might be a small amount of time in which it can be reported as running.
Since the test is testing the behavior of camel k in the case that an integration is always reported not ready I took another approach by registering a custom healthcheck that force the reported condition to be never ready. 
```release-note
NONE
```

fix(tests): fixed flaky Readiness condition with never ready route test in e2e/common/traits/health_test.go

---

e2e/common/traits/health_test.go
e2e/install/upgrade/cli_upgrade_test.go
e2e/install/upgrade/olm_upgrade_test.go
pkg/apis/camel/v1/trait/health.go
pkg/trait/health.go
pkg/trait/health_test.go
pkg/trait/trait_test.go

This PR partially reverts the work done in #5096. While working on the upgrade I realized we must strengthen the test and make sure that any automatic Pod rollout, after the operator upgrade, must finish successfully. This lead to the verification that the health trait set by default in the aforementioned PR does introduce a breaking compatibility change, as it requires a rebuild of the application due to the need to get the Camel health dependencies. This would have turn all Integrations in an unready status as soon we have moved to upcoming release version.
```release-note
chore(trait): revert default health enabled
```

chore(trait): revert default health enabled

---

pkg/trait/camel.go
pkg/trait/camel_test.go
pkg/trait/kamelets.go
pkg/trait/kamelets_test.go
pkg/trait/mount.go

This PR fix some regressions as identified in https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Catalog.20not.20found.20for.20sourceless.20integration.20after.20upgrade
```release-note
fix(traits): don't skip for synthetic kits
```

[Release 2.3.x] fix(traits): don't skip for synthetic kits

---

pkg/controller/synthetic/synthetic.go
pkg/controller/synthetic/synthetic_test.go

Because the operator may not have permissions over the Deployment resource finalizers
```release-note
fix(ctrl): synthetic Integration cannot set blockOwnerDeletion
```

fix(ctrl): synthetic Integration cannot set blockOwnerDeletion

---

pkg/controller/synthetic/synthetic.go
pkg/controller/synthetic/synthetic_test.go

Because the operator may not have permissions over the Deployment resource finalizers
```release-note
NONE
```

[Release 2.3.x] fix(ctrl): synthetic Integration cannot set blockOwnerDeletion

---

e2e/advanced/build_order_strategy_test.go

Probably it was commented during development and slipped into a commit.
```release-note
chore(e2e): revert a commented test
```

chore(e2e): revert a commented test

---

pkg/builder/quarkus.go

We have no reason to try executing any test as we don't expect the presence of any test at all
The operator output is now the following one:
```
camel-k-operator-5f5bf4f7bb-2w2tz camel-k-operator {"level":"info","ts":"2024-05-31T09:27:58Z","logger":"camel-k.maven.build","msg":"--- maven-surefire-plugin:2.12.4:test (default-test) @ camel-k-integration ---"}
camel-k-operator-5f5bf4f7bb-2w2tz camel-k-operator {"level":"info","ts":"2024-05-31T09:27:59Z","logger":"camel-k.maven.build","msg":"Tests are skipped."}
camel-k-operator-5f5bf4f7bb-2w2tz camel-k-operator {"level":"info","ts":"2024-05-31T09:27:59Z","logger":"camel-k.maven.build","msg":""}
camel-k-operator-5f5bf4f7bb-2w2tz camel-k-operator {"level":"info","ts":"2024-05-31T09:27:59Z","logger":"camel-k.maven.build","msg":"--- …
```

chore(builder): add -DskipTests

---

e2e/common/misc/pipe_test.go
pkg/controller/pipe/initialize_test.go
pkg/controller/pipe/integration.go
pkg/controller/pipe/monitor_test.go
pkg/util/bindings/catalog.go

The func will return an error instead of a nil value with a suggestion of the available bindings to use.
Closes https://github.com/apache/camel-k/issues/5535
```release-note
fix(pipe): don't panic if no binding available
```

fix(pipe): don't panic if no binding available

---

e2e/README.md
script/Makefile

Borrowed from [maven surefire](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#skipAfterFailureCount) - count test failures and skip subsequent tests when `failure count > $TEST_SKIP_AFTER_FAILURE_COUNT`
The default is `TEST_SKIP_AFTER_FAILURE_COUNT=3`
This can significantly speed up validation of bad PRs

Add support for TEST_SKIP_AFTER_FAILURE_COUNT

---

e2e/advanced/files/camel-k-tekton.yaml
e2e/advanced/main_test.go
e2e/advanced/tekton_test.go
e2e/support/test_support.go

Refactor the tekton test like task test to use it have it work the closely most  it is supposed to work:
* the Camel K operator is supposed to be already installed
* the tekton task consist of a `kamel run` command allowing to deploy a an integration from a file (here present via a volume from a configmap)
```release-note
feat(e2e): Rewrite tekton test to use run command
```

feat(e2e): Rewrite tekton test to use run command

---

.github/actions/e2e-telemetry/action.yml

```release-note
chore(ci): Upgrade opentelemetry-collector to last v0.x
```

chore(ci): Upgrade opentelemetry-collector to last v0.x

---

script/release_helm.sh

Closes #5575
```release-note
NONE
```

[Backport 2.3.x] fix(ci): merge helm with older index

---

pkg/controller/build/monitor_pod.go

Backport of #5600 
```release-note
fix(core): Remove status.Image update post publish
```

[Backport 2.3.x] fix(core): Remove status.Image update post publish

---

e2e/advanced/maven_http_proxy_test.go

Backport of #5581 
```release-note
fix(e2e): Ensures Maven proxy test is not infra dependant
```

[Backport 2.3.x] fix(e2e): Ensures Maven proxy test is not infra dependant

---

e2e/advanced/maven_http_proxy_test.go
pkg/util/maven/maven_proxies_test.go

* Add Unit test for maven proxy settings
* Add check on env vars for pod on e2e tests
```release-note
test: Improve tests for maven proxy settings
```

test: Improve tests for maven proxy settings

---

e2e/advanced/maven_http_proxy_test.go
pkg/util/maven/maven_proxies_test.go

Backport of #5594 
```release-note
test: Improve tests for maven proxy settings
```

[Backport 2.3.x] test: Improve tests for maven proxy settings

---

pkg/util/camel/camel_runtime_catalog.go
pkg/util/camel/camel_runtime_catalog_test.go

Backport of #4893 
```release-note
Fix #4893: Support YAML DSL routes configuration
```

[Backport 2.3.x] feat(4893) YAML DSL route configuration support

---

pkg/cmd/install.go

Simple change that removes the unwanted double space in front of '(global mode)'. i.e. we now have
```
Camel K installed in namespace default (global mode)
Camel K installed in namespace default via OLM subscription (global mode)
```

Revisit final operator install message

---

.github/workflows/native.yml
.github/workflows/nightly-native-test.yml

Closes #5598
```release-note
feat(ci): bring back Quarkus native execution on PR and pushes
```

feat(ci): bring back Quarkus native execution on PR and pushes

---

docs/modules/ROOT/pages/configuration/runtime-resources.adoc
e2e/common/config/files/resource-configmap-route.yaml
e2e/common/config/files/resource-secret-route.yaml
e2e/common/traits/jvm_test.go
pkg/trait/jvm.go
pkg/trait/jvm_test.go
pkg/trait/trait_types.go
pkg/util/camel/camel_util.go
pkg/util/util.go

* Replace /etc/camel/conf.d/_resources by  /etc/camel/resources.d/[_configmaps/_secrets]
* Deprecates `./resources` and `/etc/camel/resources`
Note: removal of `./resources` and `/etc/camel/resources` test run passed successfully so it can be done after the next release.
```release-note
feat(core): Mount configmap/secret resources in dedicated resources.d.  Deprecates ./resources and /etc/camel/resources default paths.
```

feat(core): Mount configmap/secret resources in dedicated resources.d

---

docs/modules/ROOT/pages/contributing/local-development.adoc
script/Makefile

Closes #5460
```release-note
feat(ci): local installation procedure
```

feat(ci): local installation procedure

---

addons/addons_test.go
e2e/common/misc/pipe_with_image_test.go
pkg/cmd/bind.go
pkg/cmd/kit_create.go
pkg/cmd/run.go
pkg/cmd/run_test.go
pkg/controller/integration/build_kit.go
pkg/controller/integration/integration_controller.go
pkg/controller/integration/kits.go
pkg/controller/integration/kits_test.go
pkg/controller/integration/monitor.go
pkg/controller/integrationkit/monitor.go
pkg/controller/integrationplatform/monitor.go
pkg/controller/kameletbinding/kameletbinding_controller.go
pkg/controller/kameletbinding/monitor.go
pkg/controller/pipe/integration.go
pkg/controller/pipe/integration_test.go
pkg/controller/pipe/monitor.go
pkg/controller/pipe/monitor_test.go
pkg/controller/pipe/pipe_controller.go
pkg/trait/quarkus.go
pkg/trait/quarkus_test.go
pkg/trait/trait_configure.go
pkg/trait/trait_support.go
pkg/trait/util.go
pkg/trait/util_test.go
pkg/util/digest/digest.go

This PR is fixing #5620 and it's adding the proper support to compare traits coming from the spec with specs coming from the annotations. With the PR, the Pipe is in charge to transform the annotations into `.spec.traits` directly, in order to let the Integration to know what to do with them (ie, transferring to the Kit only those that it knows they must be transferred).
Beside that, I've introduced a deprecation notice for supporting trait annotations in Integration, IntegrationKit and IntegrationPlatform as it does not make sense to support both configurations. They will be removed in future versions.
As specified in the code comment, the introduction of certain signature functions change is required to properly support the feature (although deprecated) and will be changed back when we …

fix(traits): annotations refactoring 

---

.github/actions/kamel-build/action.yml
e2e/install/helm/setup_test.go
e2e/install/kustomize/setup_test.go
e2e/install/upgrade/kustomize_upgrade_test.go
e2e/support/test_util.go
script/Makefile

Closes #5632
```release-note
fix(e2e): always build bundle and set local config
```

fix(e2e): always build bundle and set local config

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/cron.adoc
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration-profile.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/trait/cron.go
pkg/apis/camel/v1/trait/zz_generated.deepcopy.go
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_kameletbindings.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/cron.go
pkg/trait/cron_test.go

closes #5121 
```release-note
feat: Added support for timezone configuration at the cron trait.
```

feat(#5121): adding timeZone property to the Cron trait spec

---

pkg/trait/jolokia.go
pkg/trait/jolokia_test.go
pkg/trait/jvm.go
pkg/trait/jvm_test.go

Closes #5666
```release-note
fix(trait): explicit jolokia agent dependency
```

fix(trait): explicit jolokia agent dependency

---

docs/modules/ROOT/pages/installation/registry/registry.adoc
script/prune-camel-k-kit-images.sh

Fix: #5645 Explain how to clean registry 
```release-note
NONE
```

Document how to clean container registry and script to prune.

---

docs/modules/ROOT/pages/installation/uninstalling.adoc
script/Makefile

Closes #5671
```release-note
fix(ci): delete deployment before other resources
```

fix(ci): delete deployment before other resources

---

e2e/common/misc/rest_test.go
e2e/common/traits/builder_test.go
pkg/apis/camel/v1/trait/builder.go
pkg/platform/defaults.go
pkg/platform/defaults_test.go
pkg/trait/builder_test.go

This should be a default setting in order to enhance the parallelism during builds.
```release-note
feat: dependencies default order strategy
```

feat: dependencies default order strategy

---

script/Makefile

By default when set in `ifneq` the command is evaluated on `make <tab>` autocomplete.
```release-note
fix(install): avoid kubectl execution on Makefile evaluation
```

fix(install): avoid kubectl execution on Makefile evaluation

---

build/Dockerfile

Fix the following warnings in `make images`:
```
4 warnings found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 16)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 66)
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 70)
- UndefinedVar: Usage of undefined variable '$MAVEN_OPTS' (line 46)
```
```release-note
chore(build): Fix docker build warnings
```

chore(build): Fix docker build warnings

---

pkg/resources/config/manager/operator-deployment.yaml
script/Makefile

* Raise the default resources request for the deployment
* Only run 2 test in parallel for common advanced e2e tests
```release-note
fix(ci): raise again default resource footprint
```

fix(ci): raise again default resource footprint

---

e2e/support/test_support.go
e2e/support/util/dump.go

On test failure, dump some cluster infos to see if there is a taint on the cluster.
```release-note
chore(ci): Dump some cluster infos
```

chore(ci): Dump some cluster infos

---

script/Makefile

Ref #5696
Most of the failures on the nightly builds are due to kit builds still filling the build queue even after timeout. 
Sinde the common test have been set to `--parallel 1` it make sense to set the same value for smoke-tests. 
```release-note
fix(ci): Reduce parallelism for smoke tests
```

fix(ci): Reduce parallelism for smoke tests

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/mount.adoc
helm/camel-k/crds/crd-integration-platform.yaml
helm/camel-k/crds/crd-integration-profile.yaml
helm/camel-k/crds/crd-integration.yaml
helm/camel-k/crds/crd-kamelet-binding.yaml
helm/camel-k/crds/crd-pipe.yaml
pkg/apis/camel/v1/trait/mount.go
pkg/apis/camel/v1/trait/zz_generated.deepcopy.go
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_kameletbindings.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/mount.go
pkg/trait/mount_test.go
pkg/trait/trait_types.go
pkg/util/resource/config.go

Handles: https://github.com/apache/camel-k/issues/5654
Currently there is no way to add an emptyDir volume without using a pod template. This is useful but using the pod template will override any volumes mounted when using the mount trait e.g. configmaps, secrets.
This PR adds the trait field `mount.empty-dirs` which uses the same syntax as the existing `mount.volumes` trait field. To add an emptyDir volume use:
`trait=mount.empty-dirs=my-empty-dir:/var/test`
📓 Note that the trait field `empty-dirs` will be translated to `emptyDirs` in the integration yaml (if using helm or working with yaml directly)
The example above will add the following to your integration yaml
```yaml
spec:
containers:
- name: integration
volumeMounts:
- mountPath: /var/test
name: my-empty-dir
volumes:
- emptyDir: …
```

(#5654) Added emptyDir support to mount trait

---

pkg/trait/trait_condition_types.go

Fixing #5706 for release-2.3.x branch.
```release-note
Fixed Integration and IntegrationKit condition type values.
```

fix(#5706): removing trait prefix from condition type (release 2.3.x)

---

build/Dockerfile
docs/modules/ROOT/pages/contributing/developers.adoc
go.mod
pkg/apis/camel/v1/knative/types_support.go
pkg/builder/steps.go
pkg/cmd/delete.go
pkg/cmd/kamelet_add_repo.go
pkg/cmd/uninstall.go
pkg/cmd/util.go
pkg/cmd/util_config.go
pkg/controller/integration/build_kit.go
pkg/install/operator.go
pkg/platform/platform.go
pkg/trait/util.go
pkg/util/camel/camel_dependencies.go
pkg/util/camel/camel_runtime_catalog.go
pkg/util/envvar/envvar.go
pkg/util/kubernetes/resolver.go
pkg/util/patch/patch.go
pkg/util/util.go

Ref #5720 
```release-note
chore(ci): Upgrade golang to 1.22
```

chore(ci): Upgrade golang to 1.22

---

addons/vault/aws/aws_secrets_manager.go
addons/vault/azure/azure_key_vault.go
addons/vault/hashicorp/hashicorp_vault.go
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/environment.adoc
pkg/apis/camel/v1/common_types_support.go
pkg/apis/camel/v1/trait/environment.go
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_kameletbindings.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/environment.go
pkg/trait/environment_test.go
pkg/util/envvar/envvar.go

Closes #5522
```release-note
feat(trait): set env as configmaps/secrets
```

feat(trait): set env as configmaps/secrets

---

.github/actions/release-nightly/action.yml
.github/workflows/nightly-release.yml

```release-note
fix(ci): use new infra configuration
```

fix(ci): use new infra configuration

---

pkg/apis/camel/v1/build_type_support_test.go
pkg/apis/camel/v1/build_types_support.go

Closes #5755 
```release-note
Fixed dependencies build order strategy to avoid deadlocks
```

bugfix(#5755): avoiding deadlock between builds with dependencies build order strategy

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/mount.adoc
e2e/common/config/kamelet_config_test.go
e2e/common/config/pipe_config_test.go
pkg/apis/camel/v1/trait/mount.go
pkg/client/camel/informers/externalversions/factory.go
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_kameletbindings.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/kamelets.go
pkg/trait/kamelets_test.go
pkg/trait/knative_service_test.go
pkg/trait/mount.go
pkg/trait/trait_test.go
pkg/trait/trait_types.go
pkg/trait/trait_types_test.go
pkg/trait/util.go

```release-note
chore: remove code deprecated before 2.3
```

chore: remove code deprecated before 2.3

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/cli/cli.adoc
docs/modules/ROOT/pages/installation/advanced/advanced.adoc
docs/modules/ROOT/pages/installation/advanced/build-config.adoc
docs/modules/ROOT/pages/installation/advanced/resources.adoc
docs/modules/ROOT/pages/installation/installation.adoc
docs/modules/ROOT/pages/installation/integrationplatform.adoc
docs/modules/ROOT/pages/installation/registry/registry.adoc
docs/modules/ROOT/pages/observability/logging/operator.adoc
docs/modules/ROOT/pages/observability/monitoring/operator.adoc
pkg/cmd/operator/operator.go

With this PR we make sure that the user provide a configuration for the IntegrationPlatform custom resource. This is required as the generation of the platform is making unstable the installation procedure (where the platform is provided beside the operator configuration). We also make sure to "educate" the user about the presence and the need of this custom resource that drives the behavior of the operator. Above all, we make sure the user to understand they require a container registry in order to properly use the operator.
```release-note
feat: explicit IntegrationPlatform installation
```

feat: explicit IntegrationPlatform installation

---

e2e/common/traits/kamelet_test.go

Closes #5746 
The change is from this CAMEL issue [CAMEL-18858](https://issues.apache.org/jira/browse/CAMEL-18858).
The logs changed from:
```
2024-08-20 09:01:18,136 INFO  [org.apa.cam.k.sup.SourcesSupport] (main) Loading routes from: SourceDefinition{name='camel-k-embedded-flow', language='yaml', type='source', location='file:/etc/camel/sources/camel-k-embedded-flow.yaml', }
2024-08-20 09:01:19,432 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.4.1 (camel-1) is starting
2024-08-20 09:01:19,532 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (started:2)
2024-08-20 09:01:19,533 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (kamelet://capabilities-webhook-source)
2024-08-20 09:01:19,533 INFO …
```

fix(e2e): Kamelet in route logs

---

docs/modules/ROOT/pages/cli/cli.adoc
pkg/cmd/completion.go
pkg/cmd/completion_bash.go
pkg/cmd/completion_zsh.go
pkg/cmd/config.go
pkg/cmd/describe.go
pkg/cmd/describe_integration.go
pkg/cmd/describe_kamelet.go
pkg/cmd/describe_kit.go
pkg/cmd/describe_platform.go
pkg/cmd/dump.go
pkg/cmd/kamelet.go
pkg/cmd/kamelet_add_repo.go
pkg/cmd/kamelet_delete.go
pkg/cmd/kamelet_get.go
pkg/cmd/kamelet_remove_repo.go

```release-note
chore(cmd): deprecate CLIs subcommands
```

chore(cmd): deprecate CLIs subcommands

---

e2e/install/olm/olm_install_test.go
e2e/support/test_support.go

```release-note
fix(e2e): olm needs to create an Integration Platform
```

fix(e2e): olm needs to create an Integration Platform

---

e2e/common/misc/files/cron-yaml.yaml
e2e/support/util/dump.go

Ref #5533 
Avoid having to many pods to read the logs from
```release-note
fix(e2e): Cron e2e logs
```

fix(e2e): Cron e2e logs

---

e2e/support/test_support.go

Ref #5533 
Ensure we get the most recently created pod in tests
```release-note
fix(e2e): Get the most recent pod in e2e tests
```

fix(e2e): Get the most recent pod in e2e tests

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
helm/camel-k/crds/camel-k-crds.yaml
pkg/apis/camel/v1/integrationplatform_types.go
pkg/client/camel/applyconfiguration/camel/v1/integrationplatformbuildspec.go
pkg/controller/integrationplatform/catalog.go
pkg/controller/integrationplatform/catalog_test.go
pkg/controller/integrationplatform/monitor.go
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml

It is useful to know what core version of Camel the runtime is running
```
$ k get itp --all-namespaces
NAMESPACE   NAME      PHASE   BUILD STRATEGY   PUBLISH STRATEGY   REGISTRY ADDRESS   DEFAULT RUNTIME   CAMEL VERSION
camel-k     camel-k   Ready   routine          Jib                10.100.107.57      3.8.1             4.4.1
```
```release-note
feat(api): expose Camel core version
```

feat(api): expose Camel core version

---

pkg/trait/trait_types.go

It is good to have a limit for security reasons and it is also a workaround for #5752
Closes #5752
```release-note
fix(trait): add size to emptydir
```

fix(trait): add size to emptydir

---

e2e/common/misc/files/cron-yaml.yaml
e2e/support/test_support.go
e2e/support/util/dump.go

Backport fix https://github.com/apache/camel-k/pull/5808
Backport fix https://github.com/apache/camel-k/pull/5790
Ref #5533 
```release-note
fix(e2e): Get the most recent pod in e2e tests and add logs
```

[Backport 2.4.x]: fix(e2e): Get the most recent pod in e2e tests and add logs

---

pkg/apis/camel/v1/integration_types.go
pkg/controller/integration/integration_controller.go
pkg/controller/integration/monitor.go
pkg/controller/integration/monitor_test.go
pkg/controller/integration/monitor_unknown.go

During an IntegrationPlatform recreation, there is now way to properly set the traits, resulting in monitoring errors.
Closes #5836
```release-note
feat(api): introduce an Uknown status
```

feat(api): introduce an Uknown status

---

e2e/advanced/operator_restart_test.go
e2e/advanced/operator_resume_unknown_test.go
e2e/support/test_support.go
pkg/controller/integration/monitor.go
pkg/controller/integration/monitor_test.go
pkg/controller/integration/monitor_unknown.go
pkg/controller/integrationplatform/create.go
pkg/controller/integrationplatform/create_test.go
pkg/controller/integrationplatform/kamelets.go
pkg/controller/integrationplatform/kamelets_test.go

If an IntegrationPlatform is deleted, when the Integration requires monitoring it fails
```release-note
fix(ctrl): resume from unknown
```

fix(ctrl): resume from unknown

---

pkg/trait/builder.go
pkg/trait/builder_test.go

Closes #5838
```release-note
fix(trait): builder configuration from platform
```

fix(trait): builder configuration from platform

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
helm/camel-k/crds/camel-k-crds.yaml
pkg/apis/camel/v1/integrationprofile_types.go
pkg/controller/integrationprofile/initialize.go
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml

Closes #5869
```release-note
feat(api): IntegrationProfile deprecation
```

feat(api): IntegrationProfile deprecation

---

docs/modules/ROOT/pages/configuration/build-time-properties.adoc
docs/modules/ROOT/pages/configuration/camel-properties.adoc
pkg/cmd/run.go
pkg/cmd/run_support.go
pkg/cmd/run_test.go
pkg/trait/camel.go
pkg/trait/container.go
pkg/trait/mount.go
pkg/trait/mount_test.go
pkg/trait/trait_test.go
pkg/trait/trait_types.go
pkg/trait/trait_types_test.go
pkg/util/kubernetes/lookup.go

Beside that, we're deprecating the access to Secret and Configmap by either the CLI or the operator
Closes #5863
```release-note
feat(trait): support Camel cloud native properties
```

feat(trait): support Camel cloud native properties

---

e2e/common/traits/files/petstore-api.yaml
e2e/common/traits/files/petstore.yaml
e2e/common/traits/openapi_test.go

Altough the feature is deprecated it is good we verify with testing it still works as expected
```release-note
chore(ci): added back openapi trait test
```

chore(ci): added back openapi trait test

---

helm/camel-k/templates/operator-service-account.yaml
helm/camel-k/values.yaml

We'd like to allow the operator to push images to Google Artifact Registry using the workload identity feature in the GCP. This requires to specify the Google Service Account in an annotation to the Kubernetes service account the `camel-k-operator` deployment is using:
```
annotations:
iam.gke.io/gcp-service-account: ACCOUNT@PROJECT.iam.gserviceaccount.com
```

Allow to specify annotations for operator Kubernetes Service Account

---

pkg/cmd/run.go

Hey there!
Thank you for doing such awesome work with that project.
While using the `kamel` tool, I tried to exclusively configure my deployment via the `kamel-config.yaml` file. Due to there is a `sources` array in that config file, I think specifying the sources there should be enough to run an integration rather than needing to define at least one source at `kamel run [file to run]`.
My patch skips the error if no source file is provided via arguments and at least one source is provided in the configuration file. Otherwise, there will be an error if the sources are only provided in config file.

fix(cli): allow specifying integration run sources exclusively via config file

---

go.mod
go.sum

```release-note
chore(deps): bump github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring from 0.73.2 to 0.76.2
```

chore(deps): bump github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring from 0.73.2 to 0.76.2

---

pkg/trait/mount.go

Closes #5924
```release-note
fix(trait): use a configmap index
```

fix(trait): use a configmap index

---

pkg/controller/kameletbinding/initialize_test.go
pkg/controller/kameletbinding/integration.go
pkg/util/bindings/catalog.go

Closes #5953
```release-note
NONE
```

[Release 2.5.x] fix(binding): don't panic if no binding available

---

pkg/resources/config/crd/kustomization.yaml
pkg/resources/config/manifests/kustomization.yaml

This PR fixes the Kustomize installation by switching over deprecated `commonLabels` fields with `labels` field.
Before:
After:
PR fixes: https://github.com/apache/camel-k/issues/5928
```release-note
NONE
```

[chore] Fix Kustomize Installation

---

docs/antora.yml
docs/modules/ROOT/pages/installation/installation.adoc
script/update_docs.sh

[Release 2.5.x] fix(docs): last release version

---

pkg/resources/config/manifests/kustomization.yaml
pkg/resources/config/samples/kustomization.yaml
pkg/resources/config/scorecard/kustomization.yaml

This PR fixes the deprecated Kustomize fields (patchesStrategicMerge and patchesJson6902) with patches.
Fixes: https://github.com/apache/camel-k/issues/5972
```release-note
NONE
```

[chore] Fix Kustomize Fields

---

pkg/util/camel/camel_dependencies.go

```release-note
chore: remove registry maven dependency leftover
```

chore: remove registry maven dependency leftover

---

docs/modules/ROOT/pages/installation/registry/registry.adoc

This is to conform with how the images are being populated into the registry (as well as how it relates to the IntegrationPlatform specs).
Of note, it uses the registry.organization vs. namespace. It also uses '/camel-k-kit-...' vs. just '/kit-...'.

update registry location

---

.github/workflows/native.yml
.github/workflows/nightly-latest-runtime.yml
.github/workflows/nightly-quarkus-plain-runtime.yml
docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/camel.adoc
helm/camel-k/crds/camel-k-crds.yaml
pkg/apis/camel/v1/camelcatalog_types_support.go
pkg/apis/camel/v1/common_types.go
pkg/apis/camel/v1/trait/camel.go
pkg/builder/quarkus.go
pkg/builder/quarkus_test.go
pkg/controller/integrationplatform/monitor.go
pkg/resources/config/crd/bases/camel.apache.org_integrationkits.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/camel.go
pkg/trait/environment.go
pkg/trait/mount.go
pkg/trait/telemetry.go
pkg/util/camel/camel_dependencies.go
pkg/util/camel/camel_runtime_catalog.go
pkg/util/camel/camel_util.go

Added the support for plain Quarkus runtime. Trait `camel.runtime-provider` is in charge to control the possibility to use `plain-quarkus`.
```release-note
feat(runtime): enable plain Quarkus runtime
```

feat(runtime): enable plain Quarkus runtime

---

e2e/common/cli/promote_test.go
pkg/cmd/bind.go
pkg/cmd/promote.go
pkg/cmd/promote_test.go

Introduced a `--export-gitops-dir` flag that will create a simple opinionated Kustomize based GitOps overlay directory. The result can be used to be stored in Git and be used as a source for any GitOps pipeline.
```
kamel promote my-it --to my-dest-namespace --export-gitops-dir /path/to/export/dir
```
Closes https://github.com/apache/camel-k/issues/5456
```release-note
feat(cmd): kamel promote --export-gitops-dir
```

feat(cmd): kamel promote --export-gitops-dir

---

e2e/common/config/config_test.go
e2e/common/traits/builder_test.go
pkg/controller/integrationplatform/monitor.go
pkg/trait/mount.go
pkg/util/source/inspector.go
pkg/util/source/inspector_java_source_test.go
pkg/util/source/inspector_xml_test.go
pkg/util/source/inspector_yaml.go
pkg/util/source/inspector_yaml_test.go
pkg/util/util.go

```release-note
fix(e2e): tests failure in Plain Quarkus runtime
```

fix(e2e): tests failure in Plain Quarkus runtime

---

pkg/cmd/promote.go

If required, this must be enabled by the user which needs to have the proper administrative privileges.
```release-note
NONE
```

chore(cmd): remove system puller

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
helm/camel-k/crds/camel-k-crds.yaml
pkg/apis/camel/v1/trait/ingress.go
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/ingress.go
pkg/trait/ingress_test.go

Related to issue #5981.
_Can be reviewed again at a later point in time/in a separate PR._
Example usage:
```bash
build/_output/bin/kamel-amd64 run test/src/multi-path.yml -o yaml --trait ingress.paths="/api/v1/multi" --trait ingress.paths="/api/v1/path" > test/base/multi-path.yml
```
... generates:
```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
annotations:
camel.apache.org/operator.id: camel-k
creationTimestamp: null
name: multi-path
spec:
flows:
- from:
steps:
- set-header:
name: Content-Type
simple: application/json
- set-body:
constant: '{"welcome": "multi"}'
uri: rest:get:/api/v1/multi
- from:
steps:
- set-header:
name: Content-Type
simple: application/json
- set-body:
constant: '{"welcome": "path"}'
uri: rest:get:/api/v1/path
traits:
ingress:
paths: 
- …
```

feat(trait): add support for multiple ingress paths

---

pkg/util/source/inspector.go
pkg/util/source/inspector_java_source_test.go
pkg/util/source/inspector_xml.go
pkg/util/source/inspector_xml_test.go
pkg/util/source/inspector_yaml.go
pkg/util/source/inspector_yaml_test.go

With this PR we're going to support the management of error handler directly in the DSL.
```release-note
feat: support Error Handler
```

feat: support Error Handler

---

pkg/resources/config/manifests/kustomization.yaml
pkg/resources/config/samples/kustomization.yaml
pkg/resources/config/scorecard/kustomization.yaml

Reverts apache/camel-k#5982
Apparently this commit is causing OLM installation problems. We must verify if reverting does fix the problem.

Revert "[chore] Fix Kustomize Fields"

---

pkg/apis/camel/v1/trait/ingress.go

Move depreciation notice from ingress.paths to ingress.path.

move depreciation notice to the ingress path

---

pkg/builder/runtime_support.go
pkg/trait/jvm.go
pkg/trait/quarkus.go

Closes #6021
```release-note
NONE
```

fix(trait): deprecate old native profile

---

pkg/trait/prometheus.go

Closes #6014
```release-note
fix(trait): workaround Knative h2c port name
```

fix(trait): workaround Knative h2c port name

---

build/Dockerfile
pkg/util/defaults/defaults.go
script/Makefile

Included a 21-jdk base image beside the default 17-jdk base image for the operator
Closes #5805
```release-note
feat(ci): multiple JDK images
```

feat(ci): multiple JDK images

---

pkg/controller/integrationplatform/kamelets.go
pkg/util/jvm/keystore.go
pkg/util/jvm/keystore_test.go

fix: keystore generation output

---

e2e/native/native_with_sources_test.go
pkg/controller/build/build_pod.go
pkg/controller/build/build_pod_test.go
pkg/trait/builder.go

Closes #5811
```release-note
feat(ctrl): default builder Pod resources
```

feat(ctrl): default builder Pod resources

---

e2e/common/traits/cron_test.go

Closes #5912
```release-note
fix(e2e): wait for Pod readiness
```

fix(e2e): wait for Pod readiness

---

pkg/controller/integrationplatform/monitor.go
pkg/controller/integrationplatform/monitor_test.go

Closes #6080
```release-note
fix(ctrl): set ready state when reconciling back to normal
```

fix(ctrl): set ready state when reconciling back to normal

---

pkg/builder/quarkus.go
pkg/controller/integration/kits.go
pkg/controller/integrationkit/initialize.go
pkg/trait/camel.go

We were previously forced to use only the same version available through Camel K runtime catalog
```release-note
NONE
```

fix(builder): allow any plain Quarkus runtime

---

helm/camel-k/templates/operator-deployment.yaml
helm/camel-k/values.yaml

Possibility to define extra environment variables for operator deployment / pod.
Can be used for example to access private GitHub repositories for downloading custom `Kamelet`.
[Zulip thread](https://camel.zulipchat.com/#narrow/channel/257299-camel-k/topic/.E2.9C.94.20kamelet.20cataglog.20inside.20private.20git.20repository)
```release-note
fix(helm): extra environment variables
```

fix(helm): extra environment variables

---

pkg/apis/camel/v1/integration_types_support.go

Closes #6098
```release-note
fix(api): count all sources only once
```

fix(api): count all sources only once

---

e2e/kafka/setup/kafka-ephemeral.yaml

Closes #6159 
Replace Zookeeper in kafka cluster configuration by KRaft as zookeeper is no longer supported starting 0.46.0 strimzi.
See https://github.com/strimzi/strimzi-kafka-operator/tree/release-0.46.x/examples for reference configuration on usage of KRaft.
```release-note
fix(ci): Use KRaft for kafka-cluster
```

fix(ci): Use KRaft for kafka-cluster

---

docs/modules/ROOT/pages/pipes/bind-cli.adoc
docs/modules/ROOT/pages/pipes/error-handler.adoc
docs/modules/ROOT/pages/pipes/pipes.adoc
docs/modules/ROOT/pages/pipes/promoting.adoc

Corrected language errors, and made labelling of code samples consistent. 
Changed NOTE format to longer format for all Notes and Warnings.
Minor typos and other fixes.
```release-note
NONE
```

Language and formatting corrections to Pipes documentation

---

pkg/controller/integration/kits.go
pkg/controller/integration/kits_test.go

```release-note
fix: Correctly matching runtime versions when searching for an Integration Kit
```

fix(#6182): fixing integration x kit matching algorithm for runtime version

---

go.mod
go.sum
pkg/apis/camel/v1/common_types_support.go
script/Makefile

Dependabot has been failing due to the change in mergo url: https://github.com/darccio/mergo?tab=readme-ov-file#important-notes
+ setting language native (en) before running test as it does not works on Linux with other language
```release-note
fix(dep): Update mergo to prod ready v1 dario.cat/mergo
```

fix(dep): Update mergo to prod ready v1 dario.cat/mergo

---

pkg/apis/camel/v1/integrationkit_types.go
pkg/controller/integrationkit/build.go
pkg/trait/builder.go

* when this is higher than actual timeout
Closes #6061
```release-note
NONE
```

feat(trait): use sensible timeout for Quarkus native builder

---

e2e/common/traits/cron_test.go
e2e/common/traits/files/cron-fallback.yaml
e2e/support/test_support.go

Closes #5912
```release-note
NONE
```

[Release 2.7.x] fix(e2e): check succeeded pods instead of running pods

---

e2e/common/cli/promote_test.go
pkg/builder/common_test.go
pkg/builder/git_test.go
pkg/builder/jib_test.go
pkg/builder/quarkus_test.go
pkg/cmd/bind_test.go
pkg/cmd/promote_test.go
pkg/cmd/run_test.go
pkg/cmd/source/util_test.go
pkg/controller/integrationplatform/create_test.go
pkg/controller/integrationplatform/kamelets_test.go
pkg/util/digest/digest_test.go
pkg/util/maven/maven_command_test.go
pkg/util/sync/file_test.go

Closes:
- https://github.com/apache/camel-k/issues/6192
Changes:
- temporary files created during tests are placed in a temporary directory deleted by the testing framework
- all the top-level temporary directories created for the tests are now deleted by the testing framework
- pattern in the temporary directory is lost as the testing framework does not allow to add the pattern, hence we use the default temp dir name
- test `TestPermissionDenied` changes the file permissions to the temporary directory, therefore we need to change it back so that the testing framework can delete the folder
- tests in `modeline_test.go` that use `util.WithTempDir` (from `pkg/util/util.go:465`) are untouched because I thought it was good to use this util method in tests as well, it indirectly verifies this …

Let Golang testing framework clean any temporary data

---

docs/modules/ROOT/partials/apis/camel-k-crds.adoc
docs/modules/traits/pages/health.adoc
helm/camel-k/crds/camel-k-crds.yaml
pkg/apis/camel/v1/trait/health.go
pkg/resources/config/crd/bases/camel.apache.org_integrationplatforms.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrationprofiles.yaml
pkg/resources/config/crd/bases/camel.apache.org_integrations.yaml
pkg/resources/config/crd/bases/camel.apache.org_pipes.yaml
pkg/trait/health.go

Closes #3877
```release-note
NONE
```

fix(trait): health ports configuration
